// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.concurrent.CompletionStage;

import j2act.WebPath;

/**
 * The browser's Clipboard, run remotely through window() (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/Clipboard">MDN: Clipboard</a>
 */
public final class Clipboard {

  private final WebPath path;

  /** Made by window() and the getters of other facades. */
  public Clipboard(WebPath path) {
    this.path = path;
  }

  /**
   * Clipboard.readText(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Clipboard/readText">MDN: Clipboard.readText</a>
   */
  public CompletionStage<String> readText() {
    return path.invoke("readText", null, WebPath::string);
  }

  /**
   * Clipboard.writeText(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Clipboard/writeText">MDN: Clipboard.writeText</a>
   */
  public CompletionStage<Void> writeText(String data) {
    return path.invoke("writeText", null, WebPath::none, data);
  }
}
