// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.concurrent.CompletionStage;

import j2act.WebPath;

/**
 * The browser's Element, run remotely through window() (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/Element">MDN: Element</a>
 */
public final class Element {

  private final WebPath path;

  /** Made by window() and the getters of other facades. */
  public Element(WebPath path) {
    this.path = path;
  }

  /**
   * Element.id in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/id">MDN: Element.id</a>
   */
  public CompletionStage<String> id() {
    return path.read("id", null, WebPath::string);
  }

  /**
   * Element.id in the browser. Sets it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/id">MDN: Element.id</a>
   */
  public CompletionStage<Void> id(String value) {
    return path.write("id", value);
  }

  /**
   * Element.getAttribute(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/getAttribute">MDN: Element.getAttribute</a>
   */
  public CompletionStage<String> getAttribute(String qualifiedName) {
    return path.invoke("getAttribute", null, WebPath::string, qualifiedName);
  }

  /**
   * Element.setAttribute(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/setAttribute">MDN: Element.setAttribute</a>
   */
  public CompletionStage<Void> setAttribute(String qualifiedName, String value) {
    return path.invoke("setAttribute", null, WebPath::none, qualifiedName, value);
  }

  /**
   * Element.removeAttribute(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/removeAttribute">MDN: Element.removeAttribute</a>
   */
  public CompletionStage<Void> removeAttribute(String qualifiedName) {
    return path.invoke("removeAttribute", null, WebPath::none, qualifiedName);
  }

  /**
   * Element.requestFullscreen(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/requestFullscreen">MDN: Element.requestFullscreen</a>
   */
  public CompletionStage<Void> requestFullscreen() {
    return path.invoke("requestFullscreen", null, WebPath::none);
  }

  /**
   * Element.requestFullscreen(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/requestFullscreen">MDN: Element.requestFullscreen</a>
   */
  public CompletionStage<Void> requestFullscreen(FullscreenOptions options) {
    return path.invoke("requestFullscreen", null, WebPath::none, options);
  }

  /**
   * Element.scrollIntoView(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/scrollIntoView">MDN: Element.scrollIntoView</a>
   */
  public CompletionStage<Void> scrollIntoView() {
    return path.invoke("scrollIntoView", null, WebPath::none);
  }

  /**
   * Element.scrollIntoView(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/scrollIntoView">MDN: Element.scrollIntoView</a>
   */
  public CompletionStage<Void> scrollIntoView(boolean arg) {
    return path.invoke("scrollIntoView", null, WebPath::none, arg);
  }

  /**
   * Element.scrollIntoView(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/scrollIntoView">MDN: Element.scrollIntoView</a>
   */
  public CompletionStage<Void> scrollIntoView(ScrollIntoViewOptions arg) {
    return path.invoke("scrollIntoView", null, WebPath::none, arg);
  }

  /**
   * Element.querySelector(...) in the browser. A path step only: nothing runs until a call on the result.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Element/querySelector">MDN: Element.querySelector</a>
   */
  public Element querySelector(String selectors) {
    return new Element(path.call("querySelector", selectors));
  }

  /**
   * Element.focus(...) in the browser.
   */
  public CompletionStage<Void> focus() {
    return path.invoke("focus", null, WebPath::none);
  }

  /**
   * Element.focus(...) in the browser.
   */
  public CompletionStage<Void> focus(FocusOptions options) {
    return path.invoke("focus", null, WebPath::none, options);
  }

  /**
   * Element.blur(...) in the browser.
   */
  public CompletionStage<Void> blur() {
    return path.invoke("blur", null, WebPath::none);
  }
}
