// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.LinkedHashMap;
import java.util.Map;

import j2act.WebPath;

/**
 * The FocusOptions dictionary: set the members you need, e.g. new FocusOptions().preventScroll(...) (ADR 0022).
 */
public final class FocusOptions implements WebPath.Value {

  private final Map<String, Object> fields = new LinkedHashMap<>();

  /**
   * The preventScroll member.
   */
  public FocusOptions preventScroll(boolean preventScroll) {
    fields.put("preventScroll", preventScroll);
    return this;
  }

  /**
   * The focusVisible member.
   */
  public FocusOptions focusVisible(boolean focusVisible) {
    fields.put("focusVisible", focusVisible);
    return this;
  }

  @Override public Object toJson() {
    return fields;
  }
}
