// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.LinkedHashMap;
import java.util.Map;

import j2act.WebPath;

/**
 * The FullscreenOptions dictionary: set the members you need, e.g. new FullscreenOptions().keyboardLock(...) (ADR 0022).
 */
public final class FullscreenOptions implements WebPath.Value {

  private final Map<String, Object> fields = new LinkedHashMap<>();

  /**
   * The keyboardLock member. A FullscreenKeyboardLock: "browser" "none".
   */
  public FullscreenOptions keyboardLock(String keyboardLock) {
    fields.put("keyboardLock", keyboardLock);
    return this;
  }

  /**
   * The navigationUI member. A FullscreenNavigationUI: "auto" "show" "hide".
   */
  public FullscreenOptions navigationUI(String navigationUI) {
    fields.put("navigationUI", navigationUI);
    return this;
  }

  @Override public Object toJson() {
    return fields;
  }
}
