// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import j2act.WebPath;

/**
 * A snapshot of the browser's GeolocationPosition: its attributes when the call completed, copied into Java (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/GeolocationPosition">MDN: GeolocationPosition</a>
 */
public final class GeolocationPosition {

  /** Which attributes the browser copies out, nested for snapshot-typed ones. */
  static final String SHAPE = "{\"coords\":{\"accuracy\":1,\"latitude\":1,\"longitude\":1,\"altitude\":1,\"altitudeAccuracy\":1,\"heading\":1,\"speed\":1},\"timestamp\":1}";

  private final GeolocationCoordinates coords;
  private final Long timestamp;

  private GeolocationPosition(java.util.Map<?, ?> json) {
    this.coords = WebPath.decode(json.get("coords"), GeolocationCoordinates::from);
    this.timestamp = WebPath.decode(json.get("timestamp"), WebPath::longValue);
  }

  static GeolocationPosition from(Object json) {
    return json == null ? null : new GeolocationPosition((java.util.Map<?, ?>) json);
  }

  /**
   * GeolocationPosition.coords in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/GeolocationPosition/coords">MDN: GeolocationPosition.coords</a>
   */
  public GeolocationCoordinates coords() {
    return coords;
  }

  /**
   * GeolocationPosition.timestamp in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/GeolocationPosition/timestamp">MDN: GeolocationPosition.timestamp</a>
   */
  public Long timestamp() {
    return timestamp;
  }
}
