// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.concurrent.CompletionStage;

import j2act.WebPath;

/**
 * The browser's Geolocation, run remotely through window() (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/Geolocation">MDN: Geolocation</a>
 */
public final class Geolocation {

  private final WebPath path;

  /** Made by window() and the getters of other facades. */
  public Geolocation(WebPath path) {
    this.path = path;
  }

  /**
   * Geolocation.getCurrentPosition(...) in the browser. Callback style in the browser: the stage completes with the first callback and fails with the second.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Geolocation/getCurrentPosition">MDN: Geolocation.getCurrentPosition</a>
   */
  public CompletionStage<GeolocationPosition> getCurrentPosition() {
    return path.invokeCallbacks("getCurrentPosition", 0, 1, GeolocationPosition.SHAPE, GeolocationPosition::from, null, null);
  }

  /**
   * Geolocation.getCurrentPosition(...) in the browser. Callback style in the browser: the stage completes with the first callback and fails with the second.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Geolocation/getCurrentPosition">MDN: Geolocation.getCurrentPosition</a>
   */
  public CompletionStage<GeolocationPosition> getCurrentPosition(PositionOptions options) {
    return path.invokeCallbacks("getCurrentPosition", 0, 1, GeolocationPosition.SHAPE, GeolocationPosition::from, null, null, options);
  }
}
