// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.List;
import java.util.concurrent.CompletionStage;

import j2act.WebPath;

/**
 * The browser's Navigator, run remotely through window() (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator">MDN: Navigator</a>
 */
public final class Navigator {

  private final WebPath path;

  /** Made by window() and the getters of other facades. */
  public Navigator(WebPath path) {
    this.path = path;
  }

  /**
   * Navigator.clipboard in the browser. A path step only: nothing runs until a call on it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/clipboard">MDN: Navigator.clipboard</a>
   */
  public Clipboard clipboard() {
    return new Clipboard(path.get("clipboard"));
  }

  /**
   * Navigator.geolocation in the browser. A path step only: nothing runs until a call on it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/geolocation">MDN: Navigator.geolocation</a>
   */
  public Geolocation geolocation() {
    return new Geolocation(path.get("geolocation"));
  }

  /**
   * Navigator.permissions in the browser. A path step only: nothing runs until a call on it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/permissions">MDN: Navigator.permissions</a>
   */
  public Permissions permissions() {
    return new Permissions(path.get("permissions"));
  }

  /**
   * Navigator.share(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/share">MDN: Navigator.share</a>
   */
  public CompletionStage<Void> share() {
    return path.invoke("share", null, WebPath::none);
  }

  /**
   * Navigator.share(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/share">MDN: Navigator.share</a>
   */
  public CompletionStage<Void> share(ShareData data) {
    return path.invoke("share", null, WebPath::none, data);
  }

  /**
   * Navigator.canShare(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/canShare">MDN: Navigator.canShare</a>
   */
  public CompletionStage<Boolean> canShare() {
    return path.invoke("canShare", null, WebPath::bool);
  }

  /**
   * Navigator.canShare(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/canShare">MDN: Navigator.canShare</a>
   */
  public CompletionStage<Boolean> canShare(ShareData data) {
    return path.invoke("canShare", null, WebPath::bool, data);
  }

  /**
   * Navigator.appCodeName in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/appCodeName">MDN: Navigator.appCodeName</a>
   */
  public CompletionStage<String> appCodeName() {
    return path.read("appCodeName", null, WebPath::string);
  }

  /**
   * Navigator.appName in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/appName">MDN: Navigator.appName</a>
   */
  public CompletionStage<String> appName() {
    return path.read("appName", null, WebPath::string);
  }

  /**
   * Navigator.appVersion in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/appVersion">MDN: Navigator.appVersion</a>
   */
  public CompletionStage<String> appVersion() {
    return path.read("appVersion", null, WebPath::string);
  }

  /**
   * Navigator.platform in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/platform">MDN: Navigator.platform</a>
   */
  public CompletionStage<String> platform() {
    return path.read("platform", null, WebPath::string);
  }

  /**
   * Navigator.product in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/product">MDN: Navigator.product</a>
   */
  public CompletionStage<String> product() {
    return path.read("product", null, WebPath::string);
  }

  /**
   * Navigator.productSub in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/productSub">MDN: Navigator.productSub</a>
   */
  public CompletionStage<String> productSub() {
    return path.read("productSub", null, WebPath::string);
  }

  /**
   * Navigator.userAgent in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/userAgent">MDN: Navigator.userAgent</a>
   */
  public CompletionStage<String> userAgent() {
    return path.read("userAgent", null, WebPath::string);
  }

  /**
   * Navigator.vendor in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/vendor">MDN: Navigator.vendor</a>
   */
  public CompletionStage<String> vendor() {
    return path.read("vendor", null, WebPath::string);
  }

  /**
   * Navigator.vendorSub in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/vendorSub">MDN: Navigator.vendorSub</a>
   */
  public CompletionStage<String> vendorSub() {
    return path.read("vendorSub", null, WebPath::string);
  }

  /**
   * Navigator.taintEnabled(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/taintEnabled">MDN: Navigator.taintEnabled</a>
   */
  public CompletionStage<Boolean> taintEnabled() {
    return path.invoke("taintEnabled", null, WebPath::bool);
  }

  /**
   * Navigator.oscpu in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/oscpu">MDN: Navigator.oscpu</a>
   */
  public CompletionStage<String> oscpu() {
    return path.read("oscpu", null, WebPath::string);
  }

  /**
   * Navigator.language in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/language">MDN: Navigator.language</a>
   */
  public CompletionStage<String> language() {
    return path.read("language", null, WebPath::string);
  }

  /**
   * Navigator.languages in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/languages">MDN: Navigator.languages</a>
   */
  public CompletionStage<List<String>> languages() {
    return path.read("languages", null, json -> WebPath.list(json, WebPath::string));
  }

  /**
   * Navigator.registerProtocolHandler(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/registerProtocolHandler">MDN: Navigator.registerProtocolHandler</a>
   */
  public CompletionStage<Void> registerProtocolHandler(String scheme, String url) {
    return path.invoke("registerProtocolHandler", null, WebPath::none, scheme, url);
  }

  /**
   * Navigator.unregisterProtocolHandler(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/unregisterProtocolHandler">MDN: Navigator.unregisterProtocolHandler</a>
   */
  public CompletionStage<Void> unregisterProtocolHandler(String scheme, String url) {
    return path.invoke("unregisterProtocolHandler", null, WebPath::none, scheme, url);
  }

  /**
   * Navigator.cookieEnabled in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/cookieEnabled">MDN: Navigator.cookieEnabled</a>
   */
  public CompletionStage<Boolean> cookieEnabled() {
    return path.read("cookieEnabled", null, WebPath::bool);
  }

  /**
   * Navigator.javaEnabled(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/javaEnabled">MDN: Navigator.javaEnabled</a>
   */
  public CompletionStage<Boolean> javaEnabled() {
    return path.invoke("javaEnabled", null, WebPath::bool);
  }

  /**
   * Navigator.pdfViewerEnabled in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/pdfViewerEnabled">MDN: Navigator.pdfViewerEnabled</a>
   */
  public CompletionStage<Boolean> pdfViewerEnabled() {
    return path.read("pdfViewerEnabled", null, WebPath::bool);
  }

  /**
   * Navigator.hardwareConcurrency in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Navigator/hardwareConcurrency">MDN: Navigator.hardwareConcurrency</a>
   */
  public CompletionStage<Long> hardwareConcurrency() {
    return path.read("hardwareConcurrency", null, WebPath::longValue);
  }
}
