// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.concurrent.CompletionStage;

import j2act.WebPath;

/**
 * The Notification interface object in the browser (window.Notification), run remotely through window() (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/Notification">MDN: Notification</a>
 */
public final class Notification {

  private final WebPath path;

  /** Made by window() and the getters of other facades. */
  public Notification(WebPath path) {
    this.path = path;
  }

  /**
   * Notification.constructor(...) in the browser. Runs new Notification(...) in the browser; the object stays there.
   */
  public CompletionStage<Void> construct(String title) {
    return path.construct(title);
  }

  /**
   * Notification.constructor(...) in the browser. Runs new Notification(...) in the browser; the object stays there.
   */
  public CompletionStage<Void> construct(String title, NotificationOptions options) {
    return path.construct(title, options);
  }

  /**
   * Notification.permission in the browser. A NotificationPermission: "default" "denied" "granted".
   */
  public CompletionStage<String> permission() {
    return path.read("permission", null, WebPath::string);
  }

  /**
   * Notification.requestPermission(...) in the browser. A NotificationPermission: "default" "denied" "granted".
   */
  public CompletionStage<String> requestPermission() {
    return path.invoke("requestPermission", null, WebPath::string);
  }

  /**
   * Notification.maxActions in the browser.
   */
  public CompletionStage<Long> maxActions() {
    return path.read("maxActions", null, WebPath::longValue);
  }
}
