// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import j2act.WebPath;

/**
 * The NotificationOptions dictionary: set the members you need, e.g. new NotificationOptions().dir(...) (ADR 0022).
 */
public final class NotificationOptions implements WebPath.Value {

  private final Map<String, Object> fields = new LinkedHashMap<>();

  /**
   * The dir member. A NotificationDirection: "auto" "ltr" "rtl".
   */
  public NotificationOptions dir(String dir) {
    fields.put("dir", dir);
    return this;
  }

  /**
   * The lang member.
   */
  public NotificationOptions lang(String lang) {
    fields.put("lang", lang);
    return this;
  }

  /**
   * The body member.
   */
  public NotificationOptions body(String body) {
    fields.put("body", body);
    return this;
  }

  /**
   * The navigate member.
   */
  public NotificationOptions navigate(String navigate) {
    fields.put("navigate", navigate);
    return this;
  }

  /**
   * The tag member.
   */
  public NotificationOptions tag(String tag) {
    fields.put("tag", tag);
    return this;
  }

  /**
   * The image member.
   */
  public NotificationOptions image(String image) {
    fields.put("image", image);
    return this;
  }

  /**
   * The icon member.
   */
  public NotificationOptions icon(String icon) {
    fields.put("icon", icon);
    return this;
  }

  /**
   * The badge member.
   */
  public NotificationOptions badge(String badge) {
    fields.put("badge", badge);
    return this;
  }

  /**
   * The timestamp member.
   */
  public NotificationOptions timestamp(long timestamp) {
    fields.put("timestamp", timestamp);
    return this;
  }

  /**
   * The renotify member.
   */
  public NotificationOptions renotify(boolean renotify) {
    fields.put("renotify", renotify);
    return this;
  }

  /**
   * The silent member.
   */
  public NotificationOptions silent(Boolean silent) {
    fields.put("silent", silent);
    return this;
  }

  /**
   * The requireInteraction member.
   */
  public NotificationOptions requireInteraction(boolean requireInteraction) {
    fields.put("requireInteraction", requireInteraction);
    return this;
  }

  /**
   * The data member.
   */
  public NotificationOptions data(Object data) {
    fields.put("data", data);
    return this;
  }

  /**
   * The actions member.
   */
  public NotificationOptions actions(List<NotificationAction> actions) {
    fields.put("actions", actions);
    return this;
  }

  @Override public Object toJson() {
    return fields;
  }
}
