// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.LinkedHashMap;
import java.util.Map;

import j2act.WebPath;

/**
 * The NotificationAction dictionary: set the members you need, e.g. new NotificationAction().action(...) (ADR 0022).
 */
public final class NotificationAction implements WebPath.Value {

  private final Map<String, Object> fields = new LinkedHashMap<>();

  /**
   * Required. The action member.
   */
  public NotificationAction action(String action) {
    fields.put("action", action);
    return this;
  }

  /**
   * Required. The title member.
   */
  public NotificationAction title(String title) {
    fields.put("title", title);
    return this;
  }

  /**
   * The navigate member.
   */
  public NotificationAction navigate(String navigate) {
    fields.put("navigate", navigate);
    return this;
  }

  /**
   * The icon member.
   */
  public NotificationAction icon(String icon) {
    fields.put("icon", icon);
    return this;
  }

  @Override public Object toJson() {
    return fields;
  }
}
