// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.

/**
 * The window() facade (ADR 0022): the browser's Web APIs, mirrored one to one from WebIDL and
 * run remotely. Start from ComponentTag.window(). Getters of interfaces only build a path;
 * every other call runs in the browser, after the update's patch or inside the gesture that
 * bound it, and returns a CompletionStage that fails with a BrowserException.
 */
package j2act.web;
