// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import j2act.WebPath;

/**
 * A snapshot of the browser's PermissionStatus: its attributes when the call completed, copied into Java (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/PermissionStatus">MDN: PermissionStatus</a>
 */
public final class PermissionStatus {

  /** Which attributes the browser copies out, nested for snapshot-typed ones. */
  static final String SHAPE = "{\"state\":1,\"name\":1}";

  private final String state;
  private final String name;

  private PermissionStatus(java.util.Map<?, ?> json) {
    this.state = WebPath.decode(json.get("state"), WebPath::string);
    this.name = WebPath.decode(json.get("name"), WebPath::string);
  }

  static PermissionStatus from(Object json) {
    return json == null ? null : new PermissionStatus((java.util.Map<?, ?>) json);
  }

  /**
   * PermissionStatus.state in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/PermissionStatus/state">MDN: PermissionStatus.state</a>
   */
  public String state() {
    return state;
  }

  /**
   * PermissionStatus.name in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/PermissionStatus/name">MDN: PermissionStatus.name</a>
   */
  public String name() {
    return name;
  }
}
