// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.LinkedHashMap;
import java.util.Map;

import j2act.WebPath;

/**
 * The PermissionDescriptor dictionary: set the members you need, e.g. new PermissionDescriptor().name(...) (ADR 0022).
 */
public final class PermissionDescriptor implements WebPath.Value {

  private final Map<String, Object> fields = new LinkedHashMap<>();

  /**
   * Required. The name member.
   */
  public PermissionDescriptor name(String name) {
    fields.put("name", name);
    return this;
  }

  @Override public Object toJson() {
    return fields;
  }
}
