// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.concurrent.CompletionStage;

import j2act.WebPath;

/**
 * The browser's Permissions, run remotely through window() (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/Permissions">MDN: Permissions</a>
 */
public final class Permissions {

  private final WebPath path;

  /** Made by window() and the getters of other facades. */
  public Permissions(WebPath path) {
    this.path = path;
  }

  /**
   * Permissions.query(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Permissions/query">MDN: Permissions.query</a>
   */
  public CompletionStage<PermissionStatus> query(PermissionDescriptor permissionDesc) {
    return path.invoke("query", PermissionStatus.SHAPE, PermissionStatus::from, permissionDesc);
  }
}
