// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.LinkedHashMap;
import java.util.Map;

import j2act.WebPath;

/**
 * The ScrollIntoViewOptions dictionary: set the members you need, e.g. new ScrollIntoViewOptions().behavior(...) (ADR 0022).
 */
public final class ScrollIntoViewOptions implements WebPath.Value {

  private final Map<String, Object> fields = new LinkedHashMap<>();

  /**
   * The behavior member. A ScrollBehavior: "auto" "instant" "smooth".
   */
  public ScrollIntoViewOptions behavior(String behavior) {
    fields.put("behavior", behavior);
    return this;
  }

  /**
   * The block member. A ScrollLogicalPosition: "start" "center" "end" "nearest".
   */
  public ScrollIntoViewOptions block(String block) {
    fields.put("block", block);
    return this;
  }

  /**
   * The inline member. A ScrollLogicalPosition: "start" "center" "end" "nearest".
   */
  public ScrollIntoViewOptions inline(String inline) {
    fields.put("inline", inline);
    return this;
  }

  /**
   * The container member. A ScrollIntoViewContainer: "all" "nearest".
   */
  public ScrollIntoViewOptions container(String container) {
    fields.put("container", container);
    return this;
  }

  @Override public Object toJson() {
    return fields;
  }
}
