// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.concurrent.CompletionStage;

import j2act.WebPath;

/**
 * The browser's Storage, run remotely through window() (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/Storage">MDN: Storage</a>
 */
public final class Storage {

  private final WebPath path;

  /** Made by window() and the getters of other facades. */
  public Storage(WebPath path) {
    this.path = path;
  }

  /**
   * Storage.length in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Storage/length">MDN: Storage.length</a>
   */
  public CompletionStage<Long> length() {
    return path.read("length", null, WebPath::longValue);
  }

  /**
   * Storage.key(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Storage/key">MDN: Storage.key</a>
   */
  public CompletionStage<String> key(long index) {
    return path.invoke("key", null, WebPath::string, index);
  }

  /**
   * Storage.getItem(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Storage/getItem">MDN: Storage.getItem</a>
   */
  public CompletionStage<String> getItem(String key) {
    return path.invoke("getItem", null, WebPath::string, key);
  }

  /**
   * Storage.setItem(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Storage/setItem">MDN: Storage.setItem</a>
   */
  public CompletionStage<Void> setItem(String key, String value) {
    return path.invoke("setItem", null, WebPath::none, key, value);
  }

  /**
   * Storage.removeItem(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Storage/removeItem">MDN: Storage.removeItem</a>
   */
  public CompletionStage<Void> removeItem(String key) {
    return path.invoke("removeItem", null, WebPath::none, key);
  }

  /**
   * Storage.clear(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Storage/clear">MDN: Storage.clear</a>
   */
  public CompletionStage<Void> clear() {
    return path.invoke("clear", null, WebPath::none);
  }
}
