// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @webref/idl (MIT), @mdn/browser-compat-data (CC0). See data/window-api.json.
package j2act.web;

import java.util.concurrent.CompletionStage;

import j2act.WebPath;

/**
 * The browser's Window, run remotely through window() (ADR 0022).
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/API/Window">MDN: Window</a>
 */
public final class Window {

  private final WebPath path;

  /** Made by window() and the getters of other facades. */
  public Window(WebPath path) {
    this.path = path;
  }

  /**
   * Window.document in the browser. A path step only: nothing runs until a call on it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/document">MDN: Window.document</a>
   */
  public Document document() {
    return new Document(path.get("document"));
  }

  /**
   * Window.location in the browser. A path step only: nothing runs until a call on it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/location">MDN: Window.location</a>
   */
  public Location location() {
    return new Location(path.get("location"));
  }

  /**
   * Window.history in the browser. A path step only: nothing runs until a call on it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/history">MDN: Window.history</a>
   */
  public History history() {
    return new History(path.get("history"));
  }

  /**
   * Window.navigator in the browser. A path step only: nothing runs until a call on it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/navigator">MDN: Window.navigator</a>
   */
  public Navigator navigator() {
    return new Navigator(path.get("navigator"));
  }

  /**
   * Window.alert(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/alert">MDN: Window.alert</a>
   */
  public CompletionStage<Void> alert() {
    return path.invoke("alert", null, WebPath::none);
  }

  /**
   * Window.alert(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/alert">MDN: Window.alert</a>
   */
  public CompletionStage<Void> alert(String message) {
    return path.invoke("alert", null, WebPath::none, message);
  }

  /**
   * Window.confirm(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/confirm">MDN: Window.confirm</a>
   */
  public CompletionStage<Boolean> confirm() {
    return path.invoke("confirm", null, WebPath::bool);
  }

  /**
   * Window.confirm(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/confirm">MDN: Window.confirm</a>
   */
  public CompletionStage<Boolean> confirm(String message) {
    return path.invoke("confirm", null, WebPath::bool, message);
  }

  /**
   * Window.prompt(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/prompt">MDN: Window.prompt</a>
   */
  public CompletionStage<String> prompt() {
    return path.invoke("prompt", null, WebPath::string);
  }

  /**
   * Window.prompt(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/prompt">MDN: Window.prompt</a>
   */
  public CompletionStage<String> prompt(String message) {
    return path.invoke("prompt", null, WebPath::string, message);
  }

  /**
   * Window.prompt(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/prompt">MDN: Window.prompt</a>
   */
  public CompletionStage<String> prompt(String message, String default_) {
    return path.invoke("prompt", null, WebPath::string, message, default_);
  }

  /**
   * Window.print(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/print">MDN: Window.print</a>
   */
  public CompletionStage<Void> print() {
    return path.invoke("print", null, WebPath::none);
  }

  /**
   * Window.innerWidth in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/innerWidth">MDN: Window.innerWidth</a>
   */
  public CompletionStage<Integer> innerWidth() {
    return path.read("innerWidth", null, WebPath::integer);
  }

  /**
   * Window.innerHeight in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/innerHeight">MDN: Window.innerHeight</a>
   */
  public CompletionStage<Integer> innerHeight() {
    return path.read("innerHeight", null, WebPath::integer);
  }

  /**
   * Window.scrollX in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/scrollX">MDN: Window.scrollX</a>
   */
  public CompletionStage<Double> scrollX() {
    return path.read("scrollX", null, WebPath::number);
  }

  /**
   * Window.scrollY in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/scrollY">MDN: Window.scrollY</a>
   */
  public CompletionStage<Double> scrollY() {
    return path.read("scrollY", null, WebPath::number);
  }

  /**
   * Window.scrollTo(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/scrollTo">MDN: Window.scrollTo</a>
   */
  public CompletionStage<Void> scrollTo() {
    return path.invoke("scrollTo", null, WebPath::none);
  }

  /**
   * Window.scrollTo(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/scrollTo">MDN: Window.scrollTo</a>
   */
  public CompletionStage<Void> scrollTo(ScrollToOptions options) {
    return path.invoke("scrollTo", null, WebPath::none, options);
  }

  /**
   * Window.scrollTo(...) in the browser.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/scrollTo">MDN: Window.scrollTo</a>
   */
  public CompletionStage<Void> scrollTo(double x, double y) {
    return path.invoke("scrollTo", null, WebPath::none, x, y);
  }

  /**
   * Window.origin in the browser.
   */
  public CompletionStage<String> origin() {
    return path.read("origin", null, WebPath::string);
  }

  /**
   * Window.isSecureContext in the browser.
   */
  public CompletionStage<Boolean> isSecureContext() {
    return path.read("isSecureContext", null, WebPath::bool);
  }

  /**
   * Window.sessionStorage in the browser. A path step only: nothing runs until a call on it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/sessionStorage">MDN: Window.sessionStorage</a>
   */
  public Storage sessionStorage() {
    return new Storage(path.get("sessionStorage"));
  }

  /**
   * Window.localStorage in the browser. A path step only: nothing runs until a call on it.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/API/Window/localStorage">MDN: Window.localStorage</a>
   */
  public Storage localStorage() {
    return new Storage(path.get("localStorage"));
  }

  /** The Notification interface object: its static members and constructor. */
  public Notification Notification() {
    return new Notification(path.get("Notification"));
  }
}
