// Generated by j2act from clients.Webcam. Do not edit.

/**
 * Streams a camera into its video element.
 *
 * Implement it in the sibling .client.ts or .client.js:
 * export const camera = { ... } satisfies Camera;
 */
export interface Camera {
  /**
   * Starts the stream from this device.
   *
   * Returns its cleanup, like useEffect.
   */
  mount(el: HTMLVideoElement, props: CameraProps): (() => void) | void;
  /** Runs when props change; without it the client unmounts and mounts again. */
  update?(el: HTMLVideoElement, props: CameraProps, previous: CameraProps): void;
  /** A JPEG data URL of the current frame. */
  snapshot(el: HTMLVideoElement): string | Promise<string>;
  snapshot(el: HTMLVideoElement, into: UploadTarget): void | Promise<void>;
  shot(el: HTMLVideoElement, label: string | null, size: Size | null): Shot<{ [key: string]: number[] }> | Promise<Shot<{ [key: string]: number[] }>>;
  pause(el: HTMLVideoElement, onPaused: () => void, overlay: HTMLElement, thumbnail: string, sizes: Size[][]): void | Promise<void>;
}

export interface CameraProps {
  device: string;
  facing: Facing;
  onReady: (value: Size) => void;
  onError: (first: string, second: number) => void;
}

/**
 * Implement it in the sibling .client.ts or .client.js:
 * export const beeper = { ... } satisfies Beeper;
 */
export interface Beeper {
  mount?(el: HTMLElement): (() => void) | void;
  beep(el: HTMLElement, millis: number): void | Promise<void>;
}

/** The camera's picture size. */
export interface Size {
  width: number;
  height: number;
}

export interface Shot<T> {
  index: number;
  meta: T;
  takenAt: string;
  blurry: boolean;
  link: string;
  note: string | null;
}

export type Facing = "USER" | "ENVIRONMENT";

/** The Upload passed to an action; send() uses its chunks and server-side limits (ADR 0006). */
export interface UploadTarget {
  send(blob: Blob, name?: string): Promise<void>;
}
