// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;address&gt;</code> element.
 *
 * <p>The address element represents the contact information for its nearest article or body
 * element ancestor. If that is the body element, then the contact information applies to the
 * document as a whole.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/address">MDN:
 * &lt;address&gt;</a>
 */
public final class AddressTag extends ContainerTag<AddressTag> {

  public AddressTag() {
    super("address");
  }
}
