// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;area&gt;</code> element.
 *
 * <p>The area element represents either a hyperlink with some text and a corresponding area on an
 * image map, or a dead area on an image map.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN:
 * &lt;area&gt;</a>
 */
public final class AreaTag extends EmptyTag<AreaTag> {

  public AreaTag() {
    super("area");
  }

  /**
   * Sets the <code>alt</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN: alt</a>
   */
  public AreaTag withAlt(String value) {
    return attr("alt", value);
  }

  /**
   * Applies {@link #withAlt(String)} only when {@code condition} is true.
   */
  public AreaTag withCondAlt(boolean condition, String value) {
    return condition ? attr("alt", value) : self();
  }

  /**
   * Sets the <code>coords</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN:
   * coords</a>
   */
  public AreaTag withCoords(String value) {
    return attr("coords", value);
  }

  /**
   * Applies {@link #withCoords(String)} only when {@code condition} is true.
   */
  public AreaTag withCondCoords(boolean condition, String value) {
    return condition ? attr("coords", value) : self();
  }

  /**
   * Sets the <code>shape</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN:
   * shape</a>
   */
  public AreaTag withShape(String value) {
    return attr("shape", value);
  }

  /**
   * Applies {@link #withShape(String)} only when {@code condition} is true.
   */
  public AreaTag withCondShape(boolean condition, String value) {
    return condition ? attr("shape", value) : self();
  }

  /**
   * Sets the <code>href</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN: href</a>
   */
  public AreaTag withHref(String value) {
    return attr("href", value);
  }

  /**
   * Applies {@link #withHref(String)} only when {@code condition} is true.
   */
  public AreaTag withCondHref(boolean condition, String value) {
    return condition ? attr("href", value) : self();
  }

  /**
   * Sets the <code>target</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN:
   * target</a>
   */
  public AreaTag withTarget(String value) {
    return attr("target", value);
  }

  /**
   * Applies {@link #withTarget(String)} only when {@code condition} is true.
   */
  public AreaTag withCondTarget(boolean condition, String value) {
    return condition ? attr("target", value) : self();
  }

  /**
   * Sets the <code>download</code> attribute.
   *
   * <p>Baseline: widely available since 2019-09-27.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN:
   * download</a>
   */
  public AreaTag withDownload(String value) {
    return attr("download", value);
  }

  /**
   * Applies {@link #withDownload(String)} only when {@code condition} is true.
   */
  public AreaTag withCondDownload(boolean condition, String value) {
    return condition ? attr("download", value) : self();
  }

  /**
   * Sets <code>download</code> with no value. See {@link #withDownload(String)}.
   */
  public AreaTag isDownload() {
    return attr("download");
  }

  /**
   * Sets the <code>ping</code> attribute.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN: ping</a>
   */
  public AreaTag withPing(String value) {
    return attr("ping", value);
  }

  /**
   * Applies {@link #withPing(String)} only when {@code condition} is true.
   */
  public AreaTag withCondPing(boolean condition, String value) {
    return condition ? attr("ping", value) : self();
  }

  /**
   * Sets the <code>rel</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/rel">MDN: rel</a>
   */
  public AreaTag withRel(String value) {
    return attr("rel", value);
  }

  /**
   * Applies {@link #withRel(String)} only when {@code condition} is true.
   */
  public AreaTag withCondRel(boolean condition, String value) {
    return condition ? attr("rel", value) : self();
  }

  /**
   * Sets the <code>hreflang</code> attribute.
   *
   * <p>Experimental.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN:
   * hreflang</a>
   */
  public AreaTag withHreflang(String value) {
    return attr("hreflang", value);
  }

  /**
   * Applies {@link #withHreflang(String)} only when {@code condition} is true.
   */
  public AreaTag withCondHreflang(boolean condition, String value) {
    return condition ? attr("hreflang", value) : self();
  }

  /**
   * Sets the <code>type</code> attribute.
   *
   * <p>Experimental.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/area">MDN: type</a>
   */
  public AreaTag withType(String value) {
    return attr("type", value);
  }

  /**
   * Applies {@link #withType(String)} only when {@code condition} is true.
   */
  public AreaTag withCondType(boolean condition, String value) {
    return condition ? attr("type", value) : self();
  }
}
