// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;article&gt;</code> element.
 *
 * <p>The article element represents a complete, or self-contained, composition in a document,
 * page, application, or site and that is, in principle, independently distributable or reusable,
 * e.g. in syndication. This could be a forum post, a magazine or newspaper article, a blog entry,
 * a user-submitted comment, an interactive widget or gadget, or any other independent item of
 * content. Each article should be identified, typically by including a heading (h1–h6 element) as
 * a child of the article element.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/article">MDN:
 * &lt;article&gt;</a>
 */
public final class ArticleTag extends ContainerTag<ArticleTag> {

  public ArticleTag() {
    super("article");
  }
}
