// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;aside&gt;</code> element.
 *
 * <p>The aside element represents a section of a page that consists of content that is
 * tangentially related to the content around the aside element, and which could be considered
 * separate from that content. Such sections are often represented as sidebars in printed
 * typography.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/aside">MDN:
 * &lt;aside&gt;</a>
 */
public final class AsideTag extends ContainerTag<AsideTag> {

  public AsideTag() {
    super("aside");
  }
}
