// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;a&gt;</code> element.
 *
 * <p>If the a element has an href attribute, then it represents a hyperlink (a hypertext anchor)
 * labeled by its contents.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/a">MDN:
 * &lt;a&gt;</a>
 */
public final class ATag extends ContainerTag<ATag> {

  public ATag() {
    super("a");
  }

  /**
   * Sets the <code>href</code> attribute.
   *
   * <p>Contains a URL or a URL fragment that the hyperlink points to. A URL fragment is a name
   * preceded by a hash mark (<code>#</code>), which specifies an internal target location (an <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-id"><code>id</code></a>
   * of an HTML element) within the current document. URLs are not restricted to Web (HTTP)-based
   * documents, but can use any protocol supported by the browser. For example, <a
   * href="https://en.wikipedia.org/wiki/File_URI_scheme"><code>file:</code></a>, <code>ftp:</code>,
   * and <code>mailto:</code> work in most browsers.
   *
   * <p>**Note:** You can use <code>href="#top"</code> or the empty fragment <code>href="#"</code> to
   * link to the top of the current page. <a
   * href="https://www.w3.org/TR/html5/single-page.html#scroll-to-fragid">This behavior is specified
   * by HTML5</a>.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/a">MDN: href</a>
   */
  public ATag withHref(String value) {
    return attr("href", value);
  }

  /**
   * Applies {@link #withHref(String)} only when {@code condition} is true.
   */
  public ATag withCondHref(boolean condition, String value) {
    return condition ? attr("href", value) : self();
  }

  /**
   * Sets the <code>target</code> attribute.
   *
   * <p>Specifies where to display the linked URL. It is a name of, or keyword for, a _browsing
   * context_: a tab, window, or <code>&lt;iframe&gt;</code>. The following keywords have special
   * meanings:
   *
   * <p>* <code>_self</code>: Load the URL into the same browsing context as the current one. This is
   * the default behavior. * <code>_blank</code>: Load the URL into a new browsing context. This is
   * usually a tab, but users can configure browsers to use new windows instead. *
   * <code>_parent</code>: Load the URL into the parent browsing context of the current one. If there
   * is no parent, this behaves the same way as <code>_self</code>. * <code>_top</code>: Load the URL
   * into the top-level browsing context (that is, the "highest" browsing context that is an ancestor
   * of the current one, and has no parent). If there is no parent, this behaves the same way as
   * <code>_self</code>.
   *
   * <p>**Note:** When using <code>target</code>, consider adding <code>rel="noreferrer"</code> to
   * avoid exploitation of the <code>window.opener</code> API.
   *
   * <p>**Note:** Linking to another page using <code>target="_blank"</code> will run the new page on
   * the same process as your page. If the new page is executing expensive JS, your page's
   * performance may suffer. To avoid this use <code>rel="noopener"</code>.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/a">MDN: target</a>
   */
  public ATag withTarget(String value) {
    return attr("target", value);
  }

  /**
   * Applies {@link #withTarget(String)} only when {@code condition} is true.
   */
  public ATag withCondTarget(boolean condition, String value) {
    return condition ? attr("target", value) : self();
  }

  /**
   * Sets the <code>download</code> attribute.
   *
   * <p>This attribute instructs browsers to download a URL instead of navigating to it, so the user
   * will be prompted to save it as a local file. If the attribute has a value, it is used as the
   * pre-filled file name in the Save prompt (the user can still change the file name if they want).
   * There are no restrictions on allowed values, though <code>/</code> and <code>&#92;</code> are
   * converted to underscores. Most file systems limit some punctuation in file names, and browsers
   * will adjust the suggested name accordingly.
   *
   * <p>**Notes:**
   *
   * <p>* This attribute only works for <a
   * href="https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy">same-origin
   * URLs</a>. * Although HTTP(s) URLs need to be in the same-origin, <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/URL.createObjectURL"><code>blob:</code>
   * URLs</a> and <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs"><code>data:</code>
   * URLs</a> are allowed so that content generated by JavaScript, such as pictures created in an
   * image-editor Web app, can be downloaded. * If the HTTP header <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition"><code>Content-Disposition:</code></a>
   * gives a different filename than this attribute, the HTTP header takes priority over this
   * attribute. * If <code>Content-Disposition:</code> is set to <code>inline</code>, Firefox
   * prioritizes <code>Content-Disposition</code>, like the filename case, while Chrome prioritizes
   * the <code>download</code> attribute.
   *
   * <p>Baseline: widely available since 2022-03-19.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/a">MDN:
   * download</a>
   */
  public ATag withDownload(String value) {
    return attr("download", value);
  }

  /**
   * Applies {@link #withDownload(String)} only when {@code condition} is true.
   */
  public ATag withCondDownload(boolean condition, String value) {
    return condition ? attr("download", value) : self();
  }

  /**
   * Sets <code>download</code> with no value. See {@link #withDownload(String)}.
   */
  public ATag isDownload() {
    return attr("download");
  }

  /**
   * Sets the <code>ping</code> attribute.
   *
   * <p>Contains a space-separated list of URLs to which, when the hyperlink is followed,
   * [<code>POST</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST "The HTTP
   * POST method sends data to the server. The type of the body of the request is indicated by the
   * Content-Type header.") requests with the body <code>PING</code> will be sent by the browser (in
   * the background). Typically used for tracking.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/a">MDN: ping</a>
   */
  public ATag withPing(String value) {
    return attr("ping", value);
  }

  /**
   * Applies {@link #withPing(String)} only when {@code condition} is true.
   */
  public ATag withCondPing(boolean condition, String value) {
    return condition ? attr("ping", value) : self();
  }

  /**
   * Sets the <code>rel</code> attribute.
   *
   * <p>Specifies the relationship of the target object to the link object. The value is a
   * space-separated list of <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types">link types</a>.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/rel">MDN: rel</a>
   */
  public ATag withRel(String value) {
    return attr("rel", value);
  }

  /**
   * Applies {@link #withRel(String)} only when {@code condition} is true.
   */
  public ATag withCondRel(boolean condition, String value) {
    return condition ? attr("rel", value) : self();
  }

  /**
   * Sets the <code>hreflang</code> attribute.
   *
   * <p>This attribute indicates the human language of the linked resource. It is purely advisory,
   * with no built-in functionality. Allowed values are determined by
   * [BCP47](https://www.ietf.org/rfc/bcp/bcp47.txt "Tags for Identifying Languages").
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/a">MDN:
   * hreflang</a>
   */
  public ATag withHreflang(String value) {
    return attr("hreflang", value);
  }

  /**
   * Applies {@link #withHreflang(String)} only when {@code condition} is true.
   */
  public ATag withCondHreflang(boolean condition, String value) {
    return condition ? attr("hreflang", value) : self();
  }

  /**
   * Sets the <code>type</code> attribute.
   *
   * <p>Specifies the media type in the form of a [MIME
   * type](https://developer.mozilla.org/en-US/docs/Glossary/MIME_type "MIME type: A MIME type (now
   * properly called "media type", but also sometimes "content type") is a string sent along with a
   * file indicating the type of the file (describing the content format, for example, a sound file
   * might be labeled audio/ogg, or an image file image/png).") for the linked URL. It is purely
   * advisory, with no built-in functionality.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/a">MDN: type</a>
   */
  public ATag withType(String value) {
    return attr("type", value);
  }

  /**
   * Applies {@link #withType(String)} only when {@code condition} is true.
   */
  public ATag withCondType(boolean condition, String value) {
    return condition ? attr("type", value) : self();
  }

  /**
   * Sets the <code>referrerpolicy</code> attribute.
   *
   * <p>Indicates which <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer">referrer</a> to send
   * when fetching the URL:
   *
   * <p>* <code>'no-referrer'</code> means the <code>Referer:</code> header will not be sent. *
   * <code>'no-referrer-when-downgrade'</code> means no <code>Referer:</code> header will be sent
   * when navigating to an origin without HTTPS. This is the default behavior. *
   * <code>'origin'</code> means the referrer will be the <a
   * href="https://developer.mozilla.org/en-US/docs/Glossary/Origin">origin</a> of the page, not
   * including information after the domain. * <code>'origin-when-cross-origin'</code> meaning that
   * navigations to other origins will be limited to the scheme, the host and the port, while
   * navigations on the same origin will include the referrer's path. *
   * <code>'strict-origin-when-cross-origin'</code> * <code>'unsafe-url'</code> means the referrer
   * will include the origin and path, but not the fragment, password, or username. This is unsafe
   * because it can leak data from secure URLs to insecure ones.
   *
   * <p>Baseline: widely available since 2023-03-16.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/a">MDN:
   * referrerpolicy</a>
   */
  public ATag withReferrerpolicy(String value) {
    return attr("referrerpolicy", value);
  }

  /**
   * Applies {@link #withReferrerpolicy(String)} only when {@code condition} is true.
   */
  public ATag withCondReferrerpolicy(boolean condition, String value) {
    return condition ? attr("referrerpolicy", value) : self();
  }
}
