// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;base&gt;</code> element.
 *
 * <p>The base element allows authors to specify the document base URL for the purposes of
 * resolving relative URLs, and the name of the default browsing context for the purposes of
 * following hyperlinks. The element does not represent any content beyond this information.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/base">MDN:
 * &lt;base&gt;</a>
 */
public final class BaseTag extends EmptyTag<BaseTag> {

  public BaseTag() {
    super("base");
  }

  /**
   * Sets the <code>href</code> attribute.
   *
   * <p>The base URL to be used throughout the document for relative URL addresses. If this attribute
   * is specified, this element must come before any other elements with attributes whose values are
   * URLs. Absolute and relative URLs are allowed.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/base">MDN: href</a>
   */
  public BaseTag withHref(String value) {
    return attr("href", value);
  }

  /**
   * Applies {@link #withHref(String)} only when {@code condition} is true.
   */
  public BaseTag withCondHref(boolean condition, String value) {
    return condition ? attr("href", value) : self();
  }

  /**
   * Sets the <code>target</code> attribute.
   *
   * <p>A name or keyword indicating the default location to display the result when hyperlinks or
   * forms cause navigation, for elements that do not have an explicit target reference. It is a name
   * of, or keyword for, a _browsing context_ (for example: tab, window, or inline frame). The
   * following keywords have special meanings:
   *
   * <p>* <code>_self</code>: Load the result into the same browsing context as the current one. This
   * value is the default if the attribute is not specified. * <code>_blank</code>: Load the result
   * into a new unnamed browsing context. * <code>_parent</code>: Load the result into the parent
   * browsing context of the current one. If there is no parent, this option behaves the same way as
   * <code>_self</code>. * <code>_top</code>: Load the result into the top-level browsing context
   * (that is, the browsing context that is an ancestor of the current one, and has no parent). If
   * there is no parent, this option behaves the same way as <code>_self</code>.
   *
   * <p>If this attribute is specified, this element must come before any other elements with
   * attributes whose values are URLs.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/base">MDN:
   * target</a>
   */
  public BaseTag withTarget(String value) {
    return attr("target", value);
  }

  /**
   * Applies {@link #withTarget(String)} only when {@code condition} is true.
   */
  public BaseTag withCondTarget(boolean condition, String value) {
    return condition ? attr("target", value) : self();
  }
}
