// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;bdi&gt;</code> element.
 *
 * <p>The bdi element represents a span of text that is to be isolated from its surroundings for
 * the purposes of bidirectional text formatting. [BIDI]
 *
 * <p>Baseline: widely available since 2022-07-15.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/bdi">MDN:
 * &lt;bdi&gt;</a>
 */
public final class BdiTag extends ContainerTag<BdiTag> {

  public BdiTag() {
    super("bdi");
  }
}
