// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;blockquote&gt;</code> element.
 *
 * <p>The blockquote element represents content that is quoted from another source, optionally with
 * a citation which must be within a footer or cite element, and optionally with in-line changes
 * such as annotations and abbreviations.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/blockquote">MDN:
 * &lt;blockquote&gt;</a>
 */
public final class BlockquoteTag extends ContainerTag<BlockquoteTag> {

  public BlockquoteTag() {
    super("blockquote");
  }

  /**
   * Sets the <code>cite</code> attribute.
   *
   * <p>A URL that designates a source document or message for the information quoted. This attribute
   * is intended to point to information explaining the context or the reference for the quote.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/blockquote">MDN:
   * cite</a>
   */
  public BlockquoteTag withCite(String value) {
    return attr("cite", value);
  }

  /**
   * Applies {@link #withCite(String)} only when {@code condition} is true.
   */
  public BlockquoteTag withCondCite(boolean condition, String value) {
    return condition ? attr("cite", value) : self();
  }
}
