// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;body&gt;</code> element.
 *
 * <p>The body element represents the content of the document.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN:
 * &lt;body&gt;</a>
 */
public final class BodyTag extends ContainerTag<BodyTag> {

  public BodyTag() {
    super("body");
  }

  /**
   * Sets the <code>alink</code> attribute.
   *
   * <p>Color of text for hyperlinks when selected. _This method is non-conforming, use CSS
   * [<code>color</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/color "The color CSS
   * property sets the foreground color value of an element's text and text decorations, and sets the
   * currentcolor value.") property in conjunction with the
   * [<code>:active</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/:active "The :active CSS
   * pseudo-class represents an element (such as a button) that is being activated by the user.")
   * pseudo-class instead._
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN:
   * alink</a>
   * @deprecated The <code>alink</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public BodyTag withAlink(String value) {
    return attr("alink", value);
  }

  /**
   * Applies {@link #withAlink(String)} only when {@code condition} is true.
   */
  @Deprecated
  public BodyTag withCondAlink(boolean condition, String value) {
    return condition ? attr("alink", value) : self();
  }

  /**
   * Sets the <code>background</code> attribute.
   *
   * <p>URI of a image to use as a background. _This method is non-conforming, use CSS
   * [<code>background</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/background "The
   * background shorthand CSS property sets all background style properties at once, such as color,
   * image, origin and size, or repeat method.") property on the element instead._
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN:
   * background</a>
   * @deprecated The <code>background</code> attribute is marked deprecated in MDN
   * browser-compat-data; avoid in new markup.
   */
  @Deprecated
  public BodyTag withBackground(String value) {
    return attr("background", value);
  }

  /**
   * Applies {@link #withBackground(String)} only when {@code condition} is true.
   */
  @Deprecated
  public BodyTag withCondBackground(boolean condition, String value) {
    return condition ? attr("background", value) : self();
  }

  /**
   * Sets the <code>bgcolor</code> attribute.
   *
   * <p>Background color for the document. _This method is non-conforming, use CSS
   * [<code>background-color</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color
   * "The background-color CSS property sets the background color of an element.") property on the
   * element instead._
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN:
   * bgcolor</a>
   * @deprecated The <code>bgcolor</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public BodyTag withBgcolor(String value) {
    return attr("bgcolor", value);
  }

  /**
   * Applies {@link #withBgcolor(String)} only when {@code condition} is true.
   */
  @Deprecated
  public BodyTag withCondBgcolor(boolean condition, String value) {
    return condition ? attr("bgcolor", value) : self();
  }

  /**
   * Sets the <code>bottommargin</code> attribute.
   *
   * <p>The margin of the bottom of the body. _This method is non-conforming, use CSS
   * [<code>margin-bottom</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-bottom "The
   * margin-bottom CSS property sets the margin area on the bottom of an element. A positive value
   * places it farther from its neighbors, while a negative value places it closer.") property on the
   * element instead._
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN:
   * bottommargin</a>
   * @deprecated The <code>bottommargin</code> attribute is marked deprecated in MDN
   * browser-compat-data; avoid in new markup.
   */
  @Deprecated
  public BodyTag withBottommargin(String value) {
    return attr("bottommargin", value);
  }

  /**
   * Applies {@link #withBottommargin(String)} only when {@code condition} is true.
   */
  @Deprecated
  public BodyTag withCondBottommargin(boolean condition, String value) {
    return condition ? attr("bottommargin", value) : self();
  }

  /**
   * Sets the <code>leftmargin</code> attribute.
   *
   * <p>The margin of the left of the body. _This method is non-conforming, use CSS
   * [<code>margin-left</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-left "The
   * margin-left CSS property sets the margin area on the left side of an element. A positive value
   * places it farther from its neighbors, while a negative value places it closer.") property on the
   * element instead._
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN:
   * leftmargin</a>
   * @deprecated The <code>leftmargin</code> attribute is marked deprecated in MDN
   * browser-compat-data; avoid in new markup.
   */
  @Deprecated
  public BodyTag withLeftmargin(String value) {
    return attr("leftmargin", value);
  }

  /**
   * Applies {@link #withLeftmargin(String)} only when {@code condition} is true.
   */
  @Deprecated
  public BodyTag withCondLeftmargin(boolean condition, String value) {
    return condition ? attr("leftmargin", value) : self();
  }

  /**
   * Sets the <code>link</code> attribute.
   *
   * <p>Color of text for unvisited hypertext links. _This method is non-conforming, use CSS
   * [<code>color</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/color "The color CSS
   * property sets the foreground color value of an element's text and text decorations, and sets the
   * currentcolor value.") property in conjunction with the
   * [<code>:link</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/:link "The :link CSS
   * pseudo-class represents an element that has not yet been visited. It matches every unvisited
   * &lt;a&gt;, &lt;area&gt;, or &lt;link&gt; element that has an href attribute.") pseudo-class
   * instead._
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN: link</a>
   * @deprecated The <code>link</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public BodyTag withLink(String value) {
    return attr("link", value);
  }

  /**
   * Applies {@link #withLink(String)} only when {@code condition} is true.
   */
  @Deprecated
  public BodyTag withCondLink(boolean condition, String value) {
    return condition ? attr("link", value) : self();
  }

  /**
   * Sets the <code>rightmargin</code> attribute.
   *
   * <p>The margin of the right of the body. _This method is non-conforming, use CSS
   * [<code>margin-right</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-right "The
   * margin-right CSS property sets the margin area on the right side of an element. A positive value
   * places it farther from its neighbors, while a negative value places it closer.") property on the
   * element instead._
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN:
   * rightmargin</a>
   * @deprecated The <code>rightmargin</code> attribute is marked deprecated in MDN
   * browser-compat-data; avoid in new markup.
   */
  @Deprecated
  public BodyTag withRightmargin(String value) {
    return attr("rightmargin", value);
  }

  /**
   * Applies {@link #withRightmargin(String)} only when {@code condition} is true.
   */
  @Deprecated
  public BodyTag withCondRightmargin(boolean condition, String value) {
    return condition ? attr("rightmargin", value) : self();
  }

  /**
   * Sets the <code>topmargin</code> attribute.
   *
   * <p>The margin of the top of the body. _This method is non-conforming, use CSS
   * [<code>margin-top</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-top "The
   * margin-top CSS property sets the margin area on the top of an element. A positive value places
   * it farther from its neighbors, while a negative value places it closer.") property on the
   * element instead._
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN:
   * topmargin</a>
   * @deprecated The <code>topmargin</code> attribute is marked deprecated in MDN
   * browser-compat-data; avoid in new markup.
   */
  @Deprecated
  public BodyTag withTopmargin(String value) {
    return attr("topmargin", value);
  }

  /**
   * Applies {@link #withTopmargin(String)} only when {@code condition} is true.
   */
  @Deprecated
  public BodyTag withCondTopmargin(boolean condition, String value) {
    return condition ? attr("topmargin", value) : self();
  }

  /**
   * Sets the <code>vlink</code> attribute.
   *
   * <p>Color of text for visited hypertext links. _This method is non-conforming, use CSS
   * [<code>color</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/color "The color CSS
   * property sets the foreground color value of an element's text and text decorations, and sets the
   * currentcolor value.") property in conjunction with the
   * [<code>:visited</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited "The :visited
   * CSS pseudo-class represents links that the user has already visited. For privacy reasons, the
   * styles that can be modified using this selector are very limited.") pseudo-class instead._
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/body">MDN:
   * vlink</a>
   * @deprecated The <code>vlink</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public BodyTag withVlink(String value) {
    return attr("vlink", value);
  }

  /**
   * Applies {@link #withVlink(String)} only when {@code condition} is true.
   */
  @Deprecated
  public BodyTag withCondVlink(boolean condition, String value) {
    return condition ? attr("vlink", value) : self();
  }
}
