// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;canvas&gt;</code> element.
 *
 * <p>The canvas element provides scripts with a resolution-dependent bitmap canvas, which can be
 * used for rendering graphs, game graphics, art, or other visual images on the fly.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/canvas">MDN:
 * &lt;canvas&gt;</a>
 */
public final class CanvasTag extends ContainerTag<CanvasTag> {

  public CanvasTag() {
    super("canvas");
  }

  /**
   * Sets the <code>width</code> attribute.
   *
   * <p>The width of the coordinate space in CSS pixels. Defaults to 300.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/canvas">MDN:
   * width</a>
   */
  public CanvasTag withWidth(String value) {
    return attr("width", value);
  }

  /**
   * Applies {@link #withWidth(String)} only when {@code condition} is true.
   */
  public CanvasTag withCondWidth(boolean condition, String value) {
    return condition ? attr("width", value) : self();
  }

  /**
   * Sets the <code>height</code> attribute.
   *
   * <p>The height of the coordinate space in CSS pixels. Defaults to 150.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/canvas">MDN:
   * height</a>
   */
  public CanvasTag withHeight(String value) {
    return attr("height", value);
  }

  /**
   * Applies {@link #withHeight(String)} only when {@code condition} is true.
   */
  public CanvasTag withCondHeight(boolean condition, String value) {
    return condition ? attr("height", value) : self();
  }

  /**
   * Sets the <code>moz-opaque</code> attribute.
   *
   * <p>Lets the canvas know whether or not translucency will be a factor. If the canvas knows
   * there's no translucency, painting performance can be optimized. This is only supported by
   * Mozilla-based browsers; use the standardized [<code>canvas.getContext('2d', { alpha: false
   * })</code>](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext "The
   * HTMLCanvasElement.getContext() method returns a drawing context on the canvas, or null if the
   * context identifier is not supported.") instead.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/canvas">MDN:
   * moz-opaque</a>
   * @deprecated The <code>moz-opaque</code> attribute is marked deprecated in MDN
   * browser-compat-data; avoid in new markup.
   */
  @Deprecated
  public CanvasTag withMozOpaque(String value) {
    return attr("moz-opaque", value);
  }

  /**
   * Applies {@link #withMozOpaque(String)} only when {@code condition} is true.
   */
  @Deprecated
  public CanvasTag withCondMozOpaque(boolean condition, String value) {
    return condition ? attr("moz-opaque", value) : self();
  }
}
