// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;caption&gt;</code> element.
 *
 * <p>The caption element represents the title of the table that is its parent, if it has a parent
 * and that is a table element.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/caption">MDN:
 * &lt;caption&gt;</a>
 */
public final class CaptionTag extends ContainerTag<CaptionTag> {

  public CaptionTag() {
    super("caption");
  }

  /**
   * Sets the <code>align</code> attribute.
   *
   * <p>This enumerated attribute indicates how the caption must be aligned with respect to the
   * table. It may have one of the following values:
   *
   * <p><code>left</code>
   *
   * <p>The caption is displayed to the left of the table.
   *
   * <p><code>top</code>
   *
   * <p>The caption is displayed above the table.
   *
   * <p><code>right</code>
   *
   * <p>The caption is displayed to the right of the table.
   *
   * <p><code>bottom</code>
   *
   * <p>The caption is displayed below the table.
   *
   * <p>**Usage note:** Do not use this attribute, as it has been deprecated. The
   * [<code>&lt;caption&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption
   * "The HTML Table Caption element (&lt;caption&gt;) specifies the caption (or title) of a table,
   * and if used is always the first child of a &lt;table&gt;.") element should be styled using the
   * <a href="https://developer.mozilla.org/en-US/docs/CSS">CSS</a> properties
   * [<code>caption-side</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side "The
   * caption-side CSS property puts the content of a table's &lt;caption&gt; on the specified side.
   * The values are relative to the writing-mode of the table.") and
   * [<code>text-align</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align "The
   * text-align CSS property sets the horizontal alignment of an inline or table-cell box. This means
   * it works like vertical-align but in the horizontal direction.").
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/caption">MDN:
   * align</a>
   * @deprecated The <code>align</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public CaptionTag withAlign(String value) {
    return attr("align", value);
  }

  /**
   * Applies {@link #withAlign(String)} only when {@code condition} is true.
   */
  @Deprecated
  public CaptionTag withCondAlign(boolean condition, String value) {
    return condition ? attr("align", value) : self();
  }
}
