// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;cite&gt;</code> element.
 *
 * <p>The cite element represents a reference to a creative work. It must include the title of the
 * work or the name of the author(person, people or organization) or an URL reference, or a
 * reference in abbreviated form as per the conventions used for the addition of citation metadata.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/cite">MDN:
 * &lt;cite&gt;</a>
 */
public final class CiteTag extends ContainerTag<CiteTag> {

  public CiteTag() {
    super("cite");
  }
}
