// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;datalist&gt;</code> element.
 *
 * <p>The datalist element represents a set of option elements that represent predefined options
 * for other controls. In the rendering, the datalist element represents nothing and it, along with
 * its children, should be hidden.
 *
 * <p>Limited availability: not yet supported in all major browsers.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/datalist">MDN:
 * &lt;datalist&gt;</a>
 */
public final class DatalistTag extends ContainerTag<DatalistTag> {

  public DatalistTag() {
    super("datalist");
  }
}
