// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;dd&gt;</code> element.
 *
 * <p>The dd element represents the description, definition, or value, part of a term-description
 * group in a description list (dl element).
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/dd">MDN:
 * &lt;dd&gt;</a>
 */
public final class DdTag extends ContainerTag<DdTag> {

  public DdTag() {
    super("dd");
  }

  /**
   * Sets the <code>nowrap</code> attribute.
   *
   * <p>If the value of this attribute is set to <code>yes</code>, the definition text will not wrap.
   * The default value is <code>no</code>.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/dd">MDN: nowrap</a>
   */
  public DdTag withNowrap(String value) {
    return attr("nowrap", value);
  }

  /**
   * Applies {@link #withNowrap(String)} only when {@code condition} is true.
   */
  public DdTag withCondNowrap(boolean condition, String value) {
    return condition ? attr("nowrap", value) : self();
  }
}
