// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;details&gt;</code> element.
 *
 * <p>The details element represents a disclosure widget from which the user can obtain additional
 * information or controls.
 *
 * <p>Baseline: widely available since 2022-07-15.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/details">MDN:
 * &lt;details&gt;</a>
 */
public final class DetailsTag extends ContainerTag<DetailsTag> {

  public DetailsTag() {
    super("details");
  }

  /**
   * Sets the <code>open</code> attribute.
   *
   * <p>This Boolean attribute indicates whether or not the details — that is, the contents of the
   * <code>&lt;details&gt;</code> element — are currently visible. The default, <code>false</code>,
   * means the details are not visible.
   *
   * <p>Baseline: widely available since 2022-07-15.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/details">MDN:
   * open</a>
   */
  public DetailsTag isOpen() {
    return attr("open");
  }

  /**
   * Applies {@link #isOpen()} when {@code condition} is true and removes the attribute otherwise, so
   * a form control stays controlled either way (ADR 0013).
   */
  public DetailsTag withCondOpen(boolean condition) {
    return condition ? attr("open") : attr("open", null);
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>This attribute enables multiple <code>&lt;details&gt;</code> elements to be connected, with
   * only one open at a time. This allows developers to easily create UI features such as accordions
   * without scripting.
   *
   * <p>The <code>name</code> attribute specifies a group name — give multiple
   * <code>&lt;details&gt;</code> elements the same <code>name</code> value to group them. Only one
   * of the grouped <code>&lt;details&gt;</code> elements can be open at a time — opening one will
   * cause another to close. If multiple grouped <code>&lt;details&gt;</code> elements are given the
   * <code>open</code> attribute, only the first one in the source order will be rendered open.
   *
   * <p>**Note**: <code>&lt;details&gt;</code> elements don't have to be adjacent to one another in
   * the source to be part of the same group.
   *
   * <p>Baseline: newly available since 2024-09-03.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/details">MDN:
   * name</a>
   */
  public DetailsTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public DetailsTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }
}
