// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;dfn&gt;</code> element.
 *
 * <p>The dfn element represents the defining instance of a term. The paragraph, description list
 * group, or section that is the nearest ancestor of the dfn element must also contain the
 * definition(s) for the term given by the dfn element.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/dfn">MDN:
 * &lt;dfn&gt;</a>
 */
public final class DfnTag extends ContainerTag<DfnTag> {

  public DfnTag() {
    super("dfn");
  }
}
