// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;dialog&gt;</code> element.
 *
 * <p>The dialog element represents a part of an application that a user interacts with to perform
 * a task, for example a dialog box, inspector, or window.
 *
 * <p>Baseline: widely available since 2024-09-14.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/dialog">MDN:
 * &lt;dialog&gt;</a>
 */
public final class DialogTag extends ContainerTag<DialogTag> {

  public DialogTag() {
    super("dialog");
  }

  /**
   * Sets the <code>open</code> attribute.
   *
   * <p>Indicates that the dialog is active and available for interaction. When the <code>open</code>
   * attribute is not set, the dialog shouldn't be shown to the user.
   *
   * <p>Baseline: widely available since 2024-09-14.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/dialog">MDN:
   * open</a>
   */
  public DialogTag withOpen(String value) {
    return attr("open", value);
  }

  /**
   * Applies {@link #withOpen(String)} only when {@code condition} is true.
   */
  public DialogTag withCondOpen(boolean condition, String value) {
    return condition ? attr("open", value) : self();
  }
}
