// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;div&gt;</code> element.
 *
 * <p>The div element has no special meaning at all. It represents its children. It can be used
 * with the class, lang, and title attributes to mark up semantics common to a group of consecutive
 * elements.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/div">MDN:
 * &lt;div&gt;</a>
 */
public final class DivTag extends ContainerTag<DivTag> {

  public DivTag() {
    super("div");
  }
}
