// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;dl&gt;</code> element.
 *
 * <p>The dl element represents an association list consisting of zero or more name-value groups (a
 * description list). A name-value group consists of one or more names (dt elements) followed by
 * one or more values (dd elements), ignoring any nodes other than dt and dd elements. Within a
 * single dl element, there should not be more than one dt element for each name.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/dl">MDN:
 * &lt;dl&gt;</a>
 */
public final class DlTag extends ContainerTag<DlTag> {

  public DlTag() {
    super("dl");
  }
}
