// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;fencedframe&gt;</code> element.
 *
 * <p>The fencedframe element represents a nested browsing context, embedding another HTML page
 * into the current one.
 *
 * <p>Limited availability: not yet supported in all major browsers.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/fencedframe">MDN:
 * &lt;fencedframe&gt;</a>
 * @deprecated The <code>&lt;fencedframe&gt;</code> element is marked deprecated in MDN
 * browser-compat-data; avoid in new markup.
 */
@Deprecated
public final class FencedframeTag extends ContainerTag<FencedframeTag> {

  public FencedframeTag() {
    super("fencedframe");
  }

  /**
   * Sets the <code>allow</code> attribute.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/fencedframe">MDN:
   * allow</a>
   * @deprecated The <code>allow</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public FencedframeTag withAllow(String value) {
    return attr("allow", value);
  }

  /**
   * Applies {@link #withAllow(String)} only when {@code condition} is true.
   */
  @Deprecated
  public FencedframeTag withCondAllow(boolean condition, String value) {
    return condition ? attr("allow", value) : self();
  }

  /**
   * Sets the <code>height</code> attribute.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/fencedframe">MDN:
   * height</a>
   * @deprecated The <code>height</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public FencedframeTag withHeight(String value) {
    return attr("height", value);
  }

  /**
   * Applies {@link #withHeight(String)} only when {@code condition} is true.
   */
  @Deprecated
  public FencedframeTag withCondHeight(boolean condition, String value) {
    return condition ? attr("height", value) : self();
  }

  /**
   * Sets the <code>width</code> attribute.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/fencedframe">MDN:
   * width</a>
   * @deprecated The <code>width</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public FencedframeTag withWidth(String value) {
    return attr("width", value);
  }

  /**
   * Applies {@link #withWidth(String)} only when {@code condition} is true.
   */
  @Deprecated
  public FencedframeTag withCondWidth(boolean condition, String value) {
    return condition ? attr("width", value) : self();
  }
}
