// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;fieldset&gt;</code> element.
 *
 * <p>The fieldset element represents a set of form controls optionally grouped under a common
 * name.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/fieldset">MDN:
 * &lt;fieldset&gt;</a>
 */
public final class FieldsetTag extends ContainerTag<FieldsetTag> {

  public FieldsetTag() {
    super("fieldset");
  }

  /**
   * Sets the <code>disabled</code> attribute.
   *
   * <p>If this Boolean attribute is set, all form controls that are descendants of the
   * <code>&lt;fieldset&gt;</code>, are disabled, meaning they are not editable and won't be
   * submitted along with the <code>&lt;form&gt;</code>. They won't receive any browsing events, like
   * mouse clicks or focus-related events. By default browsers display such controls grayed out. Note
   * that form elements inside the
   * [<code>&lt;legend&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend
   * "The HTML &lt;legend&gt; element represents a caption for the content of its parent
   * &lt;fieldset&gt;.") element won't be disabled.
   *
   * <p>Baseline: widely available since 2022-07-15.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/disabled">MDN:
   * disabled</a>
   */
  public FieldsetTag isDisabled() {
    return attr("disabled");
  }

  /**
   * Applies {@link #isDisabled()} when {@code condition} is true and removes the attribute
   * otherwise, so a form control stays controlled either way (ADR 0013).
   */
  public FieldsetTag withCondDisabled(boolean condition) {
    return condition ? attr("disabled") : attr("disabled", null);
  }

  /**
   * Sets the <code>form</code> attribute.
   *
   * <p>This attribute takes the value of the <code>id</code> attribute of a
   * [<code>&lt;form&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form "The
   * HTML &lt;form&gt; element represents a document section that contains interactive controls for
   * submitting information to a web server.") element you want the <code>&lt;fieldset&gt;</code> to
   * be part of, even if it is not inside the form.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/form">MDN:
   * form</a>
   */
  public FieldsetTag withForm(String value) {
    return attr("form", value);
  }

  /**
   * Applies {@link #withForm(String)} only when {@code condition} is true.
   */
  public FieldsetTag withCondForm(boolean condition, String value) {
    return condition ? attr("form", value) : self();
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>The name associated with the group.
   *
   * <p>**Note**: The caption for the fieldset is given by the first
   * [<code>&lt;legend&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend
   * "The HTML &lt;legend&gt; element represents a caption for the content of its parent
   * &lt;fieldset&gt;.") element nested inside it.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/fieldset">MDN:
   * name</a>
   */
  public FieldsetTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public FieldsetTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }
}
