// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;figure&gt;</code> element.
 *
 * <p>The figure element represents some flow content, optionally with a caption, that is
 * self-contained (like a complete sentence) and is typically referenced as a single unit from the
 * main flow of the document.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/figure">MDN:
 * &lt;figure&gt;</a>
 */
public final class FigureTag extends ContainerTag<FigureTag> {

  public FigureTag() {
    super("figure");
  }
}
