// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;footer&gt;</code> element.
 *
 * <p>The footer element represents a footer for its nearest ancestor sectioning content or
 * sectioning root element. A footer typically contains information about its section such as who
 * wrote it, links to related documents, copyright data, and the like.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/footer">MDN:
 * &lt;footer&gt;</a>
 */
public final class FooterTag extends ContainerTag<FooterTag> {

  public FooterTag() {
    super("footer");
  }
}
