// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;form&gt;</code> element.
 *
 * <p>The form element represents a collection of form-associated elements, some of which can
 * represent editable values that can be submitted to a server for processing.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form">MDN:
 * &lt;form&gt;</a>
 */
public final class FormTag extends ContainerTag<FormTag> {

  public FormTag() {
    super("form");
  }

  /**
   * Sets the <code>accept-charset</code> attribute.
   *
   * <p>A space- or comma-delimited list of character encodings that the server accepts. The browser
   * uses them in the order in which they are listed. The default value, the reserved string
   * <code>"UNKNOWN"</code>, indicates the same encoding as that of the document containing the form
   * element. In previous versions of HTML, the different character encodings could be delimited by
   * spaces or commas. In HTML5, only spaces are allowed as delimiters.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form">MDN:
   * accept-charset</a>
   */
  public FormTag withAcceptCharset(String value) {
    return attr("accept-charset", value);
  }

  /**
   * Applies {@link #withAcceptCharset(String)} only when {@code condition} is true.
   */
  public FormTag withCondAcceptCharset(boolean condition, String value) {
    return condition ? attr("accept-charset", value) : self();
  }

  /**
   * Sets the <code>action</code> attribute.
   *
   * <p>The URI of a program that processes the form information. This value can be overridden by a
   * <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formaction"><code>formaction</code></a>
   * attribute on a
   * [<code>&lt;button&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
   * "The HTML &lt;button&gt; element represents a clickable button, which can be used in forms or
   * anywhere in a document that needs simple, standard button functionality.") or
   * [<code>&lt;input&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
   * "The HTML &lt;input&gt; element is used to create interactive controls for web-based forms in
   * order to accept data from the user; a wide variety of types of input data and control widgets
   * are available, depending on the device and user agent.") element.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form">MDN:
   * action</a>
   */
  public FormTag withAction(String value) {
    return attr("action", value);
  }

  /**
   * Applies {@link #withAction(String)} only when {@code condition} is true.
   */
  public FormTag withCondAction(boolean condition, String value) {
    return condition ? attr("action", value) : self();
  }

  /**
   * Sets the <code>autocomplete</code> attribute.
   *
   * <p>Indicates whether input elements can by default have their values automatically completed by
   * the browser. This setting can be overridden by an <code>autocomplete</code> attribute on an
   * element belonging to the form. Possible values are:
   *
   * <p>* <code>off</code>: The user must explicitly enter a value into each field for every use, or
   * the document provides its own auto-completion method; the browser does not automatically
   * complete entries. * <code>on</code>: The browser can automatically complete values based on
   * values that the user has previously entered in the form.
   *
   * <p>For most modern browsers (including Firefox 38+, Google Chrome 34+, IE 11+) setting the
   * autocomplete attribute will not prevent a browser's password manager from asking the user if
   * they want to store login fields (username and password), if the user permits the storage the
   * browser will autofill the login the next time the user visits the page. See <a
   * href="https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields">The
   * autocomplete attribute and login fields</a>. **Note:** If you set <code>autocomplete</code> to
   * <code>off</code> in a form because the document provides its own auto-completion, then you
   * should also set <code>autocomplete</code> to <code>off</code> for each of the form's
   * <code>input</code> elements that the document can auto-complete. For details, see the note
   * regarding Google Chrome in the <a href="#compatChart">Browser Compatibility chart</a>.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/autocomplete">MDN:
   * autocomplete</a>
   */
  public FormTag withAutocomplete(String value) {
    return attr("autocomplete", value);
  }

  /**
   * Applies {@link #withAutocomplete(String)} only when {@code condition} is true.
   */
  public FormTag withCondAutocomplete(boolean condition, String value) {
    return condition ? attr("autocomplete", value) : self();
  }

  /**
   * Sets the <code>enctype</code> attribute.
   *
   * <p>When the value of the <code>method</code> attribute is <code>post</code>, enctype is the <a
   * href="https://en.wikipedia.org/wiki/Mime_type">MIME type</a> of content that is used to submit
   * the form to the server. Possible values are:
   *
   * <p>* <code>application/x-www-form-urlencoded</code>: The default value if the attribute is not
   * specified. * <code>multipart/form-data</code>: The value used for an
   * [<code>&lt;input&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
   * "The HTML &lt;input&gt; element is used to create interactive controls for web-based forms in
   * order to accept data from the user; a wide variety of types of input data and control widgets
   * are available, depending on the device and user agent.") element with the <code>type</code>
   * attribute set to "file". * <code>text/plain</code>: (HTML5)
   *
   * <p>This value can be overridden by a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formenctype"><code>formenctype</code></a>
   * attribute on a
   * [<code>&lt;button&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
   * "The HTML &lt;button&gt; element represents a clickable button, which can be used in forms or
   * anywhere in a document that needs simple, standard button functionality.") or
   * [<code>&lt;input&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
   * "The HTML &lt;input&gt; element is used to create interactive controls for web-based forms in
   * order to accept data from the user; a wide variety of types of input data and control widgets
   * are available, depending on the device and user agent.") element.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form">MDN:
   * enctype</a>
   */
  public FormTag withEnctype(String value) {
    return attr("enctype", value);
  }

  /**
   * Applies {@link #withEnctype(String)} only when {@code condition} is true.
   */
  public FormTag withCondEnctype(boolean condition, String value) {
    return condition ? attr("enctype", value) : self();
  }

  /**
   * Sets the <code>method</code> attribute.
   *
   * <p>The <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP">HTTP</a> method that the
   * browser uses to submit the form. Possible values are:
   *
   * <p>* <code>post</code>: Corresponds to the HTTP <a
   * href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5">POST method</a> ; form data
   * are included in the body of the form and sent to the server. * <code>get</code>: Corresponds to
   * the HTTP <a href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.3">GET method</a>;
   * form data are appended to the <code>action</code> attribute URI with a '?' as separator, and the
   * resulting URI is sent to the server. Use this method when the form has no side-effects and
   * contains only ASCII characters. * <code>dialog</code>: Use when the form is inside
   * a [<code>&lt;dialog&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
   * "The HTML &lt;dialog&gt; element represents a dialog box or other interactive component, such as
   * an inspector or window.") element to close the dialog when submitted.
   *
   * <p>This value can be overridden by a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formmethod"><code>formmethod</code></a>
   * attribute on a
   * [<code>&lt;button&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
   * "The HTML &lt;button&gt; element represents a clickable button, which can be used in forms or
   * anywhere in a document that needs simple, standard button functionality.") or
   * [<code>&lt;input&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
   * "The HTML &lt;input&gt; element is used to create interactive controls for web-based forms in
   * order to accept data from the user; a wide variety of types of input data and control widgets
   * are available, depending on the device and user agent.") element.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form">MDN:
   * method</a>
   */
  public FormTag withMethod(String value) {
    return attr("method", value);
  }

  /**
   * Applies {@link #withMethod(String)} only when {@code condition} is true.
   */
  public FormTag withCondMethod(boolean condition, String value) {
    return condition ? attr("method", value) : self();
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>The name of the form. In HTML 4, its use is deprecated (<code>id</code> should be used
   * instead). It must be unique among the forms in a document and not just an empty string in HTML
   * 5.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form">MDN: name</a>
   */
  public FormTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public FormTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }

  /**
   * Sets the <code>novalidate</code> attribute.
   *
   * <p>This Boolean attribute indicates that the form is not to be validated when submitted. If this
   * attribute is not specified (and therefore the form is validated), this default setting can be
   * overridden by a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formnovalidate"><code>formnovalidate</code></a>
   * attribute on a
   * [<code>&lt;button&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
   * "The HTML &lt;button&gt; element represents a clickable button, which can be used in forms or
   * anywhere in a document that needs simple, standard button functionality.") or
   * [<code>&lt;input&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
   * "The HTML &lt;input&gt; element is used to create interactive controls for web-based forms in
   * order to accept data from the user; a wide variety of types of input data and control widgets
   * are available, depending on the device and user agent.") element belonging to the form.
   *
   * <p>Baseline: widely available since 2019-09-27.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form">MDN:
   * novalidate</a>
   */
  public FormTag isNovalidate() {
    return attr("novalidate");
  }

  /**
   * Applies {@link #isNovalidate()} when {@code condition} is true and removes the attribute
   * otherwise, so a form control stays controlled either way (ADR 0013).
   */
  public FormTag withCondNovalidate(boolean condition) {
    return condition ? attr("novalidate") : attr("novalidate", null);
  }

  /**
   * Sets the <code>target</code> attribute.
   *
   * <p>A name or keyword indicating where to display the response that is received after submitting
   * the form. In HTML 4, this is the name/keyword for a frame. In HTML5, it is a name/keyword for a
   * _browsing context_ (for example, tab, window, or inline frame). The following keywords have
   * special meanings:
   *
   * <p>* <code>_self</code>: Load the response into the same HTML 4 frame (or HTML5 browsing
   * context) as the current one. This value is the default if the attribute is not specified. *
   * <code>_blank</code>: Load the response into a new unnamed HTML 4 window or HTML5 browsing
   * context. * <code>_parent</code>: Load the response into the HTML 4 frameset parent of the
   * current frame, or HTML5 parent browsing context of the current one. If there is no parent, this
   * option behaves the same way as <code>_self</code>. * <code>_top</code>: HTML 4: Load the
   * response into the full original window, and cancel all other frames. HTML5: Load the response
   * into the top-level browsing context (i.e., the browsing context that is an ancestor of the
   * current one, and has no parent). If there is no parent, this option behaves the same way as
   * <code>_self</code>. * _iframename_: The response is displayed in a named
   * [<code>&lt;iframe&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
   * "The HTML Inline Frame element (&lt;iframe&gt;) represents a nested browsing context, embedding
   * another HTML page into the current one.").
   *
   * <p>HTML5: This value can be overridden by a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formtarget"><code>formtarget</code></a>
   * attribute on a
   * [<code>&lt;button&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
   * "The HTML &lt;button&gt; element represents a clickable button, which can be used in forms or
   * anywhere in a document that needs simple, standard button functionality.") or
   * [<code>&lt;input&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
   * "The HTML &lt;input&gt; element is used to create interactive controls for web-based forms in
   * order to accept data from the user; a wide variety of types of input data and control widgets
   * are available, depending on the device and user agent.") element.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form">MDN:
   * target</a>
   */
  public FormTag withTarget(String value) {
    return attr("target", value);
  }

  /**
   * Applies {@link #withTarget(String)} only when {@code condition} is true.
   */
  public FormTag withCondTarget(boolean condition, String value) {
    return condition ? attr("target", value) : self();
  }

  /**
   * Sets the <code>accept</code> attribute.
   *
   * <p>A comma-separated list of content types that the server accepts.
   *
   * <p>**Usage note:** This attribute has been removed in HTML5 and should no longer be used.
   * Instead, use the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept"><code>accept</code></a>
   * attribute of the specific
   * [<code>&lt;input&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
   * "The HTML &lt;input&gt; element is used to create interactive controls for web-based forms in
   * order to accept data from the user; a wide variety of types of input data and control widgets
   * are available, depending on the device and user agent.") element.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form">MDN:
   * accept</a>
   */
  public FormTag withAccept(String value) {
    return attr("accept", value);
  }

  /**
   * Applies {@link #withAccept(String)} only when {@code condition} is true.
   */
  public FormTag withCondAccept(boolean condition, String value) {
    return condition ? attr("accept", value) : self();
  }

  /**
   * Sets the <code>rel</code> attribute.
   *
   * <p>Controls the annotations and what kinds of links the form creates.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/form#rel">MDN:
   * rel</a>
   */
  public FormTag withRel(String value) {
    return attr("rel", value);
  }

  /**
   * Applies {@link #withRel(String)} only when {@code condition} is true.
   */
  public FormTag withCondRel(boolean condition, String value) {
    return condition ? attr("rel", value) : self();
  }
}
