// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;header&gt;</code> element.
 *
 * <p>The header element represents introductory content for its nearest ancestor sectioning
 * content or sectioning root element. A header typically contains a group of introductory or
 * navigational aids. When the nearest ancestor sectioning content or sectioning root element is
 * the body element, then it applies to the whole page.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/header">MDN:
 * &lt;header&gt;</a>
 */
public final class HeaderTag extends ContainerTag<HeaderTag> {

  public HeaderTag() {
    super("header");
  }
}
