// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;hr&gt;</code> element.
 *
 * <p>The hr element represents a paragraph-level thematic break, e.g. a scene change in a story,
 * or a transition to another topic within a section of a reference book.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/hr">MDN:
 * &lt;hr&gt;</a>
 */
public final class HrTag extends EmptyTag<HrTag> {

  public HrTag() {
    super("hr");
  }

  /**
   * Sets the <code>align</code> attribute.
   *
   * <p>Sets the alignment of the rule on the page. If no value is specified, the default value is
   * <code>left</code>.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/hr">MDN: align</a>
   * @deprecated The <code>align</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public HrTag withAlign(String value) {
    return attr("align", value);
  }

  /**
   * Applies {@link #withAlign(String)} only when {@code condition} is true.
   */
  @Deprecated
  public HrTag withCondAlign(boolean condition, String value) {
    return condition ? attr("align", value) : self();
  }

  /**
   * Sets the <code>color</code> attribute.
   *
   * <p>Sets the color of the rule through color name or hexadecimal value.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/hr">MDN: color</a>
   * @deprecated The <code>color</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public HrTag withColor(String value) {
    return attr("color", value);
  }

  /**
   * Applies {@link #withColor(String)} only when {@code condition} is true.
   */
  @Deprecated
  public HrTag withCondColor(boolean condition, String value) {
    return condition ? attr("color", value) : self();
  }

  /**
   * Sets the <code>noshade</code> attribute.
   *
   * <p>Sets the rule to have no shading.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/hr">MDN:
   * noshade</a>
   * @deprecated The <code>noshade</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public HrTag withNoshade(String value) {
    return attr("noshade", value);
  }

  /**
   * Applies {@link #withNoshade(String)} only when {@code condition} is true.
   */
  @Deprecated
  public HrTag withCondNoshade(boolean condition, String value) {
    return condition ? attr("noshade", value) : self();
  }

  /**
   * Sets the <code>size</code> attribute.
   *
   * <p>Sets the height, in pixels, of the rule.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/hr">MDN: size</a>
   * @deprecated The <code>size</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public HrTag withSize(String value) {
    return attr("size", value);
  }

  /**
   * Applies {@link #withSize(String)} only when {@code condition} is true.
   */
  @Deprecated
  public HrTag withCondSize(boolean condition, String value) {
    return condition ? attr("size", value) : self();
  }

  /**
   * Sets the <code>width</code> attribute.
   *
   * <p>Sets the length of the rule on the page through a pixel or percentage value.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/hr">MDN: width</a>
   * @deprecated The <code>width</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public HrTag withWidth(String value) {
    return attr("width", value);
  }

  /**
   * Applies {@link #withWidth(String)} only when {@code condition} is true.
   */
  @Deprecated
  public HrTag withCondWidth(boolean condition, String value) {
    return condition ? attr("width", value) : self();
  }
}
