// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;html&gt;</code> element.
 *
 * <p>The html element represents the root of an HTML document.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/html">MDN:
 * &lt;html&gt;</a>
 */
public final class HtmlTag extends ContainerTag<HtmlTag> {

  public HtmlTag() {
    super("html");
  }

  /**
   * Sets the <code>manifest</code> attribute.
   *
   * <p>Specifies the URI of a resource manifest indicating resources that should be cached locally.
   * See <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache">Using the
   * application cache</a> for details.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/html">MDN:
   * manifest</a>
   */
  public HtmlTag withManifest(String value) {
    return attr("manifest", value);
  }

  /**
   * Applies {@link #withManifest(String)} only when {@code condition} is true.
   */
  public HtmlTag withCondManifest(boolean condition, String value) {
    return condition ? attr("manifest", value) : self();
  }

  /**
   * Sets the <code>version</code> attribute.
   *
   * <p>Specifies the version of the HTML [Document Type
   * Definition](https://developer.mozilla.org/en-US/docs/Glossary/DTD "Document Type Definition: In
   * HTML, the doctype is the required "&lt;!DOCTYPE html&gt;" preamble found at the top of all
   * documents. Its sole purpose is to prevent a browser from switching into so-called “quirks mode”
   * when rendering a document; that is, the "&lt;!DOCTYPE html&gt;" doctype ensures that the browser
   * makes a best-effort attempt at following the relevant specifications, rather than using a
   * different rendering mode that is incompatible with some specifications.") that governs the
   * current document. This attribute is not needed, because it is redundant with the version
   * information in the document type declaration.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/html">MDN:
   * version</a>
   * @deprecated The <code>version</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public HtmlTag withVersion(String value) {
    return attr("version", value);
  }

  /**
   * Applies {@link #withVersion(String)} only when {@code condition} is true.
   */
  @Deprecated
  public HtmlTag withCondVersion(boolean condition, String value) {
    return condition ? attr("version", value) : self();
  }

  /**
   * Sets the <code>xmlns</code> attribute.
   *
   * <p>Specifies the XML Namespace of the document. Default value is
   * <code>"http://www.w3.org/1999/xhtml"</code>. This is required in documents parsed with XML
   * parsers, and optional in text/html documents.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/html">MDN:
   * xmlns</a>
   */
  public HtmlTag withXmlns(String value) {
    return attr("xmlns", value);
  }

  /**
   * Applies {@link #withXmlns(String)} only when {@code condition} is true.
   */
  public HtmlTag withCondXmlns(boolean condition, String value) {
    return condition ? attr("xmlns", value) : self();
  }
}
