// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;iframe&gt;</code> element.
 *
 * <p>The iframe element represents a nested browsing context.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
 * &lt;iframe&gt;</a>
 */
public final class IframeTag extends ContainerTag<IframeTag> {

  public IframeTag() {
    super("iframe");
  }

  /**
   * Sets the <code>src</code> attribute.
   *
   * <p>The URL of the page to embed. Use a value of <code>about:blank</code> to embed an empty page
   * that conforms to the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Inherited_origins">same-origin
   * policy</a>. Also note that programatically removing an <code>&lt;iframe&gt;</code>'s src
   * attribute (e.g. via
   * [<code>Element.removeAttribute()</code>](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute
   * "The Element method removeAttribute() removes the attribute with the specified name from the
   * element.")) causes <code>about:blank</code> to be loaded in the frame in Firefox (from version
   * 65), Chromium-based browsers, and Safari/iOS.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * src</a>
   */
  public IframeTag withSrc(String value) {
    return attr("src", value);
  }

  /**
   * Applies {@link #withSrc(String)} only when {@code condition} is true.
   */
  public IframeTag withCondSrc(boolean condition, String value) {
    return condition ? attr("src", value) : self();
  }

  /**
   * Sets the <code>srcdoc</code> attribute.
   *
   * <p>Inline HTML to embed, overriding the <code>src</code> attribute. If a browser does not
   * support the <code>srcdoc</code> attribute, it will fall back to the URL in the <code>src</code>
   * attribute.
   *
   * <p>Baseline: widely available since 2022-07-15.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * srcdoc</a>
   */
  public IframeTag withSrcdoc(String value) {
    return attr("srcdoc", value);
  }

  /**
   * Applies {@link #withSrcdoc(String)} only when {@code condition} is true.
   */
  public IframeTag withCondSrcdoc(boolean condition, String value) {
    return condition ? attr("srcdoc", value) : self();
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>A targetable name for the embedded browsing context. This can be used in the
   * <code>target</code> attribute of the
   * [<code>&lt;a&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a "The HTML
   * &lt;a&gt; element (or anchor element) creates a hyperlink to other web pages, files, locations
   * within the same page, email addresses, or any other URL."),
   * [<code>&lt;form&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form "The
   * HTML &lt;form&gt; element represents a document section that contains interactive controls for
   * submitting information to a web server."), or
   * [<code>&lt;base&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base "The
   * HTML &lt;base&gt; element specifies the base URL to use for all relative URLs contained within a
   * document. There can be only one &lt;base&gt; element in a document.") elements; the
   * <code>formtarget</code> attribute of the
   * [<code>&lt;input&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
   * "The HTML &lt;input&gt; element is used to create interactive controls for web-based forms in
   * order to accept data from the user; a wide variety of types of input data and control widgets
   * are available, depending on the device and user agent.") or
   * [<code>&lt;button&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
   * "The HTML &lt;button&gt; element represents a clickable button, which can be used in forms or
   * anywhere in a document that needs simple, standard button functionality.") elements; or the
   * <code>windowName</code> parameter in the
   * [<code>window.open()</code>](https://developer.mozilla.org/en-US/docs/Web/API/Window/open
   * "The Window interface's open() method loads the specified resource into the browsing context
   * (window, &lt;iframe&gt; or tab) with the specified name. If the name doesn't exist, then a new
   * window is opened and the specified resource is loaded into its browsing context.") method.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * name</a>
   */
  public IframeTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public IframeTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }

  /**
   * Sets the <code>sandbox</code> attribute.
   *
   * <p>Applies extra restrictions to the content in the frame. The value of the attribute can either
   * be empty to apply all restrictions, or space-separated tokens to lift particular restrictions:
   *
   * <p>* <code>allow-forms</code>: Allows the resource to submit forms. If this keyword is not used,
   * form submission is blocked. * <code>allow-modals</code>: Lets the resource <a
   * href="https://html.spec.whatwg.org/multipage/origin.html#sandboxed-modals-flag">open modal
   * windows</a>. * <code>allow-orientation-lock</code>: Lets the resource <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/Screen/lockOrientation">lock the screen
   * orientation</a>. * <code>allow-pointer-lock</code>: Lets the resource use the <a
   * href="https://developer.mozilla.org/en-US/docs/WebAPI/Pointer_Lock">Pointer Lock API</a>. *
   * <code>allow-popups</code>: Allows popups (such as <code>window.open()</code>,
   * <code>target="_blank"</code>, or <code>showModalDialog()</code>). If this keyword is not used,
   * the popup will silently fail to open. * <code>allow-popups-to-escape-sandbox</code>: Lets the
   * sandboxed document open new windows without those windows inheriting the sandboxing. For
   * example, this can safely sandbox an advertisement without forcing the same restrictions upon the
   * page the ad links to. * <code>allow-presentation</code>: Lets the resource start a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/PresentationRequest">presentation
   * session</a>. * <code>allow-same-origin</code>: If this token is not used, the resource is
   * treated as being from a special origin that always fails the [same-origin
   * policy](https://developer.mozilla.org/en-US/docs/Glossary/same-origin_policy "same-origin
   * policy: The same-origin policy is a critical security mechanism that restricts how a document or
   * script loaded from one origin can interact with a resource from another origin."). *
   * <code>allow-scripts</code>: Lets the resource run scripts (but not create popup windows). *
   * <code>allow-storage-access-by-user-activation</code> : Lets the resource request access to the
   * parent's storage capabilities with the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API">Storage Access
   * API</a>. * <code>allow-top-navigation</code>: Lets the resource navigate the top-level browsing
   * context (the one named <code>_top</code>). *
   * <code>allow-top-navigation-by-user-activation</code>: Lets the resource navigate the top-level
   * browsing context, but only if initiated by a user gesture.
   *
   * <p>**Notes about sandboxing:**
   *
   * <p>* When the embedded document has the same origin as the embedding page, it is **strongly
   * discouraged** to use both <code>allow-scripts</code> and <code>allow-same-origin</code>, as that
   * lets the embedded document remove the <code>sandbox</code> attribute — making it no more secure
   * than not using the <code>sandbox</code> attribute at all. * Sandboxing is useless if the
   * attacker can display content outside a sandboxed <code>iframe</code> — such as if the viewer
   * opens the frame in a new tab. Such content should be also served from a _separate origin_ to
   * limit potential damage. * The <code>sandbox</code> attribute is unsupported in Internet Explorer
   * 9 and earlier.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * sandbox</a>
   */
  public IframeTag withSandbox(String value) {
    return attr("sandbox", value);
  }

  /**
   * Applies {@link #withSandbox(String)} only when {@code condition} is true.
   */
  public IframeTag withCondSandbox(boolean condition, String value) {
    return condition ? attr("sandbox", value) : self();
  }

  /**
   * Sets <code>sandbox</code> with no value. See {@link #withSandbox(String)}.
   */
  public IframeTag isSandbox() {
    return attr("sandbox");
  }

  /**
   * Sets the <code>seamless</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * seamless</a>
   */
  public IframeTag isSeamless() {
    return attr("seamless");
  }

  /**
   * Applies {@link #isSeamless()} when {@code condition} is true and removes the attribute
   * otherwise, so a form control stays controlled either way (ADR 0013).
   */
  public IframeTag withCondSeamless(boolean condition) {
    return condition ? attr("seamless") : attr("seamless", null);
  }

  /**
   * Sets the <code>allowfullscreen</code> attribute.
   *
   * <p>Set to <code>true</code> if the <code>&lt;iframe&gt;</code> can activate fullscreen mode by
   * calling the
   * [<code>requestFullscreen()</code>](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen
   * "The Element.requestFullscreen() method issues an asynchronous request to make the element be
   * displayed in full-screen mode.") method. This attribute is considered a legacy attribute and
   * redefined as <code>allow="fullscreen"</code>.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * allowfullscreen</a>
   */
  public IframeTag isAllowfullscreen() {
    return attr("allowfullscreen");
  }

  /**
   * Applies {@link #isAllowfullscreen()} when {@code condition} is true and removes the attribute
   * otherwise, so a form control stays controlled either way (ADR 0013).
   */
  public IframeTag withCondAllowfullscreen(boolean condition) {
    return condition ? attr("allowfullscreen") : attr("allowfullscreen", null);
  }

  /**
   * Sets the <code>width</code> attribute.
   *
   * <p>The width of the frame in CSS pixels. Default is <code>300</code>.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * width</a>
   */
  public IframeTag withWidth(String value) {
    return attr("width", value);
  }

  /**
   * Applies {@link #withWidth(String)} only when {@code condition} is true.
   */
  public IframeTag withCondWidth(boolean condition, String value) {
    return condition ? attr("width", value) : self();
  }

  /**
   * Sets the <code>height</code> attribute.
   *
   * <p>The height of the frame in CSS pixels. Default is <code>150</code>.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * height</a>
   */
  public IframeTag withHeight(String value) {
    return attr("height", value);
  }

  /**
   * Applies {@link #withHeight(String)} only when {@code condition} is true.
   */
  public IframeTag withCondHeight(boolean condition, String value) {
    return condition ? attr("height", value) : self();
  }

  /**
   * Sets the <code>allow</code> attribute.
   *
   * <p>Specifies a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy">feature policy</a> for
   * the <code>&lt;iframe&gt;</code>.
   *
   * <p>Baseline: widely available since 2023-01-28.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * allow</a>
   */
  public IframeTag withAllow(String value) {
    return attr("allow", value);
  }

  /**
   * Applies {@link #withAllow(String)} only when {@code condition} is true.
   */
  public IframeTag withCondAllow(boolean condition, String value) {
    return condition ? attr("allow", value) : self();
  }

  /**
   * Sets the <code>allowpaymentrequest</code> attribute.
   *
   * <p>Set to <code>true</code> if a cross-origin <code>&lt;iframe&gt;</code> should be allowed to
   * invoke the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API">Payment Request
   * API</a>.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * allowpaymentrequest</a>
   * @deprecated The <code>allowpaymentrequest</code> attribute is marked deprecated in MDN
   * browser-compat-data; avoid in new markup.
   */
  @Deprecated
  public IframeTag withAllowpaymentrequest(String value) {
    return attr("allowpaymentrequest", value);
  }

  /**
   * Applies {@link #withAllowpaymentrequest(String)} only when {@code condition} is true.
   */
  @Deprecated
  public IframeTag withCondAllowpaymentrequest(boolean condition, String value) {
    return condition ? attr("allowpaymentrequest", value) : self();
  }

  /**
   * Sets the <code>csp</code> attribute.
   *
   * <p>A <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP">Content Security Policy</a>
   * enforced for the embedded resource. See
   * [<code>HTMLIFrameElement.csp</code>](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/csp
   * "The csp property of the HTMLIFrameElement interface specifies the Content Security Policy that
   * an embedded document must agree to enforce upon itself.") for details.
   *
   * <p>Limited availability: not yet supported in all major browsers. Experimental.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * csp</a>
   */
  public IframeTag withCsp(String value) {
    return attr("csp", value);
  }

  /**
   * Applies {@link #withCsp(String)} only when {@code condition} is true.
   */
  public IframeTag withCondCsp(boolean condition, String value) {
    return condition ? attr("csp", value) : self();
  }

  /**
   * Sets the <code>importance</code> attribute.
   *
   * <p>The download priority of the resource in the <code>&lt;iframe&gt;</code>'s <code>src</code>
   * attribute. Allowed values:
   *
   * <p><code>auto</code> (default)
   *
   * <p>No preference. The browser uses its own heuristics to decide the priority of the resource.
   *
   * <p><code>high</code>
   *
   * <p>The resource should be downloaded before other lower-priority page resources.
   *
   * <p><code>low</code>
   *
   * <p>The resource should be downloaded after other higher-priority page resources.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * importance</a>
   */
  public IframeTag withImportance(String value) {
    return attr("importance", value);
  }

  /**
   * Applies {@link #withImportance(String)} only when {@code condition} is true.
   */
  public IframeTag withCondImportance(boolean condition, String value) {
    return condition ? attr("importance", value) : self();
  }

  /**
   * Sets the <code>referrerpolicy</code> attribute.
   *
   * <p>Indicates which <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer">referrer</a> to send
   * when fetching the frame's resource:
   *
   * <p>* <code>no-referrer</code>: The
   * [<code>Referer</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer "The
   * Referer request header contains the address of the previous web page from which a link to the
   * currently requested page was followed. The Referer header allows servers to identify where
   * people are visiting them from and may use that data for analytics, logging, or optimized
   * caching, for example.") header will not be sent. * <code>no-referrer-when-downgrade</code>
   * (default): The
   * [<code>Referer</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer "The
   * Referer request header contains the address of the previous web page from which a link to the
   * currently requested page was followed. The Referer header allows servers to identify where
   * people are visiting them from and may use that data for analytics, logging, or optimized
   * caching, for example.") header will not be sent to
   * [origin](https://developer.mozilla.org/en-US/docs/Glossary/origin "origin: Web content's origin
   * is defined by the scheme (protocol), host (domain), and port of the URL used to access it. Two
   * objects have the same origin only when the scheme, host, and port all match.")s without
   * [TLS](https://developer.mozilla.org/en-US/docs/Glossary/TLS "TLS: Transport Layer Security
   * (TLS), previously known as Secure Sockets Layer (SSL), is a protocol used by applications to
   * communicate securely across a network, preventing tampering with and eavesdropping on email, web
   * browsing, messaging, and other protocols.")
   * ([HTTPS](https://developer.mozilla.org/en-US/docs/Glossary/HTTPS "HTTPS: HTTPS (HTTP Secure) is
   * an encrypted version of the HTTP protocol. It usually uses SSL or TLS to encrypt all
   * communication between a client and a server. This secure connection allows clients to safely
   * exchange sensitive data with a server, for example for banking activities or online
   * shopping.")). * <code>origin</code>: The sent referrer will be limited to the origin of the
   * referring page: its <a
   * href="https://developer.mozilla.org/en-US/docs/Archive/Mozilla/URIScheme">scheme</a>,
   * [host](https://developer.mozilla.org/en-US/docs/Glossary/host "host: A host is a device
   * connected to the Internet (or a local network). Some hosts called servers offer additional
   * services like serving webpages or storing files and emails."), and
   * [port](https://developer.mozilla.org/en-US/docs/Glossary/port "port: For a computer connected to
   * a network with an IP address, a port is a communication endpoint. Ports are designated by
   * numbers, and below 1024 each port is associated by default with a specific protocol."). *
   * <code>origin-when-cross-origin</code>: The referrer sent to other origins will be limited to the
   * scheme, the host, and the port. Navigations on the same origin will still include the path. *
   * <code>same-origin</code>: A referrer will be sent for [same
   * origin](https://developer.mozilla.org/en-US/docs/Glossary/Same-origin_policy "same origin: The
   * same-origin policy is a critical security mechanism that restricts how a document or script
   * loaded from one origin can interact with a resource from another origin."), but cross-origin
   * requests will contain no referrer information. * <code>strict-origin</code>: Only send the
   * origin of the document as the referrer when the protocol security level stays the same
   * (HTTPS→HTTPS), but don't send it to a less secure destination (HTTPS→HTTP). *
   * <code>strict-origin-when-cross-origin</code>: Send a full URL when performing a same-origin
   * request, only send the origin when the protocol security level stays the same (HTTPS→HTTPS), and
   * send no header to a less secure destination (HTTPS→HTTP). * <code>unsafe-url</code>: The
   * referrer will include the origin _and_ the path (but not the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/hash">fragment</a>,
   * <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/password">password</a>,
   * or <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/username">username</a>).
   * **This value is unsafe**, because it leaks origins and paths from TLS-protected resources to
   * insecure origins.
   *
   * <p>Baseline: widely available since 2023-03-16.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/iframe">MDN:
   * referrerpolicy</a>
   */
  public IframeTag withReferrerpolicy(String value) {
    return attr("referrerpolicy", value);
  }

  /**
   * Applies {@link #withReferrerpolicy(String)} only when {@code condition} is true.
   */
  public IframeTag withCondReferrerpolicy(boolean condition, String value) {
    return condition ? attr("referrerpolicy", value) : self();
  }
}
