// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;img&gt;</code> element.
 *
 * <p>An img element represents an image.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN:
 * &lt;img&gt;</a>
 */
public final class ImgTag extends EmptyTag<ImgTag> {

  public ImgTag() {
    super("img");
  }

  /**
   * Sets the <code>alt</code> attribute.
   *
   * <p>This attribute defines an alternative text description of the image.
   *
   * <p>**Note:** Browsers do not always display the image referenced by the element. This is the
   * case for non-graphical browsers (including those used by people with visual impairments), if the
   * user chooses not to display images, or if the browser cannot display the image because it is
   * invalid or an <a href="#Supported_image_formats">unsupported type</a>. In these cases, the
   * browser may replace the image with the text defined in this element's <code>alt</code>
   * attribute. You should, for these reasons and others, provide a useful value for <code>alt</code>
   * whenever possible.
   *
   * <p>**Note:** Omitting this attribute altogether indicates that the image is a key part of the
   * content, and no textual equivalent is available. Setting this attribute to an empty string
   * (<code>alt=""</code>) indicates that this image is _not_ a key part of the content (decorative),
   * and that non-visual browsers may omit it from rendering.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN: alt</a>
   */
  public ImgTag withAlt(String value) {
    return attr("alt", value);
  }

  /**
   * Applies {@link #withAlt(String)} only when {@code condition} is true.
   */
  public ImgTag withCondAlt(boolean condition, String value) {
    return condition ? attr("alt", value) : self();
  }

  /**
   * Sets the <code>src</code> attribute.
   *
   * <p>The image URL. This attribute is mandatory for the <code>&lt;img&gt;</code> element. On
   * browsers supporting <code>srcset</code>, <code>src</code> is treated like a candidate image with
   * a pixel density descriptor <code>1x</code> unless an image with this pixel density descriptor is
   * already defined in <code>srcset,</code> or unless <code>srcset</code> contains '<code>w</code>'
   * descriptors.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN: src</a>
   */
  public ImgTag withSrc(String value) {
    return attr("src", value);
  }

  /**
   * Applies {@link #withSrc(String)} only when {@code condition} is true.
   */
  public ImgTag withCondSrc(boolean condition, String value) {
    return condition ? attr("src", value) : self();
  }

  /**
   * Sets the <code>srcset</code> attribute.
   *
   * <p>A list of one or more strings separated by commas indicating a set of possible image sources
   * for the user agent to use. Each string is composed of:
   *
   * <p>1. a URL to an image, 2. optionally, whitespace followed by one of: * A width descriptor, or
   * a positive integer directly followed by '<code>w</code>'. The width descriptor is divided by the
   * source size given in the <code>sizes</code> attribute to calculate the effective pixel density.
   * * A pixel density descriptor, which is a positive floating point number directly followed by
   * '<code>x</code>'.
   *
   * <p>If no descriptor is specified, the source is assigned the default descriptor:
   * <code>1x</code>.
   *
   * <p>It is incorrect to mix width descriptors and pixel density descriptors in the same
   * <code>srcset</code> attribute. Duplicate descriptors (for instance, two sources in the same
   * <code>srcset</code> which are both described with '<code>2x</code>') are also invalid.
   *
   * <p>The user agent selects any one of the available sources at its discretion. This provides them
   * with significant leeway to tailor their selection based on things like user preferences or
   * bandwidth conditions. See our <a
   * href="https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images">Responsive
   * images</a> tutorial for an example.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN:
   * srcset</a>
   */
  public ImgTag withSrcset(String value) {
    return attr("srcset", value);
  }

  /**
   * Applies {@link #withSrcset(String)} only when {@code condition} is true.
   */
  public ImgTag withCondSrcset(boolean condition, String value) {
    return condition ? attr("srcset", value) : self();
  }

  /**
   * Sets the <code>crossorigin</code> attribute.
   *
   * <p>This enumerated attribute indicates if the fetching of the related image must be done using
   * CORS or not. <a href="https://developer.mozilla.org/en-US/docs/CORS_Enabled_Image">CORS-enabled
   * images</a> can be reused in the
   * [<code>&lt;canvas&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas
   * "Use the HTML &lt;canvas&gt; element with either the canvas scripting API or the WebGL API to
   * draw graphics and animations.") element without being "<a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#What_is_a_tainted_canvas">tainted</a>."
   * The allowed values are: <code>anonymous</code>
   *
   * <p>A cross-origin request (i.e., with <code>Origin:</code> HTTP header) is performed, but no
   * credential is sent (i.e., no cookie, X.509 certificate, or HTTP Basic authentication). If the
   * server does not give credentials to the origin site (by not setting the
   * [<code>Access-Control-Allow-Origin</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
   * "The Access-Control-Allow-Origin response header indicates whether the response can be shared
   * with requesting code from the given origin.") HTTP header), the image will be tainted and its
   * usage restricted.
   *
   * <p><code>use-credentials</code>
   *
   * <p>A cross-origin request (i.e., with the
   * [<code>Origin</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin "The
   * Origin request header indicates where a fetch originates from. It doesn't include any path
   * information, but only the server name. It is sent with CORS requests, as well as with POST
   * requests. It is similar to the Referer header, but, unlike this header, it doesn't disclose the
   * whole path.") HTTP header) performed along with credentials sent (i.e., a cookie, certificate,
   * or HTTP Basic authentication). If the server does not give credentials to the origin site
   * (through the <code>Access-Control-Allow-Credentials</code> HTTP header), the image will be
   * tainted and its usage restricted.
   *
   * <p>If the attribute is not present, the resource is fetched without a CORS request (i.e.,
   * without sending the <code>Origin</code> HTTP header), preventing its non-tainted usage in
   * [<code>&lt;canvas&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas
   * "Use the HTML &lt;canvas&gt; element with either the canvas scripting API or the WebGL API to
   * draw graphics and animations.") elements. If invalid, it is handled as if the
   * <code>anonymous</code> value was used. See <a
   * href="https://developer.mozilla.org/en-US/docs/HTML/CORS_settings_attributes">CORS settings
   * attributes</a> for additional information.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/crossorigin">MDN:
   * crossorigin</a>
   */
  public ImgTag withCrossorigin(String value) {
    return attr("crossorigin", value);
  }

  /**
   * Applies {@link #withCrossorigin(String)} only when {@code condition} is true.
   */
  public ImgTag withCondCrossorigin(boolean condition, String value) {
    return condition ? attr("crossorigin", value) : self();
  }

  /**
   * Sets the <code>usemap</code> attribute.
   *
   * <p>The partial URL (starting with '#') of an <a
   * href="https://developer.mozilla.org/en-US/docs/HTML/Element/map">image map</a> associated with
   * the element.
   *
   * <p>**Note:** You cannot use this attribute if the <code>&lt;img&gt;</code> element is a
   * descendant of an
   * [<code>&lt;a&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a "The HTML
   * &lt;a&gt; element (or anchor element) creates a hyperlink to other web pages, files, locations
   * within the same page, email addresses, or any other URL.") or
   * [<code>&lt;button&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
   * "The HTML &lt;button&gt; element represents a clickable button, which can be used in forms or
   * anywhere in a document that needs simple, standard button functionality.") element.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN:
   * usemap</a>
   */
  public ImgTag withUsemap(String value) {
    return attr("usemap", value);
  }

  /**
   * Applies {@link #withUsemap(String)} only when {@code condition} is true.
   */
  public ImgTag withCondUsemap(boolean condition, String value) {
    return condition ? attr("usemap", value) : self();
  }

  /**
   * Sets the <code>ismap</code> attribute.
   *
   * <p>This Boolean attribute indicates that the image is part of a server-side map. If so, the
   * precise coordinates of a click are sent to the server.
   *
   * <p>**Note:** This attribute is allowed only if the <code>&lt;img&gt;</code> element is a
   * descendant of an
   * [<code>&lt;a&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a "The HTML
   * &lt;a&gt; element (or anchor element) creates a hyperlink to other web pages, files, locations
   * within the same page, email addresses, or any other URL.") element with a valid <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-href"><code>href</code></a>
   * attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN: ismap</a>
   */
  public ImgTag isIsmap() {
    return attr("ismap");
  }

  /**
   * Applies {@link #isIsmap()} only when {@code condition} is true.
   */
  public ImgTag withCondIsmap(boolean condition) {
    return condition ? attr("ismap") : self();
  }

  /**
   * Sets the <code>width</code> attribute.
   *
   * <p>The intrinsic width of the image in pixels.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN: width</a>
   */
  public ImgTag withWidth(String value) {
    return attr("width", value);
  }

  /**
   * Applies {@link #withWidth(String)} only when {@code condition} is true.
   */
  public ImgTag withCondWidth(boolean condition, String value) {
    return condition ? attr("width", value) : self();
  }

  /**
   * Sets the <code>height</code> attribute.
   *
   * <p>The intrinsic height of the image in pixels.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN:
   * height</a>
   */
  public ImgTag withHeight(String value) {
    return attr("height", value);
  }

  /**
   * Applies {@link #withHeight(String)} only when {@code condition} is true.
   */
  public ImgTag withCondHeight(boolean condition, String value) {
    return condition ? attr("height", value) : self();
  }

  /**
   * Sets the <code>decoding</code> attribute.
   *
   * <p>Provides an image decoding hint to the browser. The allowed values are: <code>sync</code>
   *
   * <p>Decode the image synchronously for atomic presentation with other content.
   *
   * <p><code>async</code>
   *
   * <p>Decode the image asynchronously to reduce delay in presenting other content.
   *
   * <p><code>auto</code>
   *
   * <p>Default mode, which indicates no preference for the decoding mode. The browser decides what
   * is best for the user.
   *
   * <p>Baseline: widely available since 2022-07-15.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img#decoding">MDN:
   * decoding</a>
   */
  public ImgTag withDecoding(String value) {
    return attr("decoding", value);
  }

  /**
   * Applies {@link #withDecoding(String)} only when {@code condition} is true.
   */
  public ImgTag withCondDecoding(boolean condition, String value) {
    return condition ? attr("decoding", value) : self();
  }

  /**
   * Sets the <code>loading</code> attribute.
   *
   * <p>Indicates how the browser should load the image.
   *
   * <p>Baseline: widely available since 2024-09-14.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN:
   * loading</a>
   */
  public ImgTag withLoading(String value) {
    return attr("loading", value);
  }

  /**
   * Applies {@link #withLoading(String)} only when {@code condition} is true.
   */
  public ImgTag withCondLoading(boolean condition, String value) {
    return condition ? attr("loading", value) : self();
  }

  /**
   * Sets the <code>fetchpriority</code> attribute.
   *
   * <p>Provides a hint of the relative priority to use when fetching the image.
   *
   * <p>Baseline: newly available since 2024-10-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/fetchpriority">MDN:
   * fetchpriority</a>
   */
  public ImgTag withFetchpriority(String value) {
    return attr("fetchpriority", value);
  }

  /**
   * Applies {@link #withFetchpriority(String)} only when {@code condition} is true.
   */
  public ImgTag withCondFetchpriority(boolean condition, String value) {
    return condition ? attr("fetchpriority", value) : self();
  }

  /**
   * Sets the <code>referrerpolicy</code> attribute.
   *
   * <p>A string indicating which referrer to use when fetching the resource:
   *
   * <p>* <code>no-referrer:</code> The
   * [<code>Referer</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer "The
   * Referer request header contains the address of the previous web page from which a link to the
   * currently requested page was followed. The Referer header allows servers to identify where
   * people are visiting them from and may use that data for analytics, logging, or optimized
   * caching, for example.") header will not be sent. * <code>no-referrer-when-downgrade:</code> No
   * <code>Referer</code> header will be sent when navigating to an origin without TLS (HTTPS). This
   * is a user agent’s default behavior if no policy is otherwise specified. * <code>origin:</code>
   * The <code>Referer</code> header will include the page of origin's scheme, the host, and the
   * port. * <code>origin-when-cross-origin:</code> Navigating to other origins will limit the
   * included referral data to the scheme, the host and the port, while navigating from the same
   * origin will include the referrer's full path. * <code>unsafe-url:</code> The
   * <code>Referer</code> header will include the origin and the path, but not the fragment,
   * password, or username. This case is unsafe because it can leak origins and paths from
   * TLS-protected resources to insecure origins.
   *
   * <p>Baseline: widely available since 2023-03-16.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN:
   * referrerpolicy</a>
   */
  public ImgTag withReferrerpolicy(String value) {
    return attr("referrerpolicy", value);
  }

  /**
   * Applies {@link #withReferrerpolicy(String)} only when {@code condition} is true.
   */
  public ImgTag withCondReferrerpolicy(boolean condition, String value) {
    return condition ? attr("referrerpolicy", value) : self();
  }

  /**
   * Sets the <code>sizes</code> attribute.
   *
   * <p>A list of one or more strings separated by commas indicating a set of source sizes. Each
   * source size consists of:
   *
   * <p>1. a media condition. This must be omitted for the last item. 2. a source size value.
   *
   * <p>Source size values specify the intended display size of the image. User agents use the
   * current source size to select one of the sources supplied by the <code>srcset</code> attribute,
   * when those sources are described using width ('<code>w</code>') descriptors. The selected source
   * size affects the intrinsic size of the image (the image’s display size if no CSS styling is
   * applied). If the <code>srcset</code> attribute is absent, or contains no values with a width
   * (<code>w</code>) descriptor, then the <code>sizes</code> attribute has no effect.
   *
   * <p>Baseline: widely available since 2018-09-21.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN: sizes</a>
   */
  public ImgTag withSizes(String value) {
    return attr("sizes", value);
  }

  /**
   * Applies {@link #withSizes(String)} only when {@code condition} is true.
   */
  public ImgTag withCondSizes(boolean condition, String value) {
    return condition ? attr("sizes", value) : self();
  }

  /**
   * Sets the <code>importance</code> attribute.
   *
   * <p>Indicates the relative importance of the resource. Priority hints are delegated using the
   * values:
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN:
   * importance</a>
   */
  public ImgTag withImportance(String value) {
    return attr("importance", value);
  }

  /**
   * Applies {@link #withImportance(String)} only when {@code condition} is true.
   */
  public ImgTag withCondImportance(boolean condition, String value) {
    return condition ? attr("importance", value) : self();
  }

  /**
   * Sets the <code>intrinsicsize</code> attribute.
   *
   * <p>This attribute tells the browser to ignore the actual intrinsic size of the image and pretend
   * it’s the size specified in the attribute. Specifically, the image would raster at these
   * dimensions and <code>naturalWidth</code>/<code>naturalHeight</code> on images would return the
   * values specified in this attribute. <a
   * href="https://github.com/ojanvafai/intrinsicsize-attribute">Explainer</a>, <a
   * href="https://googlechrome.github.io/samples/intrinsic-size/index.html">examples</a>
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img">MDN:
   * intrinsicsize</a>
   */
  public ImgTag withIntrinsicsize(String value) {
    return attr("intrinsicsize", value);
  }

  /**
   * Applies {@link #withIntrinsicsize(String)} only when {@code condition} is true.
   */
  public ImgTag withCondIntrinsicsize(boolean condition, String value) {
    return condition ? attr("intrinsicsize", value) : self();
  }
}
