// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;input&gt;</code> element.
 *
 * <p>The input element represents a typed data field, usually with a form control to allow the
 * user to edit the data.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input">MDN:
 * &lt;input&gt;</a>
 */
public final class InputTag extends EmptyTag<InputTag> {

  public InputTag() {
    super("input");
  }

  /**
   * Sets the <code>accept</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/accept">MDN:
   * accept</a>
   */
  public InputTag withAccept(String value) {
    return attr("accept", value);
  }

  /**
   * Applies {@link #withAccept(String)} only when {@code condition} is true.
   */
  public InputTag withCondAccept(boolean condition, String value) {
    return condition ? attr("accept", value) : self();
  }

  /**
   * Sets the <code>alt</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#alt">MDN:
   * alt</a>
   */
  public InputTag withAlt(String value) {
    return attr("alt", value);
  }

  /**
   * Applies {@link #withAlt(String)} only when {@code condition} is true.
   */
  public InputTag withCondAlt(boolean condition, String value) {
    return condition ? attr("alt", value) : self();
  }

  /**
   * Sets the <code>autocomplete</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/autocomplete">MDN:
   * autocomplete</a>
   */
  public InputTag withAutocomplete(String value) {
    return attr("autocomplete", value);
  }

  /**
   * Applies {@link #withAutocomplete(String)} only when {@code condition} is true.
   */
  public InputTag withCondAutocomplete(boolean condition, String value) {
    return condition ? attr("autocomplete", value) : self();
  }

  /**
   * Sets the <code>checked</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#checked">MDN:
   * checked</a>
   */
  public InputTag isChecked() {
    return attr("checked");
  }

  /**
   * Applies {@link #isChecked()} only when {@code condition} is true.
   */
  public InputTag withCondChecked(boolean condition) {
    return condition ? attr("checked") : self();
  }

  /**
   * Sets the <code>dirname</code> attribute.
   *
   * <p>Baseline: widely available since 2026-02-01.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#dirname">MDN:
   * dirname</a>
   */
  public InputTag withDirname(String value) {
    return attr("dirname", value);
  }

  /**
   * Applies {@link #withDirname(String)} only when {@code condition} is true.
   */
  public InputTag withCondDirname(boolean condition, String value) {
    return condition ? attr("dirname", value) : self();
  }

  /**
   * Sets the <code>disabled</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/disabled">MDN:
   * disabled</a>
   */
  public InputTag isDisabled() {
    return attr("disabled");
  }

  /**
   * Applies {@link #isDisabled()} only when {@code condition} is true.
   */
  public InputTag withCondDisabled(boolean condition) {
    return condition ? attr("disabled") : self();
  }

  /**
   * Sets the <code>form</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#form">MDN:
   * form</a>
   */
  public InputTag withForm(String value) {
    return attr("form", value);
  }

  /**
   * Applies {@link #withForm(String)} only when {@code condition} is true.
   */
  public InputTag withCondForm(boolean condition, String value) {
    return condition ? attr("form", value) : self();
  }

  /**
   * Sets the <code>formaction</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#formaction">MDN:
   * formaction</a>
   */
  public InputTag withFormaction(String value) {
    return attr("formaction", value);
  }

  /**
   * Applies {@link #withFormaction(String)} only when {@code condition} is true.
   */
  public InputTag withCondFormaction(boolean condition, String value) {
    return condition ? attr("formaction", value) : self();
  }

  /**
   * Sets the <code>formenctype</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#formenctype">MDN:
   * formenctype</a>
   */
  public InputTag withFormenctype(String value) {
    return attr("formenctype", value);
  }

  /**
   * Applies {@link #withFormenctype(String)} only when {@code condition} is true.
   */
  public InputTag withCondFormenctype(boolean condition, String value) {
    return condition ? attr("formenctype", value) : self();
  }

  /**
   * Sets the <code>formmethod</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#formmethod">MDN:
   * formmethod</a>
   */
  public InputTag withFormmethod(String value) {
    return attr("formmethod", value);
  }

  /**
   * Applies {@link #withFormmethod(String)} only when {@code condition} is true.
   */
  public InputTag withCondFormmethod(boolean condition, String value) {
    return condition ? attr("formmethod", value) : self();
  }

  /**
   * Sets the <code>formnovalidate</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#formnovalidate">MDN:
   * formnovalidate</a>
   */
  public InputTag isFormnovalidate() {
    return attr("formnovalidate");
  }

  /**
   * Applies {@link #isFormnovalidate()} only when {@code condition} is true.
   */
  public InputTag withCondFormnovalidate(boolean condition) {
    return condition ? attr("formnovalidate") : self();
  }

  /**
   * Sets the <code>formtarget</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#formtarget">MDN:
   * formtarget</a>
   */
  public InputTag withFormtarget(String value) {
    return attr("formtarget", value);
  }

  /**
   * Applies {@link #withFormtarget(String)} only when {@code condition} is true.
   */
  public InputTag withCondFormtarget(boolean condition, String value) {
    return condition ? attr("formtarget", value) : self();
  }

  /**
   * Sets the <code>height</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input">MDN:
   * height</a>
   */
  public InputTag withHeight(String value) {
    return attr("height", value);
  }

  /**
   * Applies {@link #withHeight(String)} only when {@code condition} is true.
   */
  public InputTag withCondHeight(boolean condition, String value) {
    return condition ? attr("height", value) : self();
  }

  /**
   * Sets the <code>list</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input">MDN:
   * list</a>
   */
  public InputTag withList(String value) {
    return attr("list", value);
  }

  /**
   * Applies {@link #withList(String)} only when {@code condition} is true.
   */
  public InputTag withCondList(boolean condition, String value) {
    return condition ? attr("list", value) : self();
  }

  /**
   * Sets the <code>max</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/max">MDN: max</a>
   */
  public InputTag withMax(String value) {
    return attr("max", value);
  }

  /**
   * Applies {@link #withMax(String)} only when {@code condition} is true.
   */
  public InputTag withCondMax(boolean condition, String value) {
    return condition ? attr("max", value) : self();
  }

  /**
   * Sets the <code>maxlength</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/maxlength">MDN:
   * maxlength</a>
   */
  public InputTag withMaxlength(String value) {
    return attr("maxlength", value);
  }

  /**
   * Applies {@link #withMaxlength(String)} only when {@code condition} is true.
   */
  public InputTag withCondMaxlength(boolean condition, String value) {
    return condition ? attr("maxlength", value) : self();
  }

  /**
   * Sets the <code>min</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/min">MDN: min</a>
   */
  public InputTag withMin(String value) {
    return attr("min", value);
  }

  /**
   * Applies {@link #withMin(String)} only when {@code condition} is true.
   */
  public InputTag withCondMin(boolean condition, String value) {
    return condition ? attr("min", value) : self();
  }

  /**
   * Sets the <code>minlength</code> attribute.
   *
   * <p>Baseline: widely available since 2020-10-30.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/minlength">MDN:
   * minlength</a>
   */
  public InputTag withMinlength(String value) {
    return attr("minlength", value);
  }

  /**
   * Applies {@link #withMinlength(String)} only when {@code condition} is true.
   */
  public InputTag withCondMinlength(boolean condition, String value) {
    return condition ? attr("minlength", value) : self();
  }

  /**
   * Sets the <code>multiple</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/multiple">MDN:
   * multiple</a>
   */
  public InputTag isMultiple() {
    return attr("multiple");
  }

  /**
   * Applies {@link #isMultiple()} only when {@code condition} is true.
   */
  public InputTag withCondMultiple(boolean condition) {
    return condition ? attr("multiple") : self();
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#name">MDN:
   * name</a>
   */
  public InputTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public InputTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }

  /**
   * Sets the <code>pattern</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/pattern">MDN:
   * pattern</a>
   */
  public InputTag withPattern(String value) {
    return attr("pattern", value);
  }

  /**
   * Applies {@link #withPattern(String)} only when {@code condition} is true.
   */
  public InputTag withCondPattern(boolean condition, String value) {
    return condition ? attr("pattern", value) : self();
  }

  /**
   * Sets the <code>placeholder</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#placeholder">MDN:
   * placeholder</a>
   */
  public InputTag withPlaceholder(String value) {
    return attr("placeholder", value);
  }

  /**
   * Applies {@link #withPlaceholder(String)} only when {@code condition} is true.
   */
  public InputTag withCondPlaceholder(boolean condition, String value) {
    return condition ? attr("placeholder", value) : self();
  }

  /**
   * Sets the <code>popovertarget</code> attribute.
   *
   * <p>Baseline: newly available since 2024-04-16.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#popovertarget">MDN:
   * popovertarget</a>
   */
  public InputTag withPopovertarget(String value) {
    return attr("popovertarget", value);
  }

  /**
   * Applies {@link #withPopovertarget(String)} only when {@code condition} is true.
   */
  public InputTag withCondPopovertarget(boolean condition, String value) {
    return condition ? attr("popovertarget", value) : self();
  }

  /**
   * Sets the <code>popovertargetaction</code> attribute.
   *
   * <p>Baseline: newly available since 2024-04-16.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#popovertargetaction">MDN:
   * popovertargetaction</a>
   */
  public InputTag withPopovertargetaction(String value) {
    return attr("popovertargetaction", value);
  }

  /**
   * Applies {@link #withPopovertargetaction(String)} only when {@code condition} is true.
   */
  public InputTag withCondPopovertargetaction(boolean condition, String value) {
    return condition ? attr("popovertargetaction", value) : self();
  }

  /**
   * Sets the <code>readonly</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/readonly">MDN:
   * readonly</a>
   */
  public InputTag isReadonly() {
    return attr("readonly");
  }

  /**
   * Applies {@link #isReadonly()} only when {@code condition} is true.
   */
  public InputTag withCondReadonly(boolean condition) {
    return condition ? attr("readonly") : self();
  }

  /**
   * Sets the <code>required</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#required">MDN:
   * required</a>
   */
  public InputTag isRequired() {
    return attr("required");
  }

  /**
   * Applies {@link #isRequired()} only when {@code condition} is true.
   */
  public InputTag withCondRequired(boolean condition) {
    return condition ? attr("required") : self();
  }

  /**
   * Sets the <code>size</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/size">MDN:
   * size</a>
   */
  public InputTag withSize(String value) {
    return attr("size", value);
  }

  /**
   * Applies {@link #withSize(String)} only when {@code condition} is true.
   */
  public InputTag withCondSize(boolean condition, String value) {
    return condition ? attr("size", value) : self();
  }

  /**
   * Sets the <code>src</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input#src">MDN:
   * src</a>
   */
  public InputTag withSrc(String value) {
    return attr("src", value);
  }

  /**
   * Applies {@link #withSrc(String)} only when {@code condition} is true.
   */
  public InputTag withCondSrc(boolean condition, String value) {
    return condition ? attr("src", value) : self();
  }

  /**
   * Sets the <code>step</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/step">MDN:
   * step</a>
   */
  public InputTag withStep(String value) {
    return attr("step", value);
  }

  /**
   * Applies {@link #withStep(String)} only when {@code condition} is true.
   */
  public InputTag withCondStep(boolean condition, String value) {
    return condition ? attr("step", value) : self();
  }

  /**
   * Sets the <code>type</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input">MDN:
   * type</a>
   */
  public InputTag withType(String value) {
    return attr("type", value);
  }

  /**
   * Applies {@link #withType(String)} only when {@code condition} is true.
   */
  public InputTag withCondType(boolean condition, String value) {
    return condition ? attr("type", value) : self();
  }

  /**
   * Sets the <code>value</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input">MDN:
   * value</a>
   */
  public InputTag withValue(String value) {
    return attr("value", value);
  }

  /**
   * Applies {@link #withValue(String)} only when {@code condition} is true.
   */
  public InputTag withCondValue(boolean condition, String value) {
    return condition ? attr("value", value) : self();
  }

  /**
   * Sets the <code>width</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/input">MDN:
   * width</a>
   */
  public InputTag withWidth(String value) {
    return attr("width", value);
  }

  /**
   * Applies {@link #withWidth(String)} only when {@code condition} is true.
   */
  public InputTag withCondWidth(boolean condition, String value) {
    return condition ? attr("width", value) : self();
  }
}
