// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;ins&gt;</code> element.
 *
 * <p>The ins element represents an addition to the document.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/ins">MDN:
 * &lt;ins&gt;</a>
 */
public final class InsTag extends ContainerTag<InsTag> {

  public InsTag() {
    super("ins");
  }

  /**
   * Sets the <code>cite</code> attribute.
   *
   * <p>This attribute defines the URI of a resource that explains the change, such as a link to
   * meeting minutes or a ticket in a troubleshooting system.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/ins">MDN: cite</a>
   */
  public InsTag withCite(String value) {
    return attr("cite", value);
  }

  /**
   * Applies {@link #withCite(String)} only when {@code condition} is true.
   */
  public InsTag withCondCite(boolean condition, String value) {
    return condition ? attr("cite", value) : self();
  }

  /**
   * Sets the <code>datetime</code> attribute.
   *
   * <p>This attribute indicates the time and date of the change and must be a valid date with an
   * optional time string. If the value cannot be parsed as a date with an optional time string, the
   * element does not have an associated time stamp. For the format of the string without a time, see
   * [Format of a valid date
   * string](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#Format_of_a_valid_date_string
   * "Certain HTML elements use date and/or time values. The formats of the strings that specify
   * these are described in this article.") in [Date and time formats used in
   * HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats "Certain HTML
   * elements use date and/or time values. The formats of the strings that specify these are
   * described in this article."). The format of the string if it includes both date and time is
   * covered in [Format of a valid local date and time
   * string](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#Format_of_a_valid_local_date_and_time_string
   * "Certain HTML elements use date and/or time values. The formats of the strings that specify
   * these are described in this article.") in [Date and time formats used in
   * HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats "Certain HTML
   * elements use date and/or time values. The formats of the strings that specify these are
   * described in this article.").
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/ins">MDN:
   * datetime</a>
   */
  public InsTag withDatetime(String value) {
    return attr("datetime", value);
  }

  /**
   * Applies {@link #withDatetime(String)} only when {@code condition} is true.
   */
  public InsTag withCondDatetime(boolean condition, String value) {
    return condition ? attr("datetime", value) : self();
  }
}
