// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;label&gt;</code> element.
 *
 * <p>The label element represents a caption in a user interface. The caption can be associated
 * with a specific form control, known as the label element's labeled control, either using the for
 * attribute, or by putting the form control inside the label element itself.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/label">MDN:
 * &lt;label&gt;</a>
 */
public final class LabelTag extends ContainerTag<LabelTag> {

  public LabelTag() {
    super("label");
  }

  /**
   * Sets the <code>form</code> attribute.
   *
   * <p>The
   * [<code>&lt;form&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form "The
   * HTML &lt;form&gt; element represents a document section that contains interactive controls for
   * submitting information to a web server.") element with which the label is associated (its _form
   * owner_). If specified, the value of the attribute is the <code>id</code> of a
   * [<code>&lt;form&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form "The
   * HTML &lt;form&gt; element represents a document section that contains interactive controls for
   * submitting information to a web server.") element in the same document. This lets you place
   * label elements anywhere within a document, not just as descendants of their form elements.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/label">MDN:
   * form</a>
   */
  public LabelTag withForm(String value) {
    return attr("form", value);
  }

  /**
   * Applies {@link #withForm(String)} only when {@code condition} is true.
   */
  public LabelTag withCondForm(boolean condition, String value) {
    return condition ? attr("form", value) : self();
  }

  /**
   * Sets the <code>for</code> attribute.
   *
   * <p>The <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-id"><code>id</code></a>
   * of a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Form_labelable">labelable</a>
   * form-related element in the same document as the <code>&lt;label&gt;</code> element. The first
   * element in the document with an <code>id</code> matching the value of the <code>for</code>
   * attribute is the _labeled control_ for this label element, if it is a labelable element. If it
   * is not labelable then the <code>for</code> attribute has no effect. If there are other elements
   * which also match the <code>id</code> value, later in the document, they are not considered.
   *
   * <p>**Note**: A <code>&lt;label&gt;</code> element can have both a <code>for</code> attribute and
   * a contained control element, as long as the <code>for</code> attribute points to the contained
   * control element.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/for">MDN: for</a>
   */
  public LabelTag withFor(String value) {
    return attr("for", value);
  }

  /**
   * Applies {@link #withFor(String)} only when {@code condition} is true.
   */
  public LabelTag withCondFor(boolean condition, String value) {
    return condition ? attr("for", value) : self();
  }
}
