// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;link&gt;</code> element.
 *
 * <p>The link element allows authors to link their document to other resources.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/link">MDN:
 * &lt;link&gt;</a>
 */
public final class LinkTag extends EmptyTag<LinkTag> {

  public LinkTag() {
    super("link");
  }

  /**
   * Sets the <code>href</code> attribute.
   *
   * <p>This attribute specifies the [URL](https://developer.mozilla.org/en-US/docs/Glossary/URL
   * "URL: Uniform Resource Locator (URL) is a text string specifying where a resource can be found
   * on the Internet.") of the linked resource. A URL can be absolute or relative.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/link">MDN: href</a>
   */
  public LinkTag withHref(String value) {
    return attr("href", value);
  }

  /**
   * Applies {@link #withHref(String)} only when {@code condition} is true.
   */
  public LinkTag withCondHref(boolean condition, String value) {
    return condition ? attr("href", value) : self();
  }

  /**
   * Sets the <code>crossorigin</code> attribute.
   *
   * <p>This enumerated attribute indicates whether
   * [CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS "CORS: CORS (Cross-Origin Resource
   * Sharing) is a system, consisting of transmitting HTTP headers, that determines whether browsers
   * block frontend JavaScript code from accessing responses for cross-origin requests.") must be
   * used when fetching the resource. <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_Enabled_Image">CORS-enabled
   * images</a> can be reused in the
   * [<code>&lt;canvas&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas
   * "Use the HTML &lt;canvas&gt; element with either the canvas scripting API or the WebGL API to
   * draw graphics and animations.") element without being _tainted_. The allowed values are:
   *
   * <p><code>anonymous</code>
   *
   * <p>A cross-origin request (i.e. with an
   * [<code>Origin</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin "The
   * Origin request header indicates where a fetch originates from. It doesn't include any path
   * information, but only the server name. It is sent with CORS requests, as well as with POST
   * requests. It is similar to the Referer header, but, unlike this header, it doesn't disclose the
   * whole path.") HTTP header) is performed, but no credential is sent (i.e. no cookie, X.509
   * certificate, or HTTP Basic authentication). If the server does not give credentials to the
   * origin site (by not setting the
   * [<code>Access-Control-Allow-Origin</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
   * "The Access-Control-Allow-Origin response header indicates whether the response can be shared
   * with requesting code from the given origin.") HTTP header) the image will be tainted and its
   * usage restricted.
   *
   * <p><code>use-credentials</code>
   *
   * <p>A cross-origin request (i.e. with an <code>Origin</code> HTTP header) is performed along with
   * a credential sent (i.e. a cookie, certificate, and/or HTTP Basic authentication is performed).
   * If the server does not give credentials to the origin site (through
   * [<code>Access-Control-Allow-Credentials</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials
   * "The Access-Control-Allow-Credentials response header tells browsers whether to expose the
   * response to frontend JavaScript code when the request's credentials mode (Request.credentials)
   * is "include".") HTTP header), the resource will be _tainted_ and its usage restricted.
   *
   * <p>If the attribute is not present, the resource is fetched without a
   * [CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS "CORS: CORS (Cross-Origin Resource
   * Sharing) is a system, consisting of transmitting HTTP headers, that determines whether browsers
   * block frontend JavaScript code from accessing responses for cross-origin requests.") request
   * (i.e. without sending the <code>Origin</code> HTTP header), preventing its non-tainted usage. If
   * invalid, it is handled as if the enumerated keyword **anonymous** was used. See <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes">CORS settings
   * attributes</a> for additional information.
   *
   * <p>Baseline: widely available since 2020-10-30.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/crossorigin">MDN:
   * crossorigin</a>
   */
  public LinkTag withCrossorigin(String value) {
    return attr("crossorigin", value);
  }

  /**
   * Applies {@link #withCrossorigin(String)} only when {@code condition} is true.
   */
  public LinkTag withCondCrossorigin(boolean condition, String value) {
    return condition ? attr("crossorigin", value) : self();
  }

  /**
   * Sets the <code>rel</code> attribute.
   *
   * <p>This attribute names a relationship of the linked document to the current document. The
   * attribute must be a space-separated list of the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types">link types values</a>.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/rel">MDN: rel</a>
   */
  public LinkTag withRel(String value) {
    return attr("rel", value);
  }

  /**
   * Applies {@link #withRel(String)} only when {@code condition} is true.
   */
  public LinkTag withCondRel(boolean condition, String value) {
    return condition ? attr("rel", value) : self();
  }

  /**
   * Sets the <code>media</code> attribute.
   *
   * <p>This attribute specifies the media that the linked resource applies to. Its value must be a
   * media type / <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/Media_queries">media
   * query</a>. This attribute is mainly useful when linking to external stylesheets — it allows the
   * user agent to pick the best adapted one for the device it runs on.
   *
   * <p>**Notes:**
   *
   * <p>* In HTML 4, this can only be a simple white-space-separated list of media description
   * literals, i.e., <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/&#64;media">media
   * types and groups</a>, where defined and allowed as values for this attribute, such as
   * <code>print</code>, <code>screen</code>, <code>aural</code>, <code>braille</code>. HTML5
   * extended this to any kind of <a
   * href="https://developer.mozilla.org/en-US/docs/Web/CSS/Media_queries">media queries</a>, which
   * are a superset of the allowed values of HTML 4. * Browsers not supporting <a
   * href="https://developer.mozilla.org/en-US/docs/Web/CSS/Media_queries">CSS3 Media Queries</a>
   * won't necessarily recognize the adequate link; do not forget to set fallback links, the
   * restricted set of media queries defined in HTML 4.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/link">MDN:
   * media</a>
   */
  public LinkTag withMedia(String value) {
    return attr("media", value);
  }

  /**
   * Applies {@link #withMedia(String)} only when {@code condition} is true.
   */
  public LinkTag withCondMedia(boolean condition, String value) {
    return condition ? attr("media", value) : self();
  }

  /**
   * Sets the <code>hreflang</code> attribute.
   *
   * <p>This attribute indicates the language of the linked resource. It is purely advisory. Allowed
   * values are determined by <a href="https://www.ietf.org/rfc/bcp/bcp47.txt">BCP47</a>. Use this
   * attribute only if the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-href"><code>href</code></a>
   * attribute is present.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/link">MDN:
   * hreflang</a>
   */
  public LinkTag withHreflang(String value) {
    return attr("hreflang", value);
  }

  /**
   * Applies {@link #withHreflang(String)} only when {@code condition} is true.
   */
  public LinkTag withCondHreflang(boolean condition, String value) {
    return condition ? attr("hreflang", value) : self();
  }

  /**
   * Sets the <code>type</code> attribute.
   *
   * <p>This attribute is used to define the type of the content linked to. The value of the
   * attribute should be a MIME type such as **text/html**, **text/css**, and so on. The common use
   * of this attribute is to define the type of stylesheet being referenced (such as **text/css**),
   * but given that CSS is the only stylesheet language used on the web, not only is it possible to
   * omit the <code>type</code> attribute, but is actually now recommended practice. It is also used
   * on <code>rel="preload"</code> link types, to make sure the browser only downloads file types
   * that it supports.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/link">MDN: type</a>
   */
  public LinkTag withType(String value) {
    return attr("type", value);
  }

  /**
   * Applies {@link #withType(String)} only when {@code condition} is true.
   */
  public LinkTag withCondType(boolean condition, String value) {
    return condition ? attr("type", value) : self();
  }

  /**
   * Sets the <code>sizes</code> attribute.
   *
   * <p>This attribute defines the sizes of the icons for visual media contained in the resource. It
   * must be present only if the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-rel"><code>rel</code></a>
   * contains a value of <code>icon</code> or a non-standard type such as Apple's
   * <code>apple-touch-icon</code>. It may have the following values:
   *
   * <p>* <code>any</code>, meaning that the icon can be scaled to any size as it is in a vector
   * format, like <code>image/svg+xml</code>. * a white-space separated list of sizes, each in the
   * format <code>_&lt;width in pixels&gt;_x_&lt;height in pixels&gt;_</code> or <code>_&lt;width in
   * pixels&gt;_X_&lt;height in pixels&gt;_</code>. Each of these sizes must be contained in the
   * resource.
   *
   * <p>**Note:** Most icon formats are only able to store one single icon; therefore most of the
   * time the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-sizes"><code>sizes</code></a>
   * contains only one entry. MS's ICO format does, as well as Apple's ICNS. ICO is more ubiquitous;
   * you should definitely use it.
   *
   * <p>Baseline: widely available since 2022-07-15.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/link">MDN:
   * sizes</a>
   */
  public LinkTag withSizes(String value) {
    return attr("sizes", value);
  }

  /**
   * Applies {@link #withSizes(String)} only when {@code condition} is true.
   */
  public LinkTag withCondSizes(boolean condition, String value) {
    return condition ? attr("sizes", value) : self();
  }

  /**
   * Sets the <code>as</code> attribute.
   *
   * <p>This attribute is only used when <code>rel="preload"</code> or <code>rel="prefetch"</code>
   * has been set on the <code>&lt;link&gt;</code> element. It specifies the type of content being
   * loaded by the <code>&lt;link&gt;</code>, which is necessary for content prioritization, request
   * matching, application of correct <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP">content security policy</a>, and
   * setting of correct
   * [<code>Accept</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept "The
   * Accept request HTTP header advertises which content types, expressed as MIME types, the client
   * is able to understand. Using content negotiation, the server then selects one of the proposals,
   * uses it and informs the client of its choice with the Content-Type response header. Browsers set
   * adequate values for this header depending on the context where the request is done: when
   * fetching a CSS stylesheet a different value is set for the request than when fetching an
   * image, video or a script.") request header.
   *
   * <p>Baseline: widely available since 2020-10-30.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/link">MDN: as</a>
   */
  public LinkTag withAs(String value) {
    return attr("as", value);
  }

  /**
   * Applies {@link #withAs(String)} only when {@code condition} is true.
   */
  public LinkTag withCondAs(boolean condition, String value) {
    return condition ? attr("as", value) : self();
  }

  /**
   * Sets the <code>importance</code> attribute.
   *
   * <p>Indicates the relative importance of the resource. Priority hints are delegated using the
   * values:
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/link">MDN:
   * importance</a>
   */
  public LinkTag withImportance(String value) {
    return attr("importance", value);
  }

  /**
   * Applies {@link #withImportance(String)} only when {@code condition} is true.
   */
  public LinkTag withCondImportance(boolean condition, String value) {
    return condition ? attr("importance", value) : self();
  }

  /**
   * Sets the <code>integrity</code> attribute.
   *
   * <p>Contains inline metadata — a base64-encoded cryptographic hash of the resource (file) you’re
   * telling the browser to fetch. The browser can use this to verify that the fetched resource has
   * been delivered free of unexpected manipulation. See <a
   * href="https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity">Subresource
   * Integrity</a>.
   *
   * <p>Baseline: widely available since 2020-10-30.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/integrity">MDN:
   * integrity</a>
   */
  public LinkTag withIntegrity(String value) {
    return attr("integrity", value);
  }

  /**
   * Applies {@link #withIntegrity(String)} only when {@code condition} is true.
   */
  public LinkTag withCondIntegrity(boolean condition, String value) {
    return condition ? attr("integrity", value) : self();
  }

  /**
   * Sets the <code>referrerpolicy</code> attribute.
   *
   * <p>A string indicating which referrer to use when fetching the resource:
   *
   * <p>* <code>no-referrer</code> means that the
   * [<code>Referer</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer "The
   * Referer request header contains the address of the previous web page from which a link to the
   * currently requested page was followed. The Referer header allows servers to identify where
   * people are visiting them from and may use that data for analytics, logging, or optimized
   * caching, for example.") header will not be sent. * <code>no-referrer-when-downgrade</code> means
   * that no [<code>Referer</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer
   * "The Referer request header contains the address of the previous web page from which a link to
   * the currently requested page was followed. The Referer header allows servers to identify where
   * people are visiting them from and may use that data for analytics, logging, or optimized
   * caching, for example.") header will be sent when navigating to an origin without TLS (HTTPS).
   * This is a user agent’s default behavior, if no policy is otherwise specified. *
   * <code>origin</code> means that the referrer will be the origin of the page, which is roughly the
   * scheme, the host, and the port. * <code>origin-when-cross-origin</code> means that navigating to
   * other origins will be limited to the scheme, the host, and the port, while navigating on the
   * same origin will include the referrer's path. * <code>unsafe-url</code> means that the referrer
   * will include the origin and the path (but not the fragment, password, or username). This case is
   * unsafe because it can leak origins and paths from TLS-protected resources to insecure origins.
   *
   * <p>Baseline: widely available since 2023-03-16.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/link">MDN:
   * referrerpolicy</a>
   */
  public LinkTag withReferrerpolicy(String value) {
    return attr("referrerpolicy", value);
  }

  /**
   * Applies {@link #withReferrerpolicy(String)} only when {@code condition} is true.
   */
  public LinkTag withCondReferrerpolicy(boolean condition, String value) {
    return condition ? attr("referrerpolicy", value) : self();
  }
}
