// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;li&gt;</code> element.
 *
 * <p>The li element represents a list item. If its parent element is an ol, ul, or menu element,
 * then the element is an item of the parent element's list, as defined for those elements.
 * Otherwise, the list item has no defined list-related relationship to any other li element.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/li">MDN:
 * &lt;li&gt;</a>
 */
public final class LiTag extends ContainerTag<LiTag> {

  public LiTag() {
    super("li");
  }

  /**
   * Sets the <code>value</code> attribute.
   *
   * <p>This integer attribute indicates the current ordinal value of the list item as defined by the
   * [<code>&lt;ol&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol "The HTML
   * &lt;ol&gt; element represents an ordered list of items, typically rendered as a numbered list.")
   * element. The only allowed value for this attribute is a number, even if the list is displayed
   * with Roman numerals or letters. List items that follow this one continue numbering from the
   * value set. The **value** attribute has no meaning for unordered lists
   * ([<code>&lt;ul&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul "The
   * HTML &lt;ul&gt; element represents an unordered list of items, typically rendered as a bulleted
   * list.")) or for menus
   * ([<code>&lt;menu&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu "The
   * HTML &lt;menu&gt; element represents a group of commands that a user can perform or activate.
   * This includes both list menus, which might appear across the top of a screen, as well as context
   * menus, such as those that might appear underneath a button after it has been clicked.")).
   *
   * <p>**Note**: This attribute was deprecated in HTML4, but reintroduced in HTML5.
   *
   * <p>**Note:** Prior to Gecko 9.0, negative values were incorrectly converted to 0. Starting in
   * Gecko 9.0 all integer values are correctly parsed.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/li">MDN: value</a>
   */
  public LiTag withValue(String value) {
    return attr("value", value);
  }

  /**
   * Applies {@link #withValue(String)} only when {@code condition} is true.
   */
  public LiTag withCondValue(boolean condition, String value) {
    return condition ? attr("value", value) : self();
  }

  /**
   * Sets the <code>type</code> attribute.
   *
   * <p>This character attribute indicates the numbering type:
   *
   * <p>* <code>a</code>: lowercase letters * <code>A</code>: uppercase letters * <code>i</code>:
   * lowercase Roman numerals * <code>I</code>: uppercase Roman numerals * <code>1</code>: numbers
   *
   * <p>This type overrides the one used by its parent
   * [<code>&lt;ol&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol "The HTML
   * &lt;ol&gt; element represents an ordered list of items, typically rendered as a numbered list.")
   * element, if any.
   *
   * <p>**Usage note:** This attribute has been deprecated: use the CSS
   * [<code>list-style-type</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type
   * "The list-style-type CSS property sets the marker (such as a disc, character, or custom counter
   * style) of a list item element.") property instead.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/li">MDN: type</a>
   * @deprecated The <code>type</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public LiTag withType(String value) {
    return attr("type", value);
  }

  /**
   * Applies {@link #withType(String)} only when {@code condition} is true.
   */
  @Deprecated
  public LiTag withCondType(boolean condition, String value) {
    return condition ? attr("type", value) : self();
  }
}
