// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;main&gt;</code> element.
 *
 * <p>The main element represents the main content of the body of a document or application. The
 * main content area consists of content that is directly related to or expands upon the central
 * topic of a document or central functionality of an application.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/main">MDN:
 * &lt;main&gt;</a>
 */
public final class MainTag extends ContainerTag<MainTag> {

  public MainTag() {
    super("main");
  }
}
