// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;map&gt;</code> element.
 *
 * <p>The map element, in conjunction with an img element and any area element descendants, defines
 * an image map. The element represents its children.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/map">MDN:
 * &lt;map&gt;</a>
 */
public final class MapTag extends ContainerTag<MapTag> {

  public MapTag() {
    super("map");
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>The name attribute gives the map a name so that it can be referenced. The attribute must be
   * present and must have a non-empty value with no space characters. The value of the name
   * attribute must not be a compatibility-caseless match for the value of the name attribute of
   * another map element in the same document. If the id attribute is also specified, both attributes
   * must have the same value.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/map">MDN: name</a>
   */
  public MapTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public MapTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }
}
