// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;mark&gt;</code> element.
 *
 * <p>The mark element represents a run of text in one document marked or highlighted for reference
 * purposes, due to its relevance in another context. When used in a quotation or other block of
 * text referred to from the prose, it indicates a highlight that was not originally present but
 * which has been added to bring the reader's attention to a part of the text that might not have
 * been considered important by the original author when the block was originally written, but
 * which is now under previously unexpected scrutiny. When used in the main prose of a document, it
 * indicates a part of the document that has been highlighted due to its likely relevance to the
 * user's current activity.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/mark">MDN:
 * &lt;mark&gt;</a>
 */
public final class MarkTag extends ContainerTag<MarkTag> {

  public MarkTag() {
    super("mark");
  }
}
