// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;meta&gt;</code> element.
 *
 * <p>The meta element represents various kinds of metadata that cannot be expressed using the
 * title, base, link, style, and script elements.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/meta">MDN:
 * &lt;meta&gt;</a>
 */
public final class MetaTag extends EmptyTag<MetaTag> {

  public MetaTag() {
    super("meta");
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>This attribute defines the name of a piece of document-level metadata. It should not be set
   * if one of the attributes <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-itemprop"><code>itemprop</code></a>,
   * <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv"><code>http-equiv</code></a>
   * or <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset"><code>charset</code></a>
   * is also set.
   *
   * <p>This metadata name is associated with the value contained by the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-content"><code>content</code></a>
   * attribute. The possible values for the name attribute are:
   *
   * <p>* <code>application-name</code> which defines the name of the application running in the web
   * page.
   *
   * <p>**Note:**
   *
   * <p>* Browsers may use this to identify the application. It is different from the
   * [<code>&lt;title&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title
   * "The HTML Title element (&lt;title&gt;) defines the document's title that is shown in a
   * browser's title bar or a page's tab.") element, which usually contain the application name, but
   * may also contain information like the document name or a status. * Simple web pages shouldn't
   * define an application-name.
   *
   * <p>* <code>author</code> which defines the name of the document's author. *
   * <code>description</code> which contains a short and accurate summary of the content of the page.
   * Several browsers, like Firefox and Opera, use this as the default description of bookmarked
   * pages. * <code>generator</code> which contains the identifier of the software that generated the
   * page. * <code>keywords</code> which contains words relevant to the page's content separated by
   * commas. * <code>referrer</code> which controls the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer"><code>Referer</code>
   * HTTP header</a> attached to requests sent from the document:
   *
   * <p>Values for the <code>content</code> attribute of <code>&lt;meta name="referrer"&gt;</code>
   *
   * <p><code>no-referrer</code>
   *
   * <p>Do not send a HTTP <code>Referrer</code> header.
   *
   * <p><code>origin</code>
   *
   * <p>Send the <a href="https://developer.mozilla.org/en-US/docs/Glossary/Origin">origin</a> of the
   * document.
   *
   * <p><code>no-referrer-when-downgrade</code>
   *
   * <p>Send the <a href="https://developer.mozilla.org/en-US/docs/Glossary/Origin">origin</a> as a
   * referrer to URLs as secure as the current page, (https→https), but does not send a referrer to
   * less secure URLs (https→http). This is the default behaviour.
   *
   * <p><code>origin-when-cross-origin</code>
   *
   * <p>Send the full URL (stripped of parameters) for same-origin requests, but only send the <a
   * href="https://developer.mozilla.org/en-US/docs/Glossary/Origin">origin</a> for other cases.
   *
   * <p><code>same-origin</code>
   *
   * <p>A referrer will be sent for <a
   * href="https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy">same-site
   * origins</a>, but cross-origin requests will contain no referrer information.
   *
   * <p><code>strict-origin</code>
   *
   * <p>Only send the origin of the document as the referrer to a-priori as-much-secure destination
   * (HTTPS-&gt;HTTPS), but don't send it to a less secure destination (HTTPS-&gt;HTTP).
   *
   * <p><code>strict-origin-when-cross-origin</code>
   *
   * <p>Send a full URL when performing a same-origin request, only send the origin of the document
   * to a-priori as-much-secure destination (HTTPS-&gt;HTTPS), and send no header to a less secure
   * destination (HTTPS-&gt;HTTP).
   *
   * <p><code>unsafe-URL</code>
   *
   * <p>Send the full URL (stripped of parameters) for same-origin or cross-origin requests.
   *
   * <p>**Notes:**
   *
   * <p>* Some browsers support the deprecated values of <code>always</code>, <code>default</code>,
   * and <code>never</code> for referrer. * Dynamically inserting <code>&lt;meta
   * name="referrer"&gt;</code> (with <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/Document/write"><code>document.write</code></a>
   * or <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild"><code>appendChild</code></a>)
   * makes the referrer behaviour unpredictable. * When several conflicting policies are defined, the
   * no-referrer policy is applied.
   *
   * <p>This attribute may also have a value taken from the extended list defined on <a
   * href="https://wiki.whatwg.org/wiki/MetaExtensions">WHATWG Wiki MetaExtensions page</a>. Although
   * none have been formally accepted yet, a few commonly used names are:
   *
   * <p>* <code>creator</code> which defines the name of the creator of the document, such as an
   * organization or institution. If there are more than one, several
   * [<code>&lt;meta&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta "The
   * HTML &lt;meta&gt; element represents metadata that cannot be represented by other HTML
   * meta-related elements, like &lt;base&gt;, &lt;link&gt;, &lt;script&gt;, &lt;style&gt; or
   * &lt;title&gt;.") elements should be used. * <code>googlebot</code>, a synonym of
   * <code>robots</code>, is only followed by Googlebot (the indexing crawler for Google). *
   * <code>publisher</code> which defines the name of the document's publisher. * <code>robots</code>
   * which defines the behaviour that cooperative crawlers, or "robots", should use with the page. It
   * is a comma-separated list of the values below:
   *
   * <p>Values for the content of <code>&lt;meta name="robots"&gt;</code>
   *
   * <p>Value
   *
   * <p>Description
   *
   * <p>Used by
   *
   * <p><code>index</code>
   *
   * <p>Allows the robot to index the page (default).
   *
   * <p>All
   *
   * <p><code>noindex</code>
   *
   * <p>Requests the robot to not index the page.
   *
   * <p>All
   *
   * <p><code>follow</code>
   *
   * <p>Allows the robot to follow the links on the page (default).
   *
   * <p>All
   *
   * <p><code>nofollow</code>
   *
   * <p>Requests the robot to not follow the links on the page.
   *
   * <p>All
   *
   * <p><code>none</code>
   *
   * <p>Equivalent to <code>noindex, nofollow</code>
   *
   * <p><a href="https://support.google.com/webmasters/answer/79812">Google</a>
   *
   * <p><code>noodp</code>
   *
   * <p>Prevents using the <a href="https://www.dmoz.org/">Open Directory Project</a> description, if
   * any, as the page description in search engine results.
   *
   * <p><a href="https://support.google.com/webmasters/answer/35624#nodmoz">Google</a>, <a
   * href="https://help.yahoo.com/kb/search-for-desktop/meta-tags-robotstxt-yahoo-search-sln2213.html#cont5">Yahoo</a>,
   * <a
   * href="https://www.bing.com/webmaster/help/which-robots-metatags-does-bing-support-5198d240">Bing</a>
   *
   * <p><code>noarchive</code>
   *
   * <p>Requests the search engine not to cache the page content.
   *
   * <p><a
   * href="https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag#valid-indexing--serving-directives">Google</a>,
   * <a href="https://help.yahoo.com/kb/search-for-desktop/SLN2213.html">Yahoo</a>, <a
   * href="https://www.bing.com/webmaster/help/which-robots-metatags-does-bing-support-5198d240">Bing</a>
   *
   * <p><code>nosnippet</code>
   *
   * <p>Prevents displaying any description of the page in search engine results.
   *
   * <p><a
   * href="https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag#valid-indexing--serving-directives">Google</a>,
   * <a
   * href="https://www.bing.com/webmaster/help/which-robots-metatags-does-bing-support-5198d240">Bing</a>
   *
   * <p><code>noimageindex</code>
   *
   * <p>Requests this page not to appear as the referring page of an indexed image.
   *
   * <p><a
   * href="https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag#valid-indexing--serving-directives">Google</a>
   *
   * <p><code>nocache</code>
   *
   * <p>Synonym of <code>noarchive</code>.
   *
   * <p><a
   * href="https://www.bing.com/webmaster/help/which-robots-metatags-does-bing-support-5198d240">Bing</a>
   *
   * <p>**Notes:**
   *
   * <p>* Only cooperative robots follow these rules. Do not expect to prevent e-mail harvesters with
   * them. * The robot still needs to access the page in order to read these rules. To prevent
   * bandwidth consumption, use a
   * _[robots.txt](https://developer.mozilla.org/en-US/docs/Glossary/robots.txt "robots.txt:
   * Robots.txt is a file which is usually placed in the root of any website. It decides
   * whether crawlers are permitted or forbidden access to the web site.")_ file. * If you want to
   * remove a page, <code>noindex</code> will work, but only after the robot visits the page again.
   * Ensure that the <code>robots.txt</code> file is not preventing revisits. * Some values are
   * mutually exclusive, like <code>index</code> and <code>noindex</code>, or <code>follow</code> and
   * <code>nofollow</code>. In these cases the robot's behaviour is undefined and may vary between
   * them. * Some crawler robots, like Google, Yahoo and Bing, support the same values for the HTTP
   * header <code>X-Robots-Tag</code>; this allows non-HTML documents like images to use these rules.
   *
   * <p>* <code>slurp</code>, is a synonym of <code>robots</code>, but only for Slurp - the crawler
   * for Yahoo Search. * <code>viewport</code>, which gives hints about the size of the initial size
   * of the [viewport](https://developer.mozilla.org/en-US/docs/Glossary/viewport "viewport: A
   * viewport represents a polygonal (normally rectangular) area in computer graphics that is
   * currently being viewed. In web browser terms, it refers to the part of the document you're
   * viewing which is currently visible in its window (or the screen, if the document is being viewed
   * in full screen mode). Content outside the viewport is not visible onscreen until scrolled into
   * view."). Used by mobile devices only.
   *
   * <p>Values for the content of <code>&lt;meta name="viewport"&gt;</code>
   *
   * <p>Value
   *
   * <p>Possible subvalues
   *
   * <p>Description
   *
   * <p><code>width</code>
   *
   * <p>A positive integer number, or the text <code>device-width</code>
   *
   * <p>Defines the pixel width of the viewport that you want the web site to be rendered at.
   *
   * <p><code>height</code>
   *
   * <p>A positive integer, or the text <code>device-height</code>
   *
   * <p>Defines the height of the viewport. Not used by any browser.
   *
   * <p><code>initial-scale</code>
   *
   * <p>A positive number between <code>0.0</code> and <code>10.0</code>
   *
   * <p>Defines the ratio between the device width (<code>device-width</code> in portrait mode or
   * <code>device-height</code> in landscape mode) and the viewport size.
   *
   * <p><code>maximum-scale</code>
   *
   * <p>A positive number between <code>0.0</code> and <code>10.0</code>
   *
   * <p>Defines the maximum amount to zoom in. It must be greater or equal to the
   * <code>minimum-scale</code> or the behaviour is undefined. Browser settings can ignore this rule
   * and iOS10+ ignores it by default.
   *
   * <p><code>minimum-scale</code>
   *
   * <p>A positive number between <code>0.0</code> and <code>10.0</code>
   *
   * <p>Defines the minimum zoom level. It must be smaller or equal to the <code>maximum-scale</code>
   * or the behaviour is undefined. Browser settings can ignore this rule and iOS10+ ignores it by
   * default.
   *
   * <p><code>user-scalable</code>
   *
   * <p><code>yes</code> or <code>no</code>
   *
   * <p>If set to <code>no</code>, the user is not able to zoom in the webpage. The default is
   * <code>yes</code>. Browser settings can ignore this rule, and iOS10+ ignores it by default.
   *
   * <p>Specification
   *
   * <p>Status
   *
   * <p>Comment
   *
   * <p><a href="https://drafts.csswg.org/css-device-adapt/#viewport-meta">CSS Device Adaptation The
   * definition of '&lt;meta name="viewport"&gt;' in that specification.</a>
   *
   * <p>Working Draft
   *
   * <p>Non-normatively describes the Viewport META element
   *
   * <p>See also:
   * [<code>&#64;viewport</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/&#64;viewport "The
   * &#64;viewport CSS at-rule lets you configure the viewport through which the document is viewed.
   * It's primarily used for mobile devices, but is also used by desktop browsers that support
   * features like "snap to edge" (such as Microsoft Edge).")
   *
   * <p>**Notes:**
   *
   * <p>* Though unstandardized, this declaration is respected by most mobile browsers due to
   * de-facto dominance. * The default values may vary between devices and browsers. * To learn about
   * this declaration in Firefox for Mobile, see [this
   * article](https://developer.mozilla.org/en-US/docs/Mobile/Viewport_meta_tag "Mobile/Viewport meta
   * tag").
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/meta/name">MDN:
   * name</a>
   */
  public MetaTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public MetaTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }

  /**
   * Sets the <code>http-equiv</code> attribute.
   *
   * <p>Defines a pragma directive. The attribute is named <code>**http-equiv**(alent)</code> because
   * all the allowed values are names of particular HTTP headers:
   *
   * <p>* <code>"content-language"</code> Defines the default language of the page. It can be
   * overridden by the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang">lang</a>
   * attribute on any element.
   *
   * <p>**Warning:** Do not use this value, as it is obsolete. Prefer the <code>lang</code> attribute
   * on the
   * [<code>&lt;html&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html "The
   * HTML &lt;html&gt; element represents the root (top-level element) of an HTML document, so it is
   * also referred to as the root element. All other elements must be descendants of this element.")
   * element.
   *
   * <p>* <code>"content-security-policy"</code> Allows page authors to define a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives">content
   * policy</a> for the current page. Content policies mostly specify allowed server origins and
   * script endpoints which help guard against cross-site scripting attacks. *
   * <code>"content-type"</code> Defines the <a
   * href="https://developer.mozilla.org/en-US/docs/Glossary/MIME_type">MIME type</a> of the
   * document, followed by its character encoding. It follows the same syntax as the HTTP
   * <code>content-type</code> entity-header field, but as it is inside a HTML page, most values
   * other than <code>text/html</code> are impossible. Therefore the valid syntax for its
   * <code>content</code> is the string '<code>text/html</code>' followed by a character set with the
   * following syntax: '<code>; charset=_IANAcharset_</code>', where <code>IANAcharset</code> is the
   * _preferred MIME name_ for a character set as <a
   * href="https://www.iana.org/assignments/character-sets">defined by the IANA.</a>
   *
   * <p>**Warning:** Do not use this value, as it is obsolete. Use the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset"><code>charset</code></a>
   * attribute on the
   * [<code>&lt;meta&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta "The
   * HTML &lt;meta&gt; element represents metadata that cannot be represented by other HTML
   * meta-related elements, like &lt;base&gt;, &lt;link&gt;, &lt;script&gt;, &lt;style&gt; or
   * &lt;title&gt;.") element.
   *
   * <p>**Note:** As
   * [<code>&lt;meta&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta "The
   * HTML &lt;meta&gt; element represents metadata that cannot be represented by other HTML
   * meta-related elements, like &lt;base&gt;, &lt;link&gt;, &lt;script&gt;, &lt;style&gt; or
   * &lt;title&gt;.") can't change documents' types in XHTML or HTML5's XHTML serialization, never
   * set the MIME type to an XHTML MIME type with <code>&lt;meta&gt;</code>.
   *
   * <p>* <code>"refresh"</code> This instruction specifies: * The number of seconds until the page
   * should be reloaded - only if the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-content"><code>content</code></a>
   * attribute contains a positive integer. * The number of seconds until the page should redirect to
   * another - only if the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-content"><code>content</code></a>
   * attribute contains a positive integer followed by the string '<code>;url=</code>', and a valid
   * URL. * <code>"set-cookie"</code> Defines a <a
   * href="https://developer.mozilla.org/en-US/docs/cookie">cookie</a> for the page. Its content must
   * follow the syntax defined in the <a
   * href="https://tools.ietf.org/html/draft-ietf-httpstate-cookie-14">IETF HTTP Cookie
   * Specification</a>.
   *
   * <p>**Warning:** Do not use this instruction, as it is obsolete. Use the HTTP header <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie"><code>Set-Cookie</code></a>
   * instead.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/meta/http-equiv">MDN:
   * http-equiv</a>
   */
  public MetaTag withHttpEquiv(String value) {
    return attr("http-equiv", value);
  }

  /**
   * Applies {@link #withHttpEquiv(String)} only when {@code condition} is true.
   */
  public MetaTag withCondHttpEquiv(boolean condition, String value) {
    return condition ? attr("http-equiv", value) : self();
  }

  /**
   * Sets the <code>content</code> attribute.
   *
   * <p>This attribute contains the value for the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv"><code>http-equiv</code></a>
   * or <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-name"><code>name</code></a>
   * attribute, depending on which is used.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/content">MDN:
   * content</a>
   */
  public MetaTag withContent(String value) {
    return attr("content", value);
  }

  /**
   * Applies {@link #withContent(String)} only when {@code condition} is true.
   */
  public MetaTag withCondContent(boolean condition, String value) {
    return condition ? attr("content", value) : self();
  }

  /**
   * Sets the <code>charset</code> attribute.
   *
   * <p>This attribute declares the page's character encoding. It must contain a <a
   * href="https://www.iana.org/assignments/character-sets">standard IANA MIME name for character
   * encodings</a>. Although the standard doesn't request a specific encoding, it suggests:
   *
   * <p>* Authors are encouraged to use <a
   * href="https://developer.mozilla.org/en-US/docs/Glossary/UTF-8"><code>UTF-8</code></a>. * Authors
   * should not use ASCII-incompatible encodings to avoid security risk: browsers not supporting them
   * may interpret harmful content as HTML. This happens with the <code>JIS_C6226-1983</code>,
   * <code>JIS_X0212-1990</code>, <code>HZ-GB-2312</code>, <code>JOHAB</code>, the ISO-2022 family
   * and the EBCDIC family.
   *
   * <p>**Note:** ASCII-incompatible encodings are those that don't map the 8-bit code points
   * <code>0x20</code> to <code>0x7E</code> to the <code>0x0020</code> to <code>0x007E</code> Unicode
   * code points)
   *
   * <p>* Authors **must not** use <code>CESU-8</code>, <code>UTF-7</code>, <code>BOCU-1</code>
   * and/or <code>SCSU</code> as <a
   * href="https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting">cross-site
   * scripting</a> attacks with these encodings have been demonstrated. * Authors should not use
   * <code>UTF-32</code> because not all HTML5 encoding algorithms can distinguish it from
   * <code>UTF-16</code>.
   *
   * <p>**Notes:**
   *
   * <p>* The declared character encoding must match the one the page was saved with to avoid garbled
   * characters and security holes. * The
   * [<code>&lt;meta&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta "The
   * HTML &lt;meta&gt; element represents metadata that cannot be represented by other HTML
   * meta-related elements, like &lt;base&gt;, &lt;link&gt;, &lt;script&gt;, &lt;style&gt; or
   * &lt;title&gt;.") element declaring the encoding must be inside the
   * [<code>&lt;head&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head "The
   * HTML &lt;head&gt; element provides general information (metadata) about the document, including
   * its title and links to its scripts and style sheets.") element and **within the first 1024
   * bytes** of the HTML as some browsers only look at those bytes before choosing an encoding. *
   * This [<code>&lt;meta&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
   * "The HTML &lt;meta&gt; element represents metadata that cannot be represented by other HTML
   * meta-related elements, like &lt;base&gt;, &lt;link&gt;, &lt;script&gt;, &lt;style&gt; or
   * &lt;title&gt;.") element is only one part of the [algorithm to determine a page's character
   * set](https://www.whatwg.org/specs/web-apps/current-work/multipage/parsing.html#encoding-sniffing-algorithm
   * "Algorithm charset page"). The <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type"><code>Content-Type</code>
   * header</a> and any [Byte-Order
   * Marks](https://developer.mozilla.org/en-US/docs/Glossary/Byte-Order_Mark "The definition of that
   * term (Byte-Order Marks) has not been written yet; please consider contributing it!") override
   * this element. * It is strongly recommended to define the character encoding. If a page's
   * encoding is undefined, cross-scripting techniques are possible, such as the <a
   * href="https://code.google.com/p/doctype-mirror/wiki/ArticleUtf7"><code>UTF-7</code> fallback
   * cross-scripting technique</a>. * The
   * [<code>&lt;meta&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta "The
   * HTML &lt;meta&gt; element represents metadata that cannot be represented by other HTML
   * meta-related elements, like &lt;base&gt;, &lt;link&gt;, &lt;script&gt;, &lt;style&gt; or
   * &lt;title&gt;.") element with a <code>charset</code> attribute is a synonym for the pre-HTML5
   * <code>&lt;meta http-equiv="Content-Type" content="text/html; charset=_IANAcharset_"&gt;</code>,
   * where _<code>IANAcharset</code>_ contains the value of the equivalent <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset"><code>charset</code></a>
   * attribute. This syntax is still allowed, although no longer recommended.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/meta">MDN:
   * charset</a>
   */
  public MetaTag withCharset(String value) {
    return attr("charset", value);
  }

  /**
   * Applies {@link #withCharset(String)} only when {@code condition} is true.
   */
  public MetaTag withCondCharset(boolean condition, String value) {
    return condition ? attr("charset", value) : self();
  }

  /**
   * Sets the <code>scheme</code> attribute.
   *
   * <p>This attribute defines the scheme in which metadata is described. A scheme is a context
   * leading to the correct interpretations of the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-content"><code>content</code></a>
   * value, like a format.
   *
   * <p>**Warning:** Do not use this value, as it is obsolete. There is no replacement as there was
   * no real usage for it.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/meta">MDN:
   * scheme</a>
   * @deprecated The <code>scheme</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public MetaTag withScheme(String value) {
    return attr("scheme", value);
  }

  /**
   * Applies {@link #withScheme(String)} only when {@code condition} is true.
   */
  @Deprecated
  public MetaTag withCondScheme(boolean condition, String value) {
    return condition ? attr("scheme", value) : self();
  }
}
