// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;object&gt;</code> element.
 *
 * <p>The object element can represent an external resource, which, depending on the type of the
 * resource, will either be treated as an image, as a nested browsing context, or as an external
 * resource to be processed by a plugin.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
 * &lt;object&gt;</a>
 */
public final class ObjectTag extends ContainerTag<ObjectTag> {

  public ObjectTag() {
    super("object");
  }

  /**
   * Sets the <code>data</code> attribute.
   *
   * <p>The address of the resource as a valid URL. At least one of **data** and **type** must be
   * defined.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * data</a>
   */
  public ObjectTag withData(String value) {
    return attr("data", value);
  }

  /**
   * Applies {@link #withData(String)} only when {@code condition} is true.
   */
  public ObjectTag withCondData(boolean condition, String value) {
    return condition ? attr("data", value) : self();
  }

  /**
   * Sets the <code>type</code> attribute.
   *
   * <p>The <a href="https://developer.mozilla.org/en-US/docs/Glossary/Content_type">content type</a>
   * of the resource specified by **data**. At least one of **data** and **type** must be defined.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * type</a>
   */
  public ObjectTag withType(String value) {
    return attr("type", value);
  }

  /**
   * Applies {@link #withType(String)} only when {@code condition} is true.
   */
  public ObjectTag withCondType(boolean condition, String value) {
    return condition ? attr("type", value) : self();
  }

  /**
   * Sets the <code>typemustmatch</code> attribute.
   *
   * <p>This Boolean attribute indicates if the **type** attribute and the actual <a
   * href="https://developer.mozilla.org/en-US/docs/Glossary/Content_type">content type</a> of the
   * resource must match to be used.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * typemustmatch</a>
   */
  public ObjectTag isTypemustmatch() {
    return attr("typemustmatch");
  }

  /**
   * Applies {@link #isTypemustmatch()} only when {@code condition} is true.
   */
  public ObjectTag withCondTypemustmatch(boolean condition) {
    return condition ? attr("typemustmatch") : self();
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>The name of valid browsing context (HTML5), or the name of the control (HTML 4).
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * name</a>
   */
  public ObjectTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public ObjectTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }

  /**
   * Sets the <code>usemap</code> attribute.
   *
   * <p>A hash-name reference to a
   * [<code>&lt;map&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/map "The
   * HTML &lt;map&gt; element is used with &lt;area&gt; elements to define an image map (a clickable
   * link area).") element; that is a '#' followed by the value of a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/map#attr-name"><code>name</code></a>
   * of a map element.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * usemap</a>
   * @deprecated The <code>usemap</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ObjectTag withUsemap(String value) {
    return attr("usemap", value);
  }

  /**
   * Applies {@link #withUsemap(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ObjectTag withCondUsemap(boolean condition, String value) {
    return condition ? attr("usemap", value) : self();
  }

  /**
   * Sets the <code>form</code> attribute.
   *
   * <p>The form element, if any, that the object element is associated with (its _form owner_). The
   * value of the attribute must be an ID of a
   * [<code>&lt;form&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form "The
   * HTML &lt;form&gt; element represents a document section that contains interactive controls for
   * submitting information to a web server.") element in the same document.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/form">MDN:
   * form</a>
   */
  public ObjectTag withForm(String value) {
    return attr("form", value);
  }

  /**
   * Applies {@link #withForm(String)} only when {@code condition} is true.
   */
  public ObjectTag withCondForm(boolean condition, String value) {
    return condition ? attr("form", value) : self();
  }

  /**
   * Sets the <code>width</code> attribute.
   *
   * <p>The width of the display resource, in <a href="https://drafts.csswg.org/css-values/#px">CSS
   * pixels</a>. -- (Absolute values only. <a
   * href="https://html.spec.whatwg.org/multipage/embedded-content.html#dimension-attributes">NO
   * percentages</a>)
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * width</a>
   */
  public ObjectTag withWidth(String value) {
    return attr("width", value);
  }

  /**
   * Applies {@link #withWidth(String)} only when {@code condition} is true.
   */
  public ObjectTag withCondWidth(boolean condition, String value) {
    return condition ? attr("width", value) : self();
  }

  /**
   * Sets the <code>height</code> attribute.
   *
   * <p>The height of the displayed resource, in <a
   * href="https://drafts.csswg.org/css-values/#px">CSS pixels</a>. -- (Absolute values only. <a
   * href="https://html.spec.whatwg.org/multipage/embedded-content.html#dimension-attributes">NO
   * percentages</a>)
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * height</a>
   */
  public ObjectTag withHeight(String value) {
    return attr("height", value);
  }

  /**
   * Applies {@link #withHeight(String)} only when {@code condition} is true.
   */
  public ObjectTag withCondHeight(boolean condition, String value) {
    return condition ? attr("height", value) : self();
  }

  /**
   * Sets the <code>archive</code> attribute.
   *
   * <p>A space-separated list of URIs for archives of resources for the object.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * archive</a>
   * @deprecated The <code>archive</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ObjectTag withArchive(String value) {
    return attr("archive", value);
  }

  /**
   * Applies {@link #withArchive(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ObjectTag withCondArchive(boolean condition, String value) {
    return condition ? attr("archive", value) : self();
  }

  /**
   * Sets the <code>border</code> attribute.
   *
   * <p>The width of a border around the control, in pixels.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * border</a>
   * @deprecated The <code>border</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ObjectTag withBorder(String value) {
    return attr("border", value);
  }

  /**
   * Applies {@link #withBorder(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ObjectTag withCondBorder(boolean condition, String value) {
    return condition ? attr("border", value) : self();
  }

  /**
   * Sets the <code>classid</code> attribute.
   *
   * <p>The URI of the object's implementation. It can be used together with, or in place of, the
   * **data** attribute.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * classid</a>
   * @deprecated The <code>classid</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ObjectTag withClassid(String value) {
    return attr("classid", value);
  }

  /**
   * Applies {@link #withClassid(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ObjectTag withCondClassid(boolean condition, String value) {
    return condition ? attr("classid", value) : self();
  }

  /**
   * Sets the <code>codebase</code> attribute.
   *
   * <p>The base path used to resolve relative URIs specified by **classid**, **data**, or
   * **archive**. If not specified, the default is the base URI of the current document.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * codebase</a>
   * @deprecated The <code>codebase</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ObjectTag withCodebase(String value) {
    return attr("codebase", value);
  }

  /**
   * Applies {@link #withCodebase(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ObjectTag withCondCodebase(boolean condition, String value) {
    return condition ? attr("codebase", value) : self();
  }

  /**
   * Sets the <code>codetype</code> attribute.
   *
   * <p>The content type of the data specified by **classid**.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * codetype</a>
   * @deprecated The <code>codetype</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ObjectTag withCodetype(String value) {
    return attr("codetype", value);
  }

  /**
   * Applies {@link #withCodetype(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ObjectTag withCondCodetype(boolean condition, String value) {
    return condition ? attr("codetype", value) : self();
  }

  /**
   * Sets the <code>declare</code> attribute.
   *
   * <p>The presence of this Boolean attribute makes this element a declaration only. The object must
   * be instantiated by a subsequent <code>&lt;object&gt;</code> element. In HTML5, repeat the
   * &lt;object&gt; element completely each that that the resource is reused.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * declare</a>
   * @deprecated The <code>declare</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ObjectTag withDeclare(String value) {
    return attr("declare", value);
  }

  /**
   * Applies {@link #withDeclare(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ObjectTag withCondDeclare(boolean condition, String value) {
    return condition ? attr("declare", value) : self();
  }

  /**
   * Sets the <code>standby</code> attribute.
   *
   * <p>A message that the browser can show while loading the object's implementation and data.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/object">MDN:
   * standby</a>
   * @deprecated The <code>standby</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ObjectTag withStandby(String value) {
    return attr("standby", value);
  }

  /**
   * Applies {@link #withStandby(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ObjectTag withCondStandby(boolean condition, String value) {
    return condition ? attr("standby", value) : self();
  }
}
