// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;optgroup&gt;</code> element.
 *
 * <p>The optgroup element represents a group of option elements with a common label.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/optgroup">MDN:
 * &lt;optgroup&gt;</a>
 */
public final class OptgroupTag extends ContainerTag<OptgroupTag> {

  public OptgroupTag() {
    super("optgroup");
  }

  /**
   * Sets the <code>disabled</code> attribute.
   *
   * <p>If this Boolean attribute is set, none of the items in this option group is selectable. Often
   * browsers grey out such control and it won't receive any browsing events, like mouse clicks or
   * focus-related ones.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/disabled">MDN:
   * disabled</a>
   */
  public OptgroupTag isDisabled() {
    return attr("disabled");
  }

  /**
   * Applies {@link #isDisabled()} only when {@code condition} is true.
   */
  public OptgroupTag withCondDisabled(boolean condition) {
    return condition ? attr("disabled") : self();
  }

  /**
   * Sets the <code>label</code> attribute.
   *
   * <p>The name of the group of options, which the browser can use when labeling the options in the
   * user interface. This attribute is mandatory if this element is used.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/optgroup">MDN:
   * label</a>
   */
  public OptgroupTag withLabel(String value) {
    return attr("label", value);
  }

  /**
   * Applies {@link #withLabel(String)} only when {@code condition} is true.
   */
  public OptgroupTag withCondLabel(boolean condition, String value) {
    return condition ? attr("label", value) : self();
  }
}
