// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;output&gt;</code> element.
 *
 * <p>The output element represents the result of a calculation performed by the application, or
 * the result of a user action.
 *
 * <p>Baseline: widely available since ≤2021-04-02.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/output">MDN:
 * &lt;output&gt;</a>
 */
public final class OutputTag extends ContainerTag<OutputTag> {

  public OutputTag() {
    super("output");
  }

  /**
   * Sets the <code>for</code> attribute.
   *
   * <p>A space-separated list of other elements’ <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id"><code>id</code></a>s,
   * indicating that those elements contributed input values to (or otherwise affected) the
   * calculation.
   *
   * <p>Baseline: widely available since ≤2021-04-02.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/for">MDN: for</a>
   */
  public OutputTag withFor(String value) {
    return attr("for", value);
  }

  /**
   * Applies {@link #withFor(String)} only when {@code condition} is true.
   */
  public OutputTag withCondFor(boolean condition, String value) {
    return condition ? attr("for", value) : self();
  }

  /**
   * Sets the <code>form</code> attribute.
   *
   * <p>The <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form">form element</a>
   * that this element is associated with (its "form owner"). The value of the attribute must be an
   * <code>id</code> of a form element in the same document. If this attribute is not specified, the
   * output element must be a descendant of a form element. This attribute enables you to place
   * output elements anywhere within a document, not just as descendants of their form elements.
   *
   * <p>Baseline: widely available since ≤2021-04-02.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/form">MDN:
   * form</a>
   */
  public OutputTag withForm(String value) {
    return attr("form", value);
  }

  /**
   * Applies {@link #withForm(String)} only when {@code condition} is true.
   */
  public OutputTag withCondForm(boolean condition, String value) {
    return condition ? attr("form", value) : self();
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>The name of the element, exposed in the
   * [<code>HTMLFormElement</code>](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement
   * "The HTMLFormElement interface represents a &lt;form&gt; element in the DOM; it allows access to
   * and in some cases modification of aspects of the form, as well as access to its component
   * elements.") API.
   *
   * <p>Baseline: widely available since ≤2021-04-02.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/output">MDN:
   * name</a>
   */
  public OutputTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public OutputTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }
}
