// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;param&gt;</code> element.
 *
 * <p>The param element defines parameters for plugins invoked by object elements. It does not
 * represent anything on its own.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/param">MDN:
 * &lt;param&gt;</a>
 * @deprecated The <code>&lt;param&gt;</code> element is marked deprecated in MDN
 * browser-compat-data; avoid in new markup.
 */
@Deprecated
public final class ParamTag extends EmptyTag<ParamTag> {

  public ParamTag() {
    super("param");
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>Name of the parameter.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/param">MDN:
   * name</a>
   * @deprecated The <code>name</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ParamTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ParamTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }

  /**
   * Sets the <code>value</code> attribute.
   *
   * <p>Specifies the value of the parameter.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/param">MDN:
   * value</a>
   * @deprecated The <code>value</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ParamTag withValue(String value) {
    return attr("value", value);
  }

  /**
   * Applies {@link #withValue(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ParamTag withCondValue(boolean condition, String value) {
    return condition ? attr("value", value) : self();
  }

  /**
   * Sets the <code>type</code> attribute.
   *
   * <p>Only used if the <code>valuetype</code> is set to "ref". Specifies the MIME type of values
   * found at the URI specified by value.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/param">MDN:
   * type</a>
   * @deprecated The <code>type</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ParamTag withType(String value) {
    return attr("type", value);
  }

  /**
   * Applies {@link #withType(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ParamTag withCondType(boolean condition, String value) {
    return condition ? attr("type", value) : self();
  }

  /**
   * Sets the <code>valuetype</code> attribute.
   *
   * <p>Specifies the type of the <code>value</code> attribute. Possible values are:
   *
   * <p>* data: Default value. The value is passed to the object's implementation as a string. * ref:
   * The value is a URI to a resource where run-time values are stored. * object: An ID of another
   * [<code>&lt;object&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object
   * "The HTML &lt;object&gt; element represents an external resource, which can be treated as an
   * image, a nested browsing context, or a resource to be handled by a plugin.") in the same
   * document.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/param">MDN:
   * valuetype</a>
   * @deprecated The <code>valuetype</code> attribute is marked deprecated in MDN
   * browser-compat-data; avoid in new markup.
   */
  @Deprecated
  public ParamTag withValuetype(String value) {
    return attr("valuetype", value);
  }

  /**
   * Applies {@link #withValuetype(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ParamTag withCondValuetype(boolean condition, String value) {
    return condition ? attr("valuetype", value) : self();
  }
}
