// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;picture&gt;</code> element.
 *
 * <p>The picture element is a container which provides multiple sources to its contained img
 * element to allow authors to declaratively control or give hints to the user agent about which
 * image resource to use, based on the screen pixel density, viewport size, image format, and other
 * factors. It represents its children.
 *
 * <p>Baseline: widely available since 2018-09-21.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/picture">MDN:
 * &lt;picture&gt;</a>
 */
public final class PictureTag extends ContainerTag<PictureTag> {

  public PictureTag() {
    super("picture");
  }
}
