// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;pre&gt;</code> element.
 *
 * <p>The pre element represents a block of preformatted text, in which structure is represented by
 * typographic conventions rather than by elements.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/pre">MDN:
 * &lt;pre&gt;</a>
 */
public final class PreTag extends ContainerTag<PreTag> {

  public PreTag() {
    super("pre");
  }

  /**
   * Sets the <code>cols</code> attribute.
   *
   * <p>Contains the _preferred_ count of characters that a line should have. It was a non-standard
   * synonym of <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre#attr-width"><code>width</code></a>.
   * To achieve such an effect, use CSS
   * [<code>width</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/width "The width CSS
   * property sets an element's width. By default it sets the width of the content area, but if
   * box-sizing is set to border-box, it sets the width of the border area.") instead.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/pre">MDN: cols</a>
   */
  public PreTag withCols(String value) {
    return attr("cols", value);
  }

  /**
   * Applies {@link #withCols(String)} only when {@code condition} is true.
   */
  public PreTag withCondCols(boolean condition, String value) {
    return condition ? attr("cols", value) : self();
  }

  /**
   * Sets the <code>width</code> attribute.
   *
   * <p>Contains the _preferred_ count of characters that a line should have. Though technically
   * still implemented, this attribute has no visual effect; to achieve such an effect, use CSS
   * [<code>width</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/width "The width CSS
   * property sets an element's width. By default it sets the width of the content area, but if
   * box-sizing is set to border-box, it sets the width of the border area.") instead.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/pre">MDN: width</a>
   * @deprecated The <code>width</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public PreTag withWidth(String value) {
    return attr("width", value);
  }

  /**
   * Applies {@link #withWidth(String)} only when {@code condition} is true.
   */
  @Deprecated
  public PreTag withCondWidth(boolean condition, String value) {
    return condition ? attr("width", value) : self();
  }

  /**
   * Sets the <code>wrap</code> attribute.
   *
   * <p>Is a _hint_ indicating how the overflow must happen. In modern browser this hint is ignored
   * and no visual effect results in its present; to achieve such an effect, use CSS
   * [<code>white-space</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space "The
   * white-space CSS property sets how white space inside an element is handled.") instead.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/pre">MDN: wrap</a>
   */
  public PreTag withWrap(String value) {
    return attr("wrap", value);
  }

  /**
   * Applies {@link #withWrap(String)} only when {@code condition} is true.
   */
  public PreTag withCondWrap(boolean condition, String value) {
    return condition ? attr("wrap", value) : self();
  }
}
