// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;progress&gt;</code> element.
 *
 * <p>The progress element represents the completion progress of a task. The progress is either
 * indeterminate, indicating that progress is being made but that it is not clear how much more
 * work remains to be done before the task is complete (e.g. because the task is waiting for a
 * remote host to respond), or the progress is a number in the range zero to a maximum, giving the
 * fraction of work that has so far been completed.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/progress">MDN:
 * &lt;progress&gt;</a>
 */
public final class ProgressTag extends ContainerTag<ProgressTag> {

  public ProgressTag() {
    super("progress");
  }

  /**
   * Sets the <code>value</code> attribute.
   *
   * <p>This attribute specifies how much of the task that has been completed. It must be a valid
   * floating point number between 0 and <code>max</code>, or between 0 and 1 if <code>max</code> is
   * omitted. If there is no <code>value</code> attribute, the progress bar is indeterminate; this
   * indicates that an activity is ongoing with no indication of how long it is expected to take.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/progress">MDN:
   * value</a>
   */
  public ProgressTag withValue(String value) {
    return attr("value", value);
  }

  /**
   * Applies {@link #withValue(String)} only when {@code condition} is true.
   */
  public ProgressTag withCondValue(boolean condition, String value) {
    return condition ? attr("value", value) : self();
  }

  /**
   * Sets the <code>max</code> attribute.
   *
   * <p>This attribute describes how much work the task indicated by the <code>progress</code>
   * element requires. The <code>max</code> attribute, if present, must have a value greater than
   * zero and be a valid floating point number. The default value is 1.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/max">MDN: max</a>
   */
  public ProgressTag withMax(String value) {
    return attr("max", value);
  }

  /**
   * Applies {@link #withMax(String)} only when {@code condition} is true.
   */
  public ProgressTag withCondMax(boolean condition, String value) {
    return condition ? attr("max", value) : self();
  }
}
