// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;rb&gt;</code> element.
 *
 * <p>The rb element marks the base text component of a ruby annotation. When it is the child of a
 * ruby element, it doesn't represent anything itself, but its parent ruby element uses it as part
 * of determining what it represents.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/rb">MDN:
 * &lt;rb&gt;</a>
 * @deprecated The <code>&lt;rb&gt;</code> element is marked deprecated in MDN browser-compat-data;
 * avoid in new markup.
 */
@Deprecated
public final class RbTag extends ContainerTag<RbTag> {

  public RbTag() {
    super("rb");
  }
}
