// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;rp&gt;</code> element.
 *
 * <p>The rp element is used to provide fallback text to be shown by user agents that don't support
 * ruby annotations. One widespread convention is to provide parentheses around the ruby text
 * component of a ruby annotation.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/rp">MDN:
 * &lt;rp&gt;</a>
 */
public final class RpTag extends ContainerTag<RpTag> {

  public RpTag() {
    super("rp");
  }
}
