// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;samp&gt;</code> element.
 *
 * <p>The samp element represents sample or quoted output from another program or computing system.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/samp">MDN:
 * &lt;samp&gt;</a>
 */
public final class SampTag extends ContainerTag<SampTag> {

  public SampTag() {
    super("samp");
  }
}
