// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;script&gt;</code> element.
 *
 * <p>The script element allows authors to include dynamic script and data blocks in their
 * documents. The element does not represent content for the user.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/script">MDN:
 * &lt;script&gt;</a>
 */
public final class ScriptTag extends ContainerTag<ScriptTag> {

  public ScriptTag() {
    super("script");
  }

  /**
   * Sets the <code>src</code> attribute.
   *
   * <p>This attribute specifies the URI of an external script; this can be used as an alternative to
   * embedding a script directly within a document.
   *
   * <p>If a <code>script</code> element has a <code>src</code> attribute specified, it should not
   * have a script embedded inside its tags.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/script">MDN:
   * src</a>
   */
  public ScriptTag withSrc(String value) {
    return attr("src", value);
  }

  /**
   * Applies {@link #withSrc(String)} only when {@code condition} is true.
   */
  public ScriptTag withCondSrc(boolean condition, String value) {
    return condition ? attr("src", value) : self();
  }

  /**
   * Sets the <code>type</code> attribute.
   *
   * <p>This attribute indicates the type of script represented. The value of this attribute will be
   * in one of the following categories:
   *
   * <p>* **Omitted or a JavaScript MIME type:** For HTML5-compliant browsers this indicates the
   * script is JavaScript. HTML5 specification urges authors to omit the attribute rather than
   * provide a redundant MIME type. In earlier browsers, this identified the scripting language of
   * the embedded or imported (via the <code>src</code> attribute) code. JavaScript MIME types are <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#JavaScript_types">listed
   * in the specification</a>. * **<code>module</code>:** For HTML5-compliant browsers the code is
   * treated as a JavaScript module. The processing of the script contents is not affected by the
   * <code>charset</code> and <code>defer</code> attributes. For information on using
   * <code>module</code>, see <a href="https://hacks.mozilla.org/2015/08/es6-in-depth-modules/">ES6
   * in Depth: Modules</a>. Code may behave differently when the <code>module</code> keyword is used.
   * * **Any other value:** The embedded content is treated as a data block which won't be processed
   * by the browser. Developers must use a valid MIME type that is not a JavaScript MIME type to
   * denote data blocks. The <code>src</code> attribute will be ignored.
   *
   * <p>**Note:** in Firefox you could specify the version of JavaScript contained in a
   * <code>&lt;script&gt;</code> element by including a non-standard <code>version</code> parameter
   * inside the <code>type</code> attribute — for example
   * <code>type="text/javascript;version=1.8"</code>. This has been removed in Firefox 59 (see
   * [bug 1428745](https://bugzilla.mozilla.org/show_bug.cgi?id=1428745 "FIXED: Remove support for
   * version parameter from script loader")).
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/script/type">MDN:
   * type</a>
   */
  public ScriptTag withType(String value) {
    return attr("type", value);
  }

  /**
   * Applies {@link #withType(String)} only when {@code condition} is true.
   */
  public ScriptTag withCondType(boolean condition, String value) {
    return condition ? attr("type", value) : self();
  }

  /**
   * Sets the <code>charset</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/script">MDN:
   * charset</a>
   */
  public ScriptTag withCharset(String value) {
    return attr("charset", value);
  }

  /**
   * Applies {@link #withCharset(String)} only when {@code condition} is true.
   */
  public ScriptTag withCondCharset(boolean condition, String value) {
    return condition ? attr("charset", value) : self();
  }

  /**
   * Sets the <code>async</code> attribute.
   *
   * <p>This is a Boolean attribute indicating that the browser should, if possible, load the script
   * asynchronously.
   *
   * <p>This attribute must not be used if the <code>src</code> attribute is absent (i.e. for inline
   * scripts). If it is included in this case it will have no effect.
   *
   * <p>Browsers usually assume the worst case scenario and load scripts synchronously, (i.e.
   * <code>async="false"</code>) during HTML parsing.
   *
   * <p>Dynamically inserted scripts (using
   * [<code>document.createElement()</code>](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement
   * "In an HTML document, the document.createElement() method creates the HTML element specified by
   * tagName, or an HTMLUnknownElement if tagName isn't recognized.")) load asynchronously by
   * default, so to turn on synchronous loading (i.e. scripts load in the order they were inserted)
   * set <code>async="false"</code>.
   *
   * <p>See <a href="#Browser_compatibility">Browser compatibility</a> for notes on browser support.
   * See also <a href="https://developer.mozilla.org/en-US/docs/Games/Techniques/Async_scripts">Async
   * scripts for asm.js</a>.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/script">MDN:
   * async</a>
   */
  public ScriptTag isAsync() {
    return attr("async");
  }

  /**
   * Applies {@link #isAsync()} only when {@code condition} is true.
   */
  public ScriptTag withCondAsync(boolean condition) {
    return condition ? attr("async") : self();
  }

  /**
   * Sets the <code>defer</code> attribute.
   *
   * <p>This Boolean attribute is set to indicate to a browser that the script is meant to be
   * executed after the document has been parsed, but before firing
   * [<code>DOMContentLoaded</code>](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded
   * "/en-US/docs/Web/Events/DOMContentLoaded").
   *
   * <p>Scripts with the <code>defer</code> attribute will prevent the <code>DOMContentLoaded</code>
   * event from firing until the script has loaded and finished evaluating.
   *
   * <p>This attribute must not be used if the <code>src</code> attribute is absent (i.e. for inline
   * scripts), in this case it would have no effect.
   *
   * <p>To achieve a similar effect for dynamically inserted scripts use <code>async="false"</code>
   * instead. Scripts with the <code>defer</code> attribute will execute in the order in which they
   * appear in the document.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/script">MDN:
   * defer</a>
   */
  public ScriptTag isDefer() {
    return attr("defer");
  }

  /**
   * Applies {@link #isDefer()} only when {@code condition} is true.
   */
  public ScriptTag withCondDefer(boolean condition) {
    return condition ? attr("defer") : self();
  }

  /**
   * Sets the <code>crossorigin</code> attribute.
   *
   * <p>Normal <code>script</code> elements pass minimal information to the
   * [<code>window.onerror</code>](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror
   * "The onerror property of the GlobalEventHandlers mixin is an EventHandler that processes error
   * events.") for scripts which do not pass the standard
   * [CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS "CORS: CORS (Cross-Origin Resource
   * Sharing) is a system, consisting of transmitting HTTP headers, that determines whether browsers
   * block frontend JavaScript code from accessing responses for cross-origin requests.") checks. To
   * allow error logging for sites which use a separate domain for static media, use this attribute.
   * See <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes">CORS
   * settings attributes</a> for a more descriptive explanation of its valid arguments.
   *
   * <p>Baseline: widely available since 2019-02-02.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/crossorigin">MDN:
   * crossorigin</a>
   */
  public ScriptTag withCrossorigin(String value) {
    return attr("crossorigin", value);
  }

  /**
   * Applies {@link #withCrossorigin(String)} only when {@code condition} is true.
   */
  public ScriptTag withCondCrossorigin(boolean condition, String value) {
    return condition ? attr("crossorigin", value) : self();
  }

  /**
   * Sets the <code>integrity</code> attribute.
   *
   * <p>This attribute contains inline metadata that a user agent can use to verify that a fetched
   * resource has been delivered free of unexpected manipulation. See <a
   * href="https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity">Subresource
   * Integrity</a>.
   *
   * <p>Baseline: widely available since 2020-10-30.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/integrity">MDN:
   * integrity</a>
   */
  public ScriptTag withIntegrity(String value) {
    return attr("integrity", value);
  }

  /**
   * Applies {@link #withIntegrity(String)} only when {@code condition} is true.
   */
  public ScriptTag withCondIntegrity(boolean condition, String value) {
    return condition ? attr("integrity", value) : self();
  }

  /**
   * Sets the <code>nomodule</code> attribute.
   *
   * <p>This Boolean attribute is set to indicate that the script should not be executed in browsers
   * that support <a href="https://hacks.mozilla.org/2015/08/es6-in-depth-modules/">ES2015
   * modules</a> — in effect, this can be used to serve fallback scripts to older browsers that do
   * not support modular JavaScript code.
   *
   * <p>Baseline: widely available since 2020-11-09.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/script">MDN:
   * nomodule</a>
   */
  public ScriptTag withNomodule(String value) {
    return attr("nomodule", value);
  }

  /**
   * Applies {@link #withNomodule(String)} only when {@code condition} is true.
   */
  public ScriptTag withCondNomodule(boolean condition, String value) {
    return condition ? attr("nomodule", value) : self();
  }

  /**
   * Sets the <code>referrerpolicy</code> attribute.
   *
   * <p>Indicates which <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer">referrer</a> to send
   * when fetching the script, or resources fetched by the script:
   *
   * <p>* <code>no-referrer</code>: The
   * [<code>Referer</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer "The
   * Referer request header contains the address of the previous web page from which a link to the
   * currently requested page was followed. The Referer header allows servers to identify where
   * people are visiting them from and may use that data for analytics, logging, or optimized
   * caching, for example.") header will not be sent. * <code>no-referrer-when-downgrade</code>
   * (default): The
   * [<code>Referer</code>](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer "The
   * Referer request header contains the address of the previous web page from which a link to the
   * currently requested page was followed. The Referer header allows servers to identify where
   * people are visiting them from and may use that data for analytics, logging, or optimized
   * caching, for example.") header will not be sent to
   * [origin](https://developer.mozilla.org/en-US/docs/Glossary/origin "origin: Web content's origin
   * is defined by the scheme (protocol), host (domain), and port of the URL used to access it. Two
   * objects have the same origin only when the scheme, host, and port all match.")s without
   * [TLS](https://developer.mozilla.org/en-US/docs/Glossary/TLS "TLS: Transport Layer Security
   * (TLS), previously known as Secure Sockets Layer (SSL), is a protocol used by applications to
   * communicate securely across a network, preventing tampering with and eavesdropping on email, web
   * browsing, messaging, and other protocols.")
   * ([HTTPS](https://developer.mozilla.org/en-US/docs/Glossary/HTTPS "HTTPS: HTTPS (HTTP Secure) is
   * an encrypted version of the HTTP protocol. It usually uses SSL or TLS to encrypt all
   * communication between a client and a server. This secure connection allows clients to safely
   * exchange sensitive data with a server, for example for banking activities or online
   * shopping.")). * <code>origin</code>: The sent referrer will be limited to the origin of the
   * referring page: its <a
   * href="https://developer.mozilla.org/en-US/docs/Archive/Mozilla/URIScheme">scheme</a>,
   * [host](https://developer.mozilla.org/en-US/docs/Glossary/host "host: A host is a device
   * connected to the Internet (or a local network). Some hosts called servers offer additional
   * services like serving webpages or storing files and emails."), and
   * [port](https://developer.mozilla.org/en-US/docs/Glossary/port "port: For a computer connected to
   * a network with an IP address, a port is a communication endpoint. Ports are designated by
   * numbers, and below 1024 each port is associated by default with a specific protocol."). *
   * <code>origin-when-cross-origin</code>: The referrer sent to other origins will be limited to the
   * scheme, the host, and the port. Navigations on the same origin will still include the path. *
   * <code>same-origin</code>: A referrer will be sent for [same
   * origin](https://developer.mozilla.org/en-US/docs/Glossary/Same-origin_policy "same origin: The
   * same-origin policy is a critical security mechanism that restricts how a document or script
   * loaded from one origin can interact with a resource from another origin."), but cross-origin
   * requests will contain no referrer information. * <code>strict-origin</code>: Only send the
   * origin of the document as the referrer when the protocol security level stays the same (e.g.
   * HTTPS→HTTPS), but don't send it to a less secure destination (e.g. HTTPS→HTTP). *
   * <code>strict-origin-when-cross-origin</code>: Send a full URL when performing a same-origin
   * request, but only send the origin when the protocol security level stays the same
   * (e.g.HTTPS→HTTPS), and send no header to a less secure destination (e.g. HTTPS→HTTP). *
   * <code>unsafe-url</code>: The referrer will include the origin _and_ the path (but not the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/hash">fragment</a>,
   * <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/password">password</a>,
   * or <a
   * href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/username">username</a>).
   * **This value is unsafe**, because it leaks origins and paths from TLS-protected resources to
   * insecure origins.
   *
   * <p>**Note**: An empty string value (<code>""</code>) is both the default value, and a fallback
   * value if <code>referrerpolicy</code> is not supported. If <code>referrerpolicy</code> is not
   * explicitly specified on the <code>&lt;script&gt;</code> element, it will adopt a higher-level
   * referrer policy, i.e. one set on the whole document or domain. If a higher-level policy is not
   * available, the empty string is treated as being equivalent to
   * <code>no-referrer-when-downgrade</code>.
   *
   * <p>Baseline: widely available since 2023-03-16.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/script">MDN:
   * referrerpolicy</a>
   */
  public ScriptTag withReferrerpolicy(String value) {
    return attr("referrerpolicy", value);
  }

  /**
   * Applies {@link #withReferrerpolicy(String)} only when {@code condition} is true.
   */
  public ScriptTag withCondReferrerpolicy(boolean condition, String value) {
    return condition ? attr("referrerpolicy", value) : self();
  }
}
