// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;section&gt;</code> element.
 *
 * <p>The section element represents a generic section of a document or application. A section, in
 * this context, is a thematic grouping of content. Each section should be identified, typically by
 * including a heading ( h1- h6 element) as a child of the section element.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/section">MDN:
 * &lt;section&gt;</a>
 */
public final class SectionTag extends ContainerTag<SectionTag> {

  public SectionTag() {
    super("section");
  }
}
