// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;select&gt;</code> element.
 *
 * <p>The select element represents a control for selecting amongst a set of options.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/select">MDN:
 * &lt;select&gt;</a>
 */
public final class SelectTag extends ContainerTag<SelectTag> {

  public SelectTag() {
    super("select");
  }

  /**
   * Sets the <code>autocomplete</code> attribute.
   *
   * <p>A [<code>DOMString</code>](https://developer.mozilla.org/en-US/docs/Web/API/DOMString
   * "DOMString is a UTF-16 String. As JavaScript already uses such strings, DOMString is mapped
   * directly to a String.") providing a hint for a [user
   * agent's](https://developer.mozilla.org/en-US/docs/Glossary/user_agent "user agent's: A user
   * agent is a computer program representing a person, for example, a browser in a Web context.")
   * autocomplete feature. See <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete">The HTML
   * autocomplete attribute</a> for a complete list of values and details on how to use autocomplete.
   *
   * <p>Baseline: widely available since 2022-07-15.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/select#autocomplete">MDN:
   * autocomplete</a>
   */
  public SelectTag withAutocomplete(String value) {
    return attr("autocomplete", value);
  }

  /**
   * Applies {@link #withAutocomplete(String)} only when {@code condition} is true.
   */
  public SelectTag withCondAutocomplete(boolean condition, String value) {
    return condition ? attr("autocomplete", value) : self();
  }

  /**
   * Sets the <code>disabled</code> attribute.
   *
   * <p>This Boolean attribute indicates that the user cannot interact with the control. If this
   * attribute is not specified, the control inherits its setting from the containing element, for
   * example <code>fieldset</code>; if there is no containing element with the <code>disabled</code>
   * attribute set, then the control is enabled.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/disabled">MDN:
   * disabled</a>
   */
  public SelectTag isDisabled() {
    return attr("disabled");
  }

  /**
   * Applies {@link #isDisabled()} when {@code condition} is true and removes the attribute
   * otherwise, so a form control stays controlled either way (ADR 0013).
   */
  public SelectTag withCondDisabled(boolean condition) {
    return condition ? attr("disabled") : attr("disabled", null);
  }

  /**
   * Sets the <code>form</code> attribute.
   *
   * <p>This attribute lets you specify the form element to which the select element is
   * associated (that is, its "form owner"). If this attribute is specified, its value must be the
   * same as the <code>id</code> of a form element in the same document. This enables you to place
   * select elements anywhere within a document, not just as descendants of their form elements.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/form">MDN:
   * form</a>
   */
  public SelectTag withForm(String value) {
    return attr("form", value);
  }

  /**
   * Applies {@link #withForm(String)} only when {@code condition} is true.
   */
  public SelectTag withCondForm(boolean condition, String value) {
    return condition ? attr("form", value) : self();
  }

  /**
   * Sets the <code>multiple</code> attribute.
   *
   * <p>This Boolean attribute indicates that multiple options can be selected in the list. If it is
   * not specified, then only one option can be selected at a time. When <code>multiple</code> is
   * specified, most browsers will show a scrolling list box instead of a single line dropdown.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/multiple">MDN:
   * multiple</a>
   */
  public SelectTag isMultiple() {
    return attr("multiple");
  }

  /**
   * Applies {@link #isMultiple()} when {@code condition} is true and removes the attribute
   * otherwise, so a form control stays controlled either way (ADR 0013).
   */
  public SelectTag withCondMultiple(boolean condition) {
    return condition ? attr("multiple") : attr("multiple", null);
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>This attribute is used to specify the name of the control.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/select">MDN:
   * name</a>
   */
  public SelectTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public SelectTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }

  /**
   * Sets the <code>required</code> attribute.
   *
   * <p>A Boolean attribute indicating that an option with a non-empty string value must be selected.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/required">MDN:
   * required</a>
   */
  public SelectTag isRequired() {
    return attr("required");
  }

  /**
   * Applies {@link #isRequired()} when {@code condition} is true and removes the attribute
   * otherwise, so a form control stays controlled either way (ADR 0013).
   */
  public SelectTag withCondRequired(boolean condition) {
    return condition ? attr("required") : attr("required", null);
  }

  /**
   * Sets the <code>size</code> attribute.
   *
   * <p>If the control is presented as a scrolling list box (e.g. when <code>multiple</code> is
   * specified), this attribute represents the number of rows in the list that should be visible at
   * one time. Browsers are not required to present a select element as a scrolled list box. The
   * default value is 0.
   *
   * <p>**Note:** According to the HTML5 specification, the default value for size should be 1;
   * however, in practice, this has been found to break some web sites, and no other browser
   * currently does that, so Mozilla has opted to continue to return 0 for the time being with
   * Firefox.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/size">MDN:
   * size</a>
   */
  public SelectTag withSize(String value) {
    return attr("size", value);
  }

  /**
   * Applies {@link #withSize(String)} only when {@code condition} is true.
   */
  public SelectTag withCondSize(boolean condition, String value) {
    return condition ? attr("size", value) : self();
  }
}
