// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;selectedcontent&gt;</code> element.
 *
 * <p>The selectedcontent element can be used to display the content of the currently selected
 * option element inside of a closed select element.
 *
 * <p>Limited availability: not yet supported in all major browsers.
 *
 * @see <a
 * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/selectedcontent">MDN:
 * &lt;selectedcontent&gt;</a>
 */
public final class SelectedcontentTag extends ContainerTag<SelectedcontentTag> {

  public SelectedcontentTag() {
    super("selectedcontent");
  }
}
