// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;slot&gt;</code> element.
 *
 * <p>The slot element is a placeholder inside a web component that you can fill with your own
 * markup, which lets you create separate DOM trees and present them together.
 *
 * <p>Baseline: widely available since 2022-07-15.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/slot">MDN:
 * &lt;slot&gt;</a>
 */
public final class SlotTag extends ContainerTag<SlotTag> {

  public SlotTag() {
    super("slot");
  }

  /**
   * Sets the <code>name</code> attribute.
   *
   * <p>The slot's name. A **named slot** is a <code>&lt;slot&gt;</code> element with a
   * <code>name</code> attribute.
   *
   * <p>Baseline: widely available since 2022-07-15.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/slot">MDN: name</a>
   */
  public SlotTag withName(String value) {
    return attr("name", value);
  }

  /**
   * Applies {@link #withName(String)} only when {@code condition} is true.
   */
  public SlotTag withCondName(boolean condition, String value) {
    return condition ? attr("name", value) : self();
  }
}
