// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;span&gt;</code> element.
 *
 * <p>The span element doesn't mean anything on its own, but can be useful when used together with
 * the global attributes, e.g. class, lang, or dir. It represents its children.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/span">MDN:
 * &lt;span&gt;</a>
 */
public final class SpanTag extends ContainerTag<SpanTag> {

  public SpanTag() {
    super("span");
  }
}
