// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;style&gt;</code> element.
 *
 * <p>The style element allows authors to embed style information in their documents. The style
 * element is one of several inputs to the styling processing model. The element does not represent
 * content for the user.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/style">MDN:
 * &lt;style&gt;</a>
 */
public final class StyleTag extends ContainerTag<StyleTag> {

  public StyleTag() {
    super("style");
  }

  /**
   * Sets the <code>media</code> attribute.
   *
   * <p>This attribute defines which media the style should be applied to. Its value is a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Media_queries">media query</a>,
   * which defaults to <code>all</code> if the attribute is missing.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/style">MDN:
   * media</a>
   */
  public StyleTag withMedia(String value) {
    return attr("media", value);
  }

  /**
   * Applies {@link #withMedia(String)} only when {@code condition} is true.
   */
  public StyleTag withCondMedia(boolean condition, String value) {
    return condition ? attr("media", value) : self();
  }

  /**
   * Sets the <code>type</code> attribute.
   *
   * <p>This attribute defines the styling language as a MIME type (charset should not be specified).
   * This attribute is optional and defaults to <code>text/css</code> if it is not specified — there
   * is very little reason to include this in modern web documents.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/style">MDN:
   * type</a>
   * @deprecated The <code>type</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public StyleTag withType(String value) {
    return attr("type", value);
  }

  /**
   * Applies {@link #withType(String)} only when {@code condition} is true.
   */
  @Deprecated
  public StyleTag withCondType(boolean condition, String value) {
    return condition ? attr("type", value) : self();
  }

  /**
   * Sets the <code>scoped</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/style">MDN:
   * scoped</a>
   */
  public StyleTag isScoped() {
    return attr("scoped");
  }

  /**
   * Applies {@link #isScoped()} when {@code condition} is true and removes the attribute otherwise,
   * so a form control stays controlled either way (ADR 0013).
   */
  public StyleTag withCondScoped(boolean condition) {
    return condition ? attr("scoped") : attr("scoped", null);
  }
}
