// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;summary&gt;</code> element.
 *
 * <p>The summary element represents a summary, caption, or legend for the rest of the contents of
 * the summary element's parent details element, if any.
 *
 * <p>Baseline: widely available since 2022-07-15.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/summary">MDN:
 * &lt;summary&gt;</a>
 */
public final class SummaryTag extends ContainerTag<SummaryTag> {

  public SummaryTag() {
    super("summary");
  }
}
