// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;sup&gt;</code> element.
 *
 * <p>The sup element represents a superscript.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/sup">MDN:
 * &lt;sup&gt;</a>
 */
public final class SupTag extends ContainerTag<SupTag> {

  public SupTag() {
    super("sup");
  }
}
