// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;table&gt;</code> element.
 *
 * <p>The table element represents data with more than one dimension, in the form of a table.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/table">MDN:
 * &lt;table&gt;</a>
 */
public final class TableTag extends ContainerTag<TableTag> {

  public TableTag() {
    super("table");
  }

  /**
   * Sets the <code>border</code> attribute.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/table">MDN:
   * border</a>
   * @deprecated The <code>border</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public TableTag withBorder(String value) {
    return attr("border", value);
  }

  /**
   * Applies {@link #withBorder(String)} only when {@code condition} is true.
   */
  @Deprecated
  public TableTag withCondBorder(boolean condition, String value) {
    return condition ? attr("border", value) : self();
  }

  /**
   * Sets the <code>align</code> attribute.
   *
   * <p>This enumerated attribute indicates how the table must be aligned inside the containing
   * document. It may have the following values:
   *
   * <p>* left: the table is displayed on the left side of the document; * center: the table is
   * displayed in the center of the document; * right: the table is displayed on the right side of
   * the document.
   *
   * <p>**Usage Note**
   *
   * <p>* **Do not use this attribute**, as it has been deprecated. The
   * [<code>&lt;table&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table
   * "The HTML &lt;table&gt; element represents tabular data — that is, information presented in a
   * two-dimensional table comprised of rows and columns of cells containing data.") element should
   * be styled using <a href="https://developer.mozilla.org/en-US/docs/CSS">CSS</a>. Set
   * [<code>margin-left</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-left "The
   * margin-left CSS property sets the margin area on the left side of an element. A positive value
   * places it farther from its neighbors, while a negative value places it closer.") and
   * [<code>margin-right</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-right "The
   * margin-right CSS property sets the margin area on the right side of an element. A positive value
   * places it farther from its neighbors, while a negative value places it closer.") to
   * <code>auto</code> or
   * [<code>margin</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/margin "The margin CSS
   * property sets the margin area on all four sides of an element. It is a shorthand for margin-top,
   * margin-right, margin-bottom, and margin-left.") to <code>0 auto</code> to achieve an effect that
   * is similar to the align attribute. * Prior to Firefox 4, Firefox also supported the
   * <code>middle</code>, <code>absmiddle</code>, and <code>abscenter</code> values as synonyms of
   * <code>center</code>, in quirks mode only.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/table">MDN:
   * align</a>
   * @deprecated The <code>align</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public TableTag withAlign(String value) {
    return attr("align", value);
  }

  /**
   * Applies {@link #withAlign(String)} only when {@code condition} is true.
   */
  @Deprecated
  public TableTag withCondAlign(boolean condition, String value) {
    return condition ? attr("align", value) : self();
  }
}
