// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;template&gt;</code> element.
 *
 * <p>The template element is used to declare fragments of HTML that can be cloned and inserted in
 * the document by script.
 *
 * <p>Baseline: widely available since 2018-05-12.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/template">MDN:
 * &lt;template&gt;</a>
 */
public final class TemplateTag extends ContainerTag<TemplateTag> {

  public TemplateTag() {
    super("template");
  }
}
