// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;tfoot&gt;</code> element.
 *
 * <p>The tfoot element represents the block of rows that consist of the column summaries (footers)
 * for the parent table element, if the tfoot element has a parent and it is a table.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/tfoot">MDN:
 * &lt;tfoot&gt;</a>
 */
public final class TfootTag extends ContainerTag<TfootTag> {

  public TfootTag() {
    super("tfoot");
  }

  /**
   * Sets the <code>align</code> attribute.
   *
   * <p>This enumerated attribute specifies how horizontal alignment of each cell content will be
   * handled. Possible values are:
   *
   * <p>* <code>left</code>, aligning the content to the left of the cell * <code>center</code>,
   * centering the content in the cell * <code>right</code>, aligning the content to the right of the
   * cell * <code>justify</code>, inserting spaces into the textual content so that the content is
   * justified in the cell * <code>char</code>, aligning the textual content on a special character
   * with a minimal offset, defined by the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody#attr-char"><code>char</code></a>
   * and <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody#attr-charoff"><code>charoff</code></a>
   * attributes Unimplemented (see [bug 2212](https://bugzilla.mozilla.org/show_bug.cgi?id=2212
   * "character alignment not implemented (align=char, charoff=, text-align:&lt;string&gt;)")).
   *
   * <p>If this attribute is not set, the <code>left</code> value is assumed.
   *
   * <p>**Note:** Do not use this attribute as it is obsolete (not supported) in the latest standard.
   *
   * <p>* To achieve the same effect as the <code>left</code>, <code>center</code>,
   * <code>right</code> or <code>justify</code> values, use the CSS
   * [<code>text-align</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align "The
   * text-align CSS property sets the horizontal alignment of an inline or table-cell box. This means
   * it works like vertical-align but in the horizontal direction.") property on it. * To achieve the
   * same effect as the <code>char</code> value, in CSS3, you can use the value of the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot#attr-char"><code>char</code></a>
   * as the value of the
   * [<code>text-align</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align "The
   * text-align CSS property sets the horizontal alignment of an inline or table-cell box. This means
   * it works like vertical-align but in the horizontal direction.") property Unimplemented.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/tfoot">MDN:
   * align</a>
   * @deprecated The <code>align</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public TfootTag withAlign(String value) {
    return attr("align", value);
  }

  /**
   * Applies {@link #withAlign(String)} only when {@code condition} is true.
   */
  @Deprecated
  public TfootTag withCondAlign(boolean condition, String value) {
    return condition ? attr("align", value) : self();
  }
}
