// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;th&gt;</code> element.
 *
 * <p>The th element represents a header cell in a table.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN:
 * &lt;th&gt;</a>
 */
public final class ThTag extends ContainerTag<ThTag> {

  public ThTag() {
    super("th");
  }

  /**
   * Sets the <code>colspan</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN:
   * colspan</a>
   */
  public ThTag withColspan(String value) {
    return attr("colspan", value);
  }

  /**
   * Applies {@link #withColspan(String)} only when {@code condition} is true.
   */
  public ThTag withCondColspan(boolean condition, String value) {
    return condition ? attr("colspan", value) : self();
  }

  /**
   * Sets the <code>rowspan</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN:
   * rowspan</a>
   */
  public ThTag withRowspan(String value) {
    return attr("rowspan", value);
  }

  /**
   * Applies {@link #withRowspan(String)} only when {@code condition} is true.
   */
  public ThTag withCondRowspan(boolean condition, String value) {
    return condition ? attr("rowspan", value) : self();
  }

  /**
   * Sets the <code>headers</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN:
   * headers</a>
   */
  public ThTag withHeaders(String value) {
    return attr("headers", value);
  }

  /**
   * Applies {@link #withHeaders(String)} only when {@code condition} is true.
   */
  public ThTag withCondHeaders(boolean condition, String value) {
    return condition ? attr("headers", value) : self();
  }

  /**
   * Sets the <code>scope</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN: scope</a>
   */
  public ThTag withScope(String value) {
    return attr("scope", value);
  }

  /**
   * Applies {@link #withScope(String)} only when {@code condition} is true.
   */
  public ThTag withCondScope(boolean condition, String value) {
    return condition ? attr("scope", value) : self();
  }

  /**
   * Sets the <code>sorted</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN: sorted</a>
   */
  public ThTag withSorted(String value) {
    return attr("sorted", value);
  }

  /**
   * Applies {@link #withSorted(String)} only when {@code condition} is true.
   */
  public ThTag withCondSorted(boolean condition, String value) {
    return condition ? attr("sorted", value) : self();
  }

  /**
   * Sets the <code>abbr</code> attribute.
   *
   * <p>This attribute contains a short abbreviated description of the cell's content. Some
   * user-agents, such as speech readers, may present this description before the content itself.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN: abbr</a>
   */
  public ThTag withAbbr(String value) {
    return attr("abbr", value);
  }

  /**
   * Applies {@link #withAbbr(String)} only when {@code condition} is true.
   */
  public ThTag withCondAbbr(boolean condition, String value) {
    return condition ? attr("abbr", value) : self();
  }

  /**
   * Sets the <code>align</code> attribute.
   *
   * <p>This enumerated attribute specifies how the cell content's horizontal alignment will be
   * handled. Possible values are:
   *
   * <p>* <code>left</code>: The content is aligned to the left of the cell. * <code>center</code>:
   * The content is centered in the cell. * <code>right</code>: The content is aligned to the right
   * of the cell. * <code>justify</code> (with text only): The content is stretched out inside the
   * cell so that it covers its entire width. * <code>char</code> (with text only): The content is
   * aligned to a character inside the <code>&lt;th&gt;</code> element with minimal offset. This
   * character is defined by the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-char"><code>char</code></a>
   * and <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-charoff"><code>charoff</code></a>
   * attributes.
   *
   * <p>The default value when this attribute is not specified is <code>left</code>.
   *
   * <p>**Note:** Do not use this attribute as it is obsolete in the latest standard.
   *
   * <p>* To achieve the same effect as the <code>left</code>, <code>center</code>,
   * <code>right</code> or <code>justify</code> values, apply the CSS
   * [<code>text-align</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align "The
   * text-align CSS property sets the horizontal alignment of an inline or table-cell box. This means
   * it works like vertical-align but in the horizontal direction.") property to the element. * To
   * achieve the same effect as the <code>char</code> value, give the
   * [<code>text-align</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align "The
   * text-align CSS property sets the horizontal alignment of an inline or table-cell box. This means
   * it works like vertical-align but in the horizontal direction.") property the same value you
   * would use for the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-char"><code>char</code></a>.
   * Unimplemented in CSS3.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN: align</a>
   * @deprecated The <code>align</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ThTag withAlign(String value) {
    return attr("align", value);
  }

  /**
   * Applies {@link #withAlign(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ThTag withCondAlign(boolean condition, String value) {
    return condition ? attr("align", value) : self();
  }

  /**
   * Sets the <code>axis</code> attribute.
   *
   * <p>This attribute contains a list of space-separated strings. Each string is the <code>id</code>
   * of a group of cells that this header applies to.
   *
   * <p>**Note:** Do not use this attribute as it is obsolete in the latest standard: use the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-scope"><code>scope</code></a>
   * attribute instead.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN: axis</a>
   * @deprecated The <code>axis</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ThTag withAxis(String value) {
    return attr("axis", value);
  }

  /**
   * Applies {@link #withAxis(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ThTag withCondAxis(boolean condition, String value) {
    return condition ? attr("axis", value) : self();
  }

  /**
   * Sets the <code>bgcolor</code> attribute.
   *
   * <p>This attribute defines the background color of each cell in a column. It consists of a
   * 6-digit hexadecimal code as defined in <a href="https://www.w3.org/Graphics/Color/sRGB">sRGB</a>
   * and is prefixed by '#'. This attribute may be used with one of sixteen predefined color strings:
   *
   * <p> 
   *
   * <p><code>black</code> = "#000000"
   *
   * <p> 
   *
   * <p><code>green</code> = "#008000"
   *
   * <p> 
   *
   * <p><code>silver</code> = "#C0C0C0"
   *
   * <p> 
   *
   * <p><code>lime</code> = "#00FF00"
   *
   * <p> 
   *
   * <p><code>gray</code> = "#808080"
   *
   * <p> 
   *
   * <p><code>olive</code> = "#808000"
   *
   * <p> 
   *
   * <p><code>white</code> = "#FFFFFF"
   *
   * <p> 
   *
   * <p><code>yellow</code> = "#FFFF00"
   *
   * <p> 
   *
   * <p><code>maroon</code> = "#800000"
   *
   * <p> 
   *
   * <p><code>navy</code> = "#000080"
   *
   * <p> 
   *
   * <p><code>red</code> = "#FF0000"
   *
   * <p> 
   *
   * <p><code>blue</code> = "#0000FF"
   *
   * <p> 
   *
   * <p><code>purple</code> = "#800080"
   *
   * <p> 
   *
   * <p><code>teal</code> = "#008080"
   *
   * <p> 
   *
   * <p><code>fuchsia</code> = "#FF00FF"
   *
   * <p> 
   *
   * <p><code>aqua</code> = "#00FFFF"
   *
   * <p>**Note:** Do not use this attribute, as it is non-standard and only implemented in some
   * versions of Microsoft Internet Explorer: The
   * [<code>&lt;th&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th "The HTML
   * &lt;th&gt; element defines a cell as header of a group of table cells. The exact nature of this
   * group is defined by the scope and headers attributes.") element should be styled using <a
   * href="https://developer.mozilla.org/en-US/docs/Web/CSS">CSS</a>. To create a similar effect use
   * the
   * [<code>background-color</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color
   * "The background-color CSS property sets the background color of an element.") property in <a
   * href="https://developer.mozilla.org/en-US/docs/Web/CSS">CSS</a> instead.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/th">MDN:
   * bgcolor</a>
   * @deprecated The <code>bgcolor</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public ThTag withBgcolor(String value) {
    return attr("bgcolor", value);
  }

  /**
   * Applies {@link #withBgcolor(String)} only when {@code condition} is true.
   */
  @Deprecated
  public ThTag withCondBgcolor(boolean condition, String value) {
    return condition ? attr("bgcolor", value) : self();
  }
}
