// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;title&gt;</code> element.
 *
 * <p>The title element represents the document's title or name. Authors should use titles that
 * identify their documents even when they are used out of context, for example in a user's history
 * or bookmarks, or in search results. The document's title is often different from its first
 * heading, since the first heading does not have to stand alone when taken out of context.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/title">MDN:
 * &lt;title&gt;</a>
 */
public final class TitleTag extends ContainerTag<TitleTag> {

  public TitleTag() {
    super("title");
  }
}
