// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;track&gt;</code> element.
 *
 * <p>The track element allows authors to specify explicit external timed text tracks for media
 * elements. It does not represent anything on its own.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/track">MDN:
 * &lt;track&gt;</a>
 */
public final class TrackTag extends EmptyTag<TrackTag> {

  public TrackTag() {
    super("track");
  }

  /**
   * Sets the <code>default</code> attribute.
   *
   * <p>This attribute indicates that the track should be enabled unless the user's preferences
   * indicate that another track is more appropriate. This may only be used on one <code>track</code>
   * element per media element.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/track">MDN:
   * default</a>
   */
  public TrackTag isDefault() {
    return attr("default");
  }

  /**
   * Applies {@link #isDefault()} when {@code condition} is true and removes the attribute otherwise,
   * so a form control stays controlled either way (ADR 0013).
   */
  public TrackTag withCondDefault(boolean condition) {
    return condition ? attr("default") : attr("default", null);
  }

  /**
   * Sets the <code>kind</code> attribute.
   *
   * <p>How the text track is meant to be used. If omitted the default kind is
   * <code>subtitles</code>. If the attribute is not present, it will use the <code>subtitles</code>.
   * If the attribute contains an invalid value, it will use <code>metadata</code>. (Versions of
   * Chrome earlier than 52 treated an invalid value as <code>subtitles</code>.) The following
   * keywords are allowed:
   *
   * <p>* <code>subtitles</code> * Subtitles provide translation of content that cannot be understood
   * by the viewer. For example dialogue or text that is not English in an English language film. *
   * Subtitles may contain additional content, usually extra background information. For example the
   * text at the beginning of the Star Wars films, or the date, time, and location of a scene. *
   * <code>captions</code> * Closed captions provide a transcription and possibly a translation of
   * audio. * It may include important non-verbal information such as music cues or sound effects. It
   * may indicate the cue's source (e.g. music, text, character). * Suitable for users who are deaf
   * or when the sound is muted. * <code>descriptions</code> * Textual description of the video
   * content. * Suitable for users who are blind or where the video cannot be seen. *
   * <code>chapters</code> * Chapter titles are intended to be used when the user is navigating the
   * media resource. * <code>metadata</code> * Tracks used by scripts. Not visible to the user.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/track">MDN:
   * kind</a>
   */
  public TrackTag withKind(String value) {
    return attr("kind", value);
  }

  /**
   * Applies {@link #withKind(String)} only when {@code condition} is true.
   */
  public TrackTag withCondKind(boolean condition, String value) {
    return condition ? attr("kind", value) : self();
  }

  /**
   * Sets the <code>label</code> attribute.
   *
   * <p>A user-readable title of the text track which is used by the browser when listing available
   * text tracks.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/track">MDN:
   * label</a>
   */
  public TrackTag withLabel(String value) {
    return attr("label", value);
  }

  /**
   * Applies {@link #withLabel(String)} only when {@code condition} is true.
   */
  public TrackTag withCondLabel(boolean condition, String value) {
    return condition ? attr("label", value) : self();
  }

  /**
   * Sets the <code>src</code> attribute.
   *
   * <p>Address of the track (<code>.vtt</code> file). Must be a valid URL. This attribute must be
   * specified and its URL value must have the same origin as the document — unless the
   * [<code>&lt;audio&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
   * "The HTML &lt;audio&gt; element is used to embed sound content in documents. It may contain one
   * or more audio sources, represented using the src attribute or the &lt;source&gt; element: the
   * browser will choose the most suitable one. It can also be the destination for streamed media,
   * using a MediaStream.") or
   * [<code>&lt;video&gt;</code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
   * "The HTML Video element (&lt;video&gt;) embeds a media player which supports video playback into
   * the document.") parent element of the <code>track</code> element has a <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes"><code>crossorigin</code></a>
   * attribute.
   *
   * <p>Baseline: widely available since 2019-05-15.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/track">MDN: src</a>
   */
  public TrackTag withSrc(String value) {
    return attr("src", value);
  }

  /**
   * Applies {@link #withSrc(String)} only when {@code condition} is true.
   */
  public TrackTag withCondSrc(boolean condition, String value) {
    return condition ? attr("src", value) : self();
  }

  /**
   * Sets the <code>srclang</code> attribute.
   *
   * <p>Language of the track text data. It must be a valid <a
   * href="https://r12a.github.io/app-subtags/">BCP 47</a> language tag. If the <code>kind</code>
   * attribute is set to <code>subtitles,</code> then <code>srclang</code> must be defined.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/track">MDN:
   * srclang</a>
   */
  public TrackTag withSrclang(String value) {
    return attr("srclang", value);
  }

  /**
   * Applies {@link #withSrclang(String)} only when {@code condition} is true.
   */
  public TrackTag withCondSrclang(boolean condition, String value) {
    return condition ? attr("srclang", value) : self();
  }
}
