// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;tr&gt;</code> element.
 *
 * <p>The tr element represents a row of cells in a table.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/tr">MDN:
 * &lt;tr&gt;</a>
 */
public final class TrTag extends ContainerTag<TrTag> {

  public TrTag() {
    super("tr");
  }

  /**
   * Sets the <code>align</code> attribute.
   *
   * <p>A [<code>DOMString</code>](https://developer.mozilla.org/en-US/docs/Web/API/DOMString
   * "DOMString is a UTF-16 String. As JavaScript already uses such strings, DOMString is mapped
   * directly to a String.") which specifies how the cell's context should be aligned horizontally
   * within the cells in the row; this is shorthand for using <code>align</code> on every cell in the
   * row individually. Possible values are:
   *
   * <p><code>left</code>
   *
   * <p>Align the content of each cell at its left edge.
   *
   * <p><code>center</code>
   *
   * <p>Center the contents of each cell between their left and right edges.
   *
   * <p><code>right</code>
   *
   * <p>Align the content of each cell at its right edge.
   *
   * <p><code>justify</code>
   *
   * <p>Widen whitespaces within the text of each cell so that the text fills the full width of each
   * cell (full justification).
   *
   * <p><code>char</code>
   *
   * <p>Align each cell in the row on a specific character (such that each row in the column that is
   * configured this way will horizontally align its cells on that character). This uses the <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr#attr-char"><code>char</code></a>
   * and <a
   * href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr#attr-charoff"><code>charoff</code></a>
   * to establish the alignment character (typically "." or "," when aligning numerical data) and the
   * number of characters that should follow the alignment character. This alignment type was never
   * widely supported.
   *
   * <p>If no value is expressly set for <code>align</code>, the parent node's value is inherited.
   *
   * <p>Instead of using the obsolete <code>align</code> attribute, you should instead use the CSS
   * [<code>text-align</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align "The
   * text-align CSS property sets the horizontal alignment of an inline or table-cell box. This means
   * it works like vertical-align but in the horizontal direction.") property to establish
   * <code>left</code>, <code>center</code>, <code>right</code>, or <code>justify</code> alignment
   * for the row's cells. To apply character-based alignment, set the CSS
   * [<code>text-align</code>](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align "The
   * text-align CSS property sets the horizontal alignment of an inline or table-cell box. This means
   * it works like vertical-align but in the horizontal direction.") property to the alignment
   * character (such as <code>"."</code> or <code>","</code>).
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/tr">MDN: align</a>
   * @deprecated The <code>align</code> attribute is marked deprecated in MDN browser-compat-data;
   * avoid in new markup.
   */
  @Deprecated
  public TrTag withAlign(String value) {
    return attr("align", value);
  }

  /**
   * Applies {@link #withAlign(String)} only when {@code condition} is true.
   */
  @Deprecated
  public TrTag withCondAlign(boolean condition, String value) {
    return condition ? attr("align", value) : self();
  }
}
