// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;var&gt;</code> element.
 *
 * <p>The var element represents a variable. This could be an actual variable in a mathematical
 * expression or programming context, an identifier representing a constant, a symbol identifying a
 * physical quantity, a function parameter, or just be a term used as a placeholder in prose.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/var">MDN:
 * &lt;var&gt;</a>
 */
public final class VarTag extends ContainerTag<VarTag> {

  public VarTag() {
    super("var");
  }
}
