// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.ContainerTag;

/**
 * The <code>&lt;video&gt;</code> element.
 *
 * <p>A video element is used for playing videos or movies, and audio files with captions.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
 * &lt;video&gt;</a>
 */
public final class VideoTag extends ContainerTag<VideoTag> {

  public VideoTag() {
    super("video");
  }

  /**
   * Sets the <code>src</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN: src</a>
   */
  public VideoTag withSrc(String value) {
    return attr("src", value);
  }

  /**
   * Applies {@link #withSrc(String)} only when {@code condition} is true.
   */
  public VideoTag withCondSrc(boolean condition, String value) {
    return condition ? attr("src", value) : self();
  }

  /**
   * Sets the <code>crossorigin</code> attribute.
   *
   * <p>Baseline: widely available since 2023-01-28.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/crossorigin">MDN:
   * crossorigin</a>
   */
  public VideoTag withCrossorigin(String value) {
    return attr("crossorigin", value);
  }

  /**
   * Applies {@link #withCrossorigin(String)} only when {@code condition} is true.
   */
  public VideoTag withCondCrossorigin(boolean condition, String value) {
    return condition ? attr("crossorigin", value) : self();
  }

  /**
   * Sets the <code>poster</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
   * poster</a>
   */
  public VideoTag withPoster(String value) {
    return attr("poster", value);
  }

  /**
   * Applies {@link #withPoster(String)} only when {@code condition} is true.
   */
  public VideoTag withCondPoster(boolean condition, String value) {
    return condition ? attr("poster", value) : self();
  }

  /**
   * Sets the <code>preload</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
   * preload</a>
   */
  public VideoTag withPreload(String value) {
    return attr("preload", value);
  }

  /**
   * Applies {@link #withPreload(String)} only when {@code condition} is true.
   */
  public VideoTag withCondPreload(boolean condition, String value) {
    return condition ? attr("preload", value) : self();
  }

  /**
   * Sets the <code>autoplay</code> attribute.
   *
   * <p>A Boolean attribute; if specified, the video automatically begins to play back as soon as it
   * can do so without stopping to finish loading the data. **Note**: Sites that automatically play
   * audio (or video with an audio track) can be an unpleasant experience for users, so it should be
   * avoided when possible. If you must offer autoplay functionality, you should make it opt-in
   * (requiring a user to specifically enable it). However, this can be useful when creating media
   * elements whose source will be set at a later time, under user control.
   *
   * <p>To disable video autoplay, <code>autoplay="false"</code> will not work; the video will
   * autoplay if the attribute is there in the <code>&lt;video&gt;</code> tag at all. To remove
   * autoplay the attribute needs to be removed altogether.
   *
   * <p>In some browsers (e.g. Chrome 70.0) autoplay is not working if no <code>muted</code>
   * attribute is present.
   *
   * <p>Baseline: widely available since 2019-03-13.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
   * autoplay</a>
   */
  public VideoTag isAutoplay() {
    return attr("autoplay");
  }

  /**
   * Applies {@link #isAutoplay()} when {@code condition} is true and removes the attribute
   * otherwise, so a form control stays controlled either way (ADR 0013).
   */
  public VideoTag withCondAutoplay(boolean condition) {
    return condition ? attr("autoplay") : attr("autoplay", null);
  }

  /**
   * Sets the <code>mediagroup</code> attribute.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
   * mediagroup</a>
   */
  public VideoTag withMediagroup(String value) {
    return attr("mediagroup", value);
  }

  /**
   * Applies {@link #withMediagroup(String)} only when {@code condition} is true.
   */
  public VideoTag withCondMediagroup(boolean condition, String value) {
    return condition ? attr("mediagroup", value) : self();
  }

  /**
   * Sets the <code>loop</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
   * loop</a>
   */
  public VideoTag isLoop() {
    return attr("loop");
  }

  /**
   * Applies {@link #isLoop()} when {@code condition} is true and removes the attribute otherwise, so
   * a form control stays controlled either way (ADR 0013).
   */
  public VideoTag withCondLoop(boolean condition) {
    return condition ? attr("loop") : attr("loop", null);
  }

  /**
   * Sets the <code>muted</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
   * muted</a>
   */
  public VideoTag isMuted() {
    return attr("muted");
  }

  /**
   * Applies {@link #isMuted()} when {@code condition} is true and removes the attribute otherwise,
   * so a form control stays controlled either way (ADR 0013).
   */
  public VideoTag withCondMuted(boolean condition) {
    return condition ? attr("muted") : attr("muted", null);
  }

  /**
   * Sets the <code>controls</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
   * controls</a>
   */
  public VideoTag isControls() {
    return attr("controls");
  }

  /**
   * Applies {@link #isControls()} when {@code condition} is true and removes the attribute
   * otherwise, so a form control stays controlled either way (ADR 0013).
   */
  public VideoTag withCondControls(boolean condition) {
    return condition ? attr("controls") : attr("controls", null);
  }

  /**
   * Sets the <code>width</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
   * width</a>
   */
  public VideoTag withWidth(String value) {
    return attr("width", value);
  }

  /**
   * Applies {@link #withWidth(String)} only when {@code condition} is true.
   */
  public VideoTag withCondWidth(boolean condition, String value) {
    return condition ? attr("width", value) : self();
  }

  /**
   * Sets the <code>height</code> attribute.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/video">MDN:
   * height</a>
   */
  public VideoTag withHeight(String value) {
    return attr("height", value);
  }

  /**
   * Applies {@link #withHeight(String)} only when {@code condition} is true.
   */
  public VideoTag withCondHeight(boolean condition, String value) {
    return condition ? attr("height", value) : self();
  }
}
