// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act.html.tags;

import j2act.EmptyTag;

/**
 * The <code>&lt;wbr&gt;</code> element.
 *
 * <p>The wbr element represents a line break opportunity.
 *
 * <p>Baseline: widely available since 2018-01-29.
 *
 * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/wbr">MDN:
 * &lt;wbr&gt;</a>
 */
public final class WbrTag extends EmptyTag<WbrTag> {

  public WbrTag() {
    super("wbr");
  }
}
