// Generated by j2act-codegen. Do not edit; regenerate with:
//   ./mvnw -pl j2act-codegen compile exec:java
// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).
// API shape follows j2html (Apache-2.0). See NOTICE.
package j2act;

/**
 * Global attributes, valid on every element. Inline <code>on*</code> handler attributes are left
 * out on purpose: events are server handlers (<code>onClick</code>, <code>onInput</code>,
 * <code>onChange</code>) declared on Tag.
 */
public interface GlobalAttributes<T extends Tag<T>> {

  T self();

  T attr(String name, Object value);

  T attr(String name);

  /**
   * Sets the <code>accesskey</code> attribute.
   *
   * <p>Provides a hint for generating a keyboard shortcut for the current element. This attribute
   * consists of a space-separated list of characters. The browser should use the first one that
   * exists on the computer keyboard layout.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/accesskey">MDN:
   * accesskey</a>
   */
  default T withAccesskey(String value) {
    return attr("accesskey", value);
  }

  /**
   * Applies {@link #withAccesskey(String)} only when {@code condition} is true.
   */
  default T withCondAccesskey(boolean condition, String value) {
    return condition ? attr("accesskey", value) : self();
  }

  /**
   * Sets the <code>autocapitalize</code> attribute.
   *
   * <p>Controls whether and how text input is automatically capitalized as it is entered/edited by
   * the user. It can have the following values:
   *
   * <p>* <code>off</code> or <code>none</code>, no autocapitalization is applied (all letters
   * default to lowercase) * <code>on</code> or <code>sentences</code>, the first letter of each
   * sentence defaults to a capital letter; all other letters default to lowercase *
   * <code>words</code>, the first letter of each word defaults to a capital letter; all other
   * letters default to lowercase * <code>characters</code>, all letters should default to uppercase
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/autocapitalize">MDN:
   * autocapitalize</a>
   */
  default T withAutocapitalize(String value) {
    return attr("autocapitalize", value);
  }

  /**
   * Applies {@link #withAutocapitalize(String)} only when {@code condition} is true.
   */
  default T withCondAutocapitalize(boolean condition, String value) {
    return condition ? attr("autocapitalize", value) : self();
  }

  /**
   * Sets the <code>autocorrect</code> attribute.
   *
   * <p>Controls whether autocorrection of editable text is enabled for spelling and/or punctuation
   * errors.
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/autocorrect">MDN:
   * autocorrect</a>
   */
  default T withAutocorrect(String value) {
    return attr("autocorrect", value);
  }

  /**
   * Applies {@link #withAutocorrect(String)} only when {@code condition} is true.
   */
  default T withCondAutocorrect(boolean condition, String value) {
    return condition ? attr("autocorrect", value) : self();
  }

  /**
   * Sets the <code>autofocus</code> attribute.
   *
   * <p>Indicates that an element should be focused on page load, or when the <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Element/dialog"><code>&lt;dialog&gt;</code></a>
   * that it is part of is displayed.
   *
   * <p>Baseline: widely available since 2025-09-27.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/autofocus">MDN:
   * autofocus</a>
   */
  default T isAutofocus() {
    return attr("autofocus");
  }

  /**
   * Applies {@link #isAutofocus()} only when {@code condition} is true.
   */
  default T withCondAutofocus(boolean condition) {
    return condition ? attr("autofocus") : self();
  }

  /**
   * Sets the <code>class</code> attribute.
   *
   * <p>A space-separated list of the classes of the element. Classes allows CSS and JavaScript to
   * select and access specific elements via the <a
   * href="https://developer.mozilla.org/docs/Web/CSS/Class_selectors">class selectors</a> or
   * functions like the method
   * [<code>Document.getElementsByClassName()</code>](https://developer.mozilla.org/docs/Web/API/Document/getElementsByClassName
   * "returns an array-like object of all child elements which have all of the given class names.").
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/class">MDN:
   * class</a>
   */
  default T withClass(String value) {
    return attr("class", value);
  }

  /**
   * Applies {@link #withClass(String)} only when {@code condition} is true.
   */
  default T withCondClass(boolean condition, String value) {
    return condition ? attr("class", value) : self();
  }

  /**
   * Sets the <code>contenteditable</code> attribute.
   *
   * <p>An enumerated attribute indicating if the element should be editable by the user. If so, the
   * browser modifies its widget to allow editing. The attribute must take one of the following
   * values:
   *
   * <p>* <code>true</code> or the _empty string_, which indicates that the element must be editable;
   * * <code>false</code>, which indicates that the element must not be editable.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/contenteditable">MDN:
   * contenteditable</a>
   */
  default T withContenteditable(String value) {
    return attr("contenteditable", value);
  }

  /**
   * Applies {@link #withContenteditable(String)} only when {@code condition} is true.
   */
  default T withCondContenteditable(boolean condition, String value) {
    return condition ? attr("contenteditable", value) : self();
  }

  /**
   * Sets <code>contenteditable="true"</code>. See {@link #withContenteditable(String)}.
   */
  default T isContenteditable() {
    return attr("contenteditable", "true");
  }

  /**
   * Sets the <code>contextmenu</code> attribute.
   *
   * <p>The <code><a href="#attr-id">**id**</a></code> of a
   * [<code>&lt;menu&gt;</code>](https://developer.mozilla.org/docs/Web/HTML/Element/menu "The HTML
   * &lt;menu&gt; element represents a group of commands that a user can perform or activate. This
   * includes both list menus, which might appear across the top of a screen, as well as context
   * menus, such as those that might appear underneath a button after it has been clicked.") to use
   * as the contextual menu for this element.
   */
  default T withContextmenu(String value) {
    return attr("contextmenu", value);
  }

  /**
   * Applies {@link #withContextmenu(String)} only when {@code condition} is true.
   */
  default T withCondContextmenu(boolean condition, String value) {
    return condition ? attr("contextmenu", value) : self();
  }

  /**
   * Sets the <code>dir</code> attribute.
   *
   * <p>An enumerated attribute indicating the directionality of the element's text. It can have the
   * following values:
   *
   * <p>* <code>ltr</code>, which means _left to right_ and is to be used for languages that are
   * written from the left to the right (like English); * <code>rtl</code>, which means _right to
   * left_ and is to be used for languages that are written from the right to the left (like Arabic);
   * * <code>auto</code>, which lets the user agent decide. It uses a basic algorithm as it parses
   * the characters inside the element until it finds a character with a strong directionality, then
   * it applies that directionality to the whole element.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/dir">MDN:
   * dir</a>
   */
  default T withDir(String value) {
    return attr("dir", value);
  }

  /**
   * Applies {@link #withDir(String)} only when {@code condition} is true.
   */
  default T withCondDir(boolean condition, String value) {
    return condition ? attr("dir", value) : self();
  }

  /**
   * Sets the <code>draggable</code> attribute.
   *
   * <p>An enumerated attribute indicating whether the element can be dragged, using the <a
   * href="https://developer.mozilla.org/docs/DragDrop/Drag_and_Drop">Drag and Drop API</a>. It can
   * have the following values:
   *
   * <p>* <code>true</code>, which indicates that the element may be dragged * <code>false</code>,
   * which indicates that the element may not be dragged.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/draggable">MDN:
   * draggable</a>
   */
  default T withDraggable(String value) {
    return attr("draggable", value);
  }

  /**
   * Applies {@link #withDraggable(String)} only when {@code condition} is true.
   */
  default T withCondDraggable(boolean condition, String value) {
    return condition ? attr("draggable", value) : self();
  }

  /**
   * Sets <code>draggable="true"</code>. See {@link #withDraggable(String)}.
   */
  default T isDraggable() {
    return attr("draggable", "true");
  }

  /**
   * Sets the <code>dropzone</code> attribute.
   *
   * <p>An enumerated attribute indicating what types of content can be dropped on an element, using
   * the <a href="https://developer.mozilla.org/docs/DragDrop/Drag_and_Drop">Drag and Drop API</a>.
   * It can have the following values:
   *
   * <p>* <code>copy</code>, which indicates that dropping will create a copy of the element that was
   * dragged * <code>move</code>, which indicates that the element that was dragged will be moved to
   * this new location. * <code>link</code>, will create a link to the dragged data.
   */
  default T withDropzone(String value) {
    return attr("dropzone", value);
  }

  /**
   * Applies {@link #withDropzone(String)} only when {@code condition} is true.
   */
  default T withCondDropzone(boolean condition, String value) {
    return condition ? attr("dropzone", value) : self();
  }

  /**
   * Sets the <code>enterkeyhint</code> attribute.
   *
   * <p>An enumerated attribute defining what action label (or icon) to present for the enter key on
   * virtual keyboards.
   *
   * <p>Baseline: widely available since 2024-05-02.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/enterkeyhint">MDN:
   * enterkeyhint</a>
   */
  default T withEnterkeyhint(String value) {
    return attr("enterkeyhint", value);
  }

  /**
   * Applies {@link #withEnterkeyhint(String)} only when {@code condition} is true.
   */
  default T withCondEnterkeyhint(boolean condition, String value) {
    return condition ? attr("enterkeyhint", value) : self();
  }

  /**
   * Sets the <code>exportparts</code> attribute.
   *
   * <p>Used to transitively export shadow parts from a nested shadow tree into a containing light
   * tree.
   *
   * <p>Baseline: widely available since 2023-01-28.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/exportparts">MDN:
   * exportparts</a>
   */
  default T withExportparts(String value) {
    return attr("exportparts", value);
  }

  /**
   * Applies {@link #withExportparts(String)} only when {@code condition} is true.
   */
  default T withCondExportparts(boolean condition, String value) {
    return condition ? attr("exportparts", value) : self();
  }

  /**
   * Sets the <code>hidden</code> attribute.
   *
   * <p>A Boolean attribute indicates that the element is not yet, or is no longer, _relevant_. For
   * example, it can be used to hide elements of the page that can't be used until the login process
   * has been completed. The browser won't render such elements. This attribute must not be used to
   * hide content that could legitimately be shown.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/hidden">MDN:
   * hidden</a>
   */
  default T isHidden() {
    return attr("hidden");
  }

  /**
   * Applies {@link #isHidden()} only when {@code condition} is true.
   */
  default T withCondHidden(boolean condition) {
    return condition ? attr("hidden") : self();
  }

  /**
   * Sets the <code>id</code> attribute.
   *
   * <p>Defines a unique identifier (ID) which must be unique in the whole document. Its purpose is
   * to identify the element when linking (using a fragment identifier), scripting, or styling (with
   * CSS).
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/id">MDN:
   * id</a>
   */
  default T withId(String value) {
    return attr("id", value);
  }

  /**
   * Applies {@link #withId(String)} only when {@code condition} is true.
   */
  default T withCondId(boolean condition, String value) {
    return condition ? attr("id", value) : self();
  }

  /**
   * Sets the <code>inert</code> attribute.
   *
   * <p>Indicates that the element and all of its flat tree descendants become _inert_. Modal
   * <code>&lt;dialog&gt;</code>s generated with <a
   * href="https://developer.mozilla.org/docs/Web/API/HTMLDialogElement/showModal"><code>showModal()</code></a>
   * escape inertness, meaning that they don't inherit inertness from their ancestors, but can only
   * be made inert by having the <code>inert</code> attribute explicitly set on themselves.
   *
   * <p>Baseline: widely available since 2025-10-11.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/inert">MDN:
   * inert</a>
   */
  default T isInert() {
    return attr("inert");
  }

  /**
   * Applies {@link #isInert()} only when {@code condition} is true.
   */
  default T withCondInert(boolean condition) {
    return condition ? attr("inert") : self();
  }

  /**
   * Sets the <code>inputmode</code> attribute.
   *
   * <p>Provides a hint to browsers as to the type of virtual keyboard configuration to use when
   * editing this element or its contents. Used primarily on
   * [<code>&lt;input&gt;</code>](https://developer.mozilla.org/docs/Web/HTML/Element/input "The HTML
   * &lt;input&gt; element is used to create interactive controls for web-based forms in order to
   * accept data from the user; a wide variety of types of input data and control widgets are
   * available, depending on the device and user agent.") elements, but is usable on any element
   * while in <code><a
   * href="https://developer.mozilla.org/docs/Web/HTML/Global_attributes#attr-contenteditable">contenteditable</a></code>
   * mode.
   *
   * <p>Baseline: widely available since 2024-06-07.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/inputmode">MDN:
   * inputmode</a>
   */
  default T withInputmode(String value) {
    return attr("inputmode", value);
  }

  /**
   * Applies {@link #withInputmode(String)} only when {@code condition} is true.
   */
  default T withCondInputmode(boolean condition, String value) {
    return condition ? attr("inputmode", value) : self();
  }

  /**
   * Sets the <code>is</code> attribute.
   *
   * <p>Allows you to specify that a standard HTML element should behave like a registered custom
   * built-in element (see <a
   * href="https://developer.mozilla.org/docs/Web/Web_Components/Using_custom_elements">Using custom
   * elements</a> for more details).
   *
   * <p>Limited availability: not yet supported in all major browsers.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/is">MDN:
   * is</a>
   */
  default T withIs(String value) {
    return attr("is", value);
  }

  /**
   * Applies {@link #withIs(String)} only when {@code condition} is true.
   */
  default T withCondIs(boolean condition, String value) {
    return condition ? attr("is", value) : self();
  }

  /**
   * Sets the <code>itemid</code> attribute.
   *
   * <p>The unique, global identifier of an item.
   */
  default T withItemid(String value) {
    return attr("itemid", value);
  }

  /**
   * Applies {@link #withItemid(String)} only when {@code condition} is true.
   */
  default T withCondItemid(boolean condition, String value) {
    return condition ? attr("itemid", value) : self();
  }

  /**
   * Sets the <code>itemprop</code> attribute.
   *
   * <p>Used to add properties to an item. Every HTML element may have an <code>itemprop</code>
   * attribute specified, where an <code>itemprop</code> consists of a name and value pair.
   */
  default T withItemprop(String value) {
    return attr("itemprop", value);
  }

  /**
   * Applies {@link #withItemprop(String)} only when {@code condition} is true.
   */
  default T withCondItemprop(boolean condition, String value) {
    return condition ? attr("itemprop", value) : self();
  }

  /**
   * Sets the <code>itemref</code> attribute.
   *
   * <p>Properties that are not descendants of an element with the <code>itemscope</code> attribute
   * can be associated with the item using an <code>itemref</code>. It provides a list of element ids
   * (not <code>itemid</code>s) with additional properties elsewhere in the document.
   */
  default T withItemref(String value) {
    return attr("itemref", value);
  }

  /**
   * Applies {@link #withItemref(String)} only when {@code condition} is true.
   */
  default T withCondItemref(boolean condition, String value) {
    return condition ? attr("itemref", value) : self();
  }

  /**
   * Sets the <code>itemscope</code> attribute.
   *
   * <p><code>itemscope</code> (usually) works along with <code><a
   * href="https://developer.mozilla.org/docs/Web/HTML/Global_attributes#attr-itemtype">itemtype</a></code>
   * to specify that the HTML contained in a block is about a particular item. <code>itemscope</code>
   * creates the Item and defines the scope of the <code>itemtype</code> associated with it.
   * <code>itemtype</code> is a valid URL of a vocabulary (such as <a
   * href="https://schema.org/">schema.org</a>) that describes the item and its properties context.
   */
  default T isItemscope() {
    return attr("itemscope");
  }

  /**
   * Applies {@link #isItemscope()} only when {@code condition} is true.
   */
  default T withCondItemscope(boolean condition) {
    return condition ? attr("itemscope") : self();
  }

  /**
   * Sets the <code>itemtype</code> attribute.
   *
   * <p>Specifies the URL of the vocabulary that will be used to define <code>itemprop</code>s (item
   * properties) in the data structure. <code><a
   * href="https://developer.mozilla.org/docs/Web/HTML/Global_attributes#attr-itemscope">itemscope</a></code>
   * is used to set the scope of where in the data structure the vocabulary set by
   * <code>itemtype</code> will be active.
   */
  default T withItemtype(String value) {
    return attr("itemtype", value);
  }

  /**
   * Applies {@link #withItemtype(String)} only when {@code condition} is true.
   */
  default T withCondItemtype(boolean condition, String value) {
    return condition ? attr("itemtype", value) : self();
  }

  /**
   * Sets the <code>lang</code> attribute.
   *
   * <p>Helps define the language of an element: the language that non-editable elements are in, or
   * the language that editable elements should be written in by the user. The attribute contains one
   * “language tag” (made of hyphen-separated “language subtags”) in the format defined in <a
   * href="https://www.ietf.org/rfc/bcp/bcp47.txt">_Tags for Identifying Languages (BCP47)_</a>. <a
   * href="#attr-xml:lang">**xml:lang**</a> has priority over it.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/lang">MDN:
   * lang</a>
   */
  default T withLang(String value) {
    return attr("lang", value);
  }

  /**
   * Applies {@link #withLang(String)} only when {@code condition} is true.
   */
  default T withCondLang(boolean condition, String value) {
    return condition ? attr("lang", value) : self();
  }

  /**
   * Sets the <code>nonce</code> attribute.
   *
   * <p>Defines a cryptographic nonce ("number used once") which can be used by <a
   * href="https://developer.mozilla.org/docs/Web/HTTP/Guides/CSP">Content Security Policy</a> to
   * determine whether or not a given fetch will be allowed to proceed for a given element.
   *
   * <p>Baseline: widely available since 2024-11-16.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/nonce">MDN:
   * nonce</a>
   */
  default T withNonce(String value) {
    return attr("nonce", value);
  }

  /**
   * Applies {@link #withNonce(String)} only when {@code condition} is true.
   */
  default T withCondNonce(boolean condition, String value) {
    return condition ? attr("nonce", value) : self();
  }

  /**
   * Sets the <code>part</code> attribute.
   *
   * <p>A space-separated list of the part names of the element. Part names allows CSS to select and
   * style specific elements in a shadow tree via the
   * [<code>::part</code>](https://developer.mozilla.org/docs/Web/CSS/::part "The ::part CSS
   * pseudo-element represents any element within a shadow tree that has a matching part attribute.")
   * pseudo-element.
   *
   * <p>Baseline: widely available since 2023-01-28.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/part">MDN:
   * part</a>
   */
  default T withPart(String value) {
    return attr("part", value);
  }

  /**
   * Applies {@link #withPart(String)} only when {@code condition} is true.
   */
  default T withCondPart(boolean condition, String value) {
    return condition ? attr("part", value) : self();
  }

  /**
   * Sets the <code>popover</code> attribute.
   *
   * <p>Designates an element as a popover element.
   *
   * <p>Baseline: newly available since 2024-04-16.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/popover">MDN:
   * popover</a>
   */
  default T withPopover(String value) {
    return attr("popover", value);
  }

  /**
   * Applies {@link #withPopover(String)} only when {@code condition} is true.
   */
  default T withCondPopover(boolean condition, String value) {
    return condition ? attr("popover", value) : self();
  }

  /**
   * Sets the <code>role</code> attribute.
   */
  default T withRole(String value) {
    return attr("role", value);
  }

  /**
   * Applies {@link #withRole(String)} only when {@code condition} is true.
   */
  default T withCondRole(boolean condition, String value) {
    return condition ? attr("role", value) : self();
  }

  /**
   * Sets the <code>slot</code> attribute.
   *
   * <p>Assigns a slot in a <a
   * href="https://developer.mozilla.org/docs/Web/Web_Components/Shadow_DOM">shadow DOM</a> shadow
   * tree to an element: An element with a <code>slot</code> attribute is assigned to the slot
   * created by the
   * [<code>&lt;slot&gt;</code>](https://developer.mozilla.org/docs/Web/HTML/Element/slot "The HTML
   * &lt;slot&gt; element—part of the Web Components technology suite—is a placeholder inside a web
   * component that you can fill with your own markup, which lets you create separate DOM trees and
   * present them together.") element whose <code><a
   * href="https://developer.mozilla.org/docs/Web/HTML/Element/slot#attr-name">name</a></code>
   * attribute's value matches that <code>slot</code> attribute's value.
   *
   * <p>Baseline: widely available since 2022-07-15.
   *
   * @see <a href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/slot">MDN:
   * slot</a>
   */
  default T withSlot(String value) {
    return attr("slot", value);
  }

  /**
   * Applies {@link #withSlot(String)} only when {@code condition} is true.
   */
  default T withCondSlot(boolean condition, String value) {
    return condition ? attr("slot", value) : self();
  }

  /**
   * Sets the <code>spellcheck</code> attribute.
   *
   * <p>An enumerated attribute defines whether the element may be checked for spelling errors. It
   * may have the following values:
   *
   * <p>* <code>true</code>, which indicates that the element should be, if possible, checked for
   * spelling errors; * <code>false</code>, which indicates that the element should not be checked
   * for spelling errors.
   *
   * <p>Baseline: widely available since 2020-05-28.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/spellcheck">MDN:
   * spellcheck</a>
   */
  default T withSpellcheck(String value) {
    return attr("spellcheck", value);
  }

  /**
   * Applies {@link #withSpellcheck(String)} only when {@code condition} is true.
   */
  default T withCondSpellcheck(boolean condition, String value) {
    return condition ? attr("spellcheck", value) : self();
  }

  /**
   * Sets <code>spellcheck="true"</code>. See {@link #withSpellcheck(String)}.
   */
  default T isSpellcheck() {
    return attr("spellcheck", "true");
  }

  /**
   * Sets the <code>style</code> attribute.
   *
   * <p>Contains <a href="https://developer.mozilla.org/docs/Web/CSS">CSS</a> styling declarations to
   * be applied to the element. Note that it is recommended for styles to be defined in a separate
   * file or files. This attribute and the
   * [<code>&lt;style&gt;</code>](https://developer.mozilla.org/docs/Web/HTML/Element/style "The HTML
   * &lt;style&gt; element contains style information for a document, or part of a document.")
   * element have mainly the purpose of allowing for quick styling, for example for testing purposes.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/style">MDN:
   * style</a>
   */
  default T withStyle(String value) {
    return attr("style", value);
  }

  /**
   * Applies {@link #withStyle(String)} only when {@code condition} is true.
   */
  default T withCondStyle(boolean condition, String value) {
    return condition ? attr("style", value) : self();
  }

  /**
   * Sets the <code>tabindex</code> attribute.
   *
   * <p>An integer attribute indicating if the element can take input focus (is _focusable_), if it
   * should participate to sequential keyboard navigation, and if so, at what position. It can take
   * several values:
   *
   * <p>* a _negative value_ means that the element should be focusable, but should not be reachable
   * via sequential keyboard navigation; * <code>0</code> means that the element should be focusable
   * and reachable via sequential keyboard navigation, but its relative order is defined by the
   * platform convention; * a _positive value_ means that the element should be focusable and
   * reachable via sequential keyboard navigation; the order in which the elements are focused is the
   * increasing value of the <a href="#attr-tabindex">**tabindex**</a>. If several elements share the
   * same tabindex, their relative order follows their relative positions in the document.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/tabindex">MDN:
   * tabindex</a>
   */
  default T withTabindex(String value) {
    return attr("tabindex", value);
  }

  /**
   * Applies {@link #withTabindex(String)} only when {@code condition} is true.
   */
  default T withCondTabindex(boolean condition, String value) {
    return condition ? attr("tabindex", value) : self();
  }

  /**
   * Sets the <code>title</code> attribute.
   *
   * <p>Contains a text representing advisory information related to the element it belongs to. Such
   * information can typically, but not necessarily, be presented to the user as a tooltip.
   *
   * <p>Baseline: widely available since 2018-01-29.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/title">MDN:
   * title</a>
   */
  default T withTitle(String value) {
    return attr("title", value);
  }

  /**
   * Applies {@link #withTitle(String)} only when {@code condition} is true.
   */
  default T withCondTitle(boolean condition, String value) {
    return condition ? attr("title", value) : self();
  }

  /**
   * Sets the <code>translate</code> attribute.
   *
   * <p>An enumerated attribute that is used to specify whether an element's attribute values and the
   * values of its [<code>Text</code>](https://developer.mozilla.org/docs/Web/API/Text "The Text
   * interface represents the textual content of Element or Attr. If an element has no markup within
   * its content, it has a single child implementing Text that contains the element's text. However,
   * if the element contains markup, it is parsed into information items and Text nodes that form its
   * children.") node children are to be translated when the page is localized, or whether to leave
   * them unchanged. It can have the following values:
   *
   * <p>* empty string and <code>yes</code>, which indicates that the element will be translated. *
   * <code>no</code>, which indicates that the element will not be translated.
   *
   * <p>Baseline: widely available since 2025-09-14.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/translate">MDN:
   * translate</a>
   */
  default T withTranslate(String value) {
    return attr("translate", value);
  }

  /**
   * Applies {@link #withTranslate(String)} only when {@code condition} is true.
   */
  default T withCondTranslate(boolean condition, String value) {
    return condition ? attr("translate", value) : self();
  }

  /**
   * Sets <code>translate="yes"</code>. See {@link #withTranslate(String)}.
   */
  default T isTranslate() {
    return attr("translate", "yes");
  }

  /**
   * Sets the <code>virtualkeyboardpolicy</code> attribute.
   *
   * <p>When specified on an element that the element's content is editable (for example, it is an
   * <code>&lt;input&gt;</code> or <code>&lt;textarea&gt;</code> element, or an element with the
   * <code>contenteditable</code> attribute set), it controls the on-screen virtual keyboard behavior
   * on devices such as tablets, mobile phones, or other devices where a hardware keyboard may not be
   * available.
   *
   * <p>Limited availability: not yet supported in all major browsers. Experimental.
   *
   * @see <a
   * href="https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/virtualkeyboardpolicy">MDN:
   * virtualkeyboardpolicy</a>
   */
  default T withVirtualkeyboardpolicy(String value) {
    return attr("virtualkeyboardpolicy", value);
  }

  /**
   * Applies {@link #withVirtualkeyboardpolicy(String)} only when {@code condition} is true.
   */
  default T withCondVirtualkeyboardpolicy(boolean condition, String value) {
    return condition ? attr("virtualkeyboardpolicy", value) : self();
  }

  /**
   * Sets <code>virtualkeyboardpolicy="true"</code>. See {@link #withVirtualkeyboardpolicy(String)}.
   */
  default T isVirtualkeyboardpolicy() {
    return attr("virtualkeyboardpolicy", "true");
  }

  /**
   * Sets the <code>aria-activedescendant</code> attribute.
   *
   * <p>Identifies the currently active element when DOM focus is on a <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#composite"><code>composite</code></a> widget, <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#textbox"><code>textbox</code></a>, <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#group"><code>group</code></a>, or <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#application"><code>application</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-activedescendant">MDN:
   * aria-activedescendant</a>
   */
  default T withAriaActivedescendant(String value) {
    return attr("aria-activedescendant", value);
  }

  /**
   * Applies {@link #withAriaActivedescendant(String)} only when {@code condition} is true.
   */
  default T withCondAriaActivedescendant(boolean condition, String value) {
    return condition ? attr("aria-activedescendant", value) : self();
  }

  /**
   * Sets the <code>aria-atomic</code> attribute.
   *
   * <p>Indicates whether <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-assistive-technology">assistive technologies</a>
   * will present all, or only parts of, the changed region based on the change notifications defined
   * by the <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-relevant"><code>aria-relevant</code></a>
   * attribute.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-atomic">MDN: aria-atomic</a>
   */
  default T withAriaAtomic(String value) {
    return attr("aria-atomic", value);
  }

  /**
   * Applies {@link #withAriaAtomic(String)} only when {@code condition} is true.
   */
  default T withCondAriaAtomic(boolean condition, String value) {
    return condition ? attr("aria-atomic", value) : self();
  }

  /**
   * Sets <code>aria-atomic="true"</code>. See {@link #withAriaAtomic(String)}.
   */
  default T isAriaAtomic() {
    return attr("aria-atomic", "true");
  }

  /**
   * Sets the <code>aria-autocomplete</code> attribute.
   *
   * <p>Indicates whether inputting text could trigger display of one or more predictions of the
   * user's intended value for an input and specifies how predictions would be presented if they are
   * made.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-autocomplete">MDN: aria-autocomplete</a>
   */
  default T withAriaAutocomplete(String value) {
    return attr("aria-autocomplete", value);
  }

  /**
   * Applies {@link #withAriaAutocomplete(String)} only when {@code condition} is true.
   */
  default T withCondAriaAutocomplete(boolean condition, String value) {
    return condition ? attr("aria-autocomplete", value) : self();
  }

  /**
   * Sets the <code>aria-busy</code> attribute.
   *
   * <p>Indicates an element is being modified and that assistive technologies _MAY_ want to wait
   * until the modifications are complete before exposing them to the user.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-busy">MDN: aria-busy</a>
   */
  default T withAriaBusy(String value) {
    return attr("aria-busy", value);
  }

  /**
   * Applies {@link #withAriaBusy(String)} only when {@code condition} is true.
   */
  default T withCondAriaBusy(boolean condition, String value) {
    return condition ? attr("aria-busy", value) : self();
  }

  /**
   * Sets <code>aria-busy="true"</code>. See {@link #withAriaBusy(String)}.
   */
  default T isAriaBusy() {
    return attr("aria-busy", "true");
  }

  /**
   * Sets the <code>aria-checked</code> attribute.
   *
   * <p>Indicates the current "checked" <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-state">state</a> of checkboxes, radio buttons, and
   * other <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-widget">widgets</a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-pressed"><code>aria-pressed</code></a> and <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-selected"><code>aria-selected</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-checked">MDN: aria-checked</a>
   */
  default T withAriaChecked(String value) {
    return attr("aria-checked", value);
  }

  /**
   * Applies {@link #withAriaChecked(String)} only when {@code condition} is true.
   */
  default T withCondAriaChecked(boolean condition, String value) {
    return condition ? attr("aria-checked", value) : self();
  }

  /**
   * Sets the <code>aria-colcount</code> attribute.
   *
   * <p>Defines the total number of columns in a <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#table"><code>table</code></a>, <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#grid"><code>grid</code></a>, or <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#treegrid"><code>treegrid</code></a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-colindex"><code>aria-colindex</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-colcount">MDN: aria-colcount</a>
   */
  default T withAriaColcount(String value) {
    return attr("aria-colcount", value);
  }

  /**
   * Applies {@link #withAriaColcount(String)} only when {@code condition} is true.
   */
  default T withCondAriaColcount(boolean condition, String value) {
    return condition ? attr("aria-colcount", value) : self();
  }

  /**
   * Sets the <code>aria-colindex</code> attribute.
   *
   * <p>Defines an <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element's</a> column
   * index or position with respect to the total number of columns within a <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#table"><code>table</code></a>, <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#grid"><code>grid</code></a>, or <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#treegrid"><code>treegrid</code></a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-colcount"><code>aria-colcount</code></a> and <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-colspan"><code>aria-colspan</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-colindex">MDN: aria-colindex</a>
   */
  default T withAriaColindex(String value) {
    return attr("aria-colindex", value);
  }

  /**
   * Applies {@link #withAriaColindex(String)} only when {@code condition} is true.
   */
  default T withCondAriaColindex(boolean condition, String value) {
    return condition ? attr("aria-colindex", value) : self();
  }

  /**
   * Sets the <code>aria-colspan</code> attribute.
   *
   * <p>Defines the number of columns spanned by a cell or gridcell within a <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#table"><code>table</code></a>, <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#grid"><code>grid</code></a>, or <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#treegrid"><code>treegrid</code></a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-colindex"><code>aria-colindex</code></a> and <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-rowspan"><code>aria-rowspan</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-colspan">MDN: aria-colspan</a>
   */
  default T withAriaColspan(String value) {
    return attr("aria-colspan", value);
  }

  /**
   * Applies {@link #withAriaColspan(String)} only when {@code condition} is true.
   */
  default T withCondAriaColspan(boolean condition, String value) {
    return condition ? attr("aria-colspan", value) : self();
  }

  /**
   * Sets the <code>aria-controls</code> attribute.
   *
   * <p>Identifies the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> (or
   * elements) whose contents or presence are controlled by the current element. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-owns"><code>aria-owns</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-controls">MDN: aria-controls</a>
   */
  default T withAriaControls(String value) {
    return attr("aria-controls", value);
  }

  /**
   * Applies {@link #withAriaControls(String)} only when {@code condition} is true.
   */
  default T withCondAriaControls(boolean condition, String value) {
    return condition ? attr("aria-controls", value) : self();
  }

  /**
   * Sets the <code>aria-current</code> attribute.
   *
   * <p>Indicates the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> that
   * represents the current item within a container or set of related elements.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-current">MDN: aria-current</a>
   */
  default T withAriaCurrent(String value) {
    return attr("aria-current", value);
  }

  /**
   * Applies {@link #withAriaCurrent(String)} only when {@code condition} is true.
   */
  default T withCondAriaCurrent(boolean condition, String value) {
    return condition ? attr("aria-current", value) : self();
  }

  /**
   * Sets the <code>aria-describedby</code> attribute.
   *
   * <p>Identifies the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> (or
   * elements) that describes the <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-object">object</a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-labelledby"><code>aria-labelledby</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-describedby">MDN: aria-describedby</a>
   */
  default T withAriaDescribedby(String value) {
    return attr("aria-describedby", value);
  }

  /**
   * Applies {@link #withAriaDescribedby(String)} only when {@code condition} is true.
   */
  default T withCondAriaDescribedby(boolean condition, String value) {
    return condition ? attr("aria-describedby", value) : self();
  }

  /**
   * Sets the <code>aria-disabled</code> attribute.
   *
   * <p>Indicates that the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> is
   * <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-perceivable">perceivable</a> but disabled, so
   * it is not editable or otherwise <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-operable">operable</a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-hidden"><code>aria-hidden</code></a> and <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-readonly"><code>aria-readonly</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-disabled">MDN: aria-disabled</a>
   */
  default T withAriaDisabled(String value) {
    return attr("aria-disabled", value);
  }

  /**
   * Applies {@link #withAriaDisabled(String)} only when {@code condition} is true.
   */
  default T withCondAriaDisabled(boolean condition, String value) {
    return condition ? attr("aria-disabled", value) : self();
  }

  /**
   * Sets <code>aria-disabled="true"</code>. See {@link #withAriaDisabled(String)}.
   */
  default T isAriaDisabled() {
    return attr("aria-disabled", "true");
  }

  /**
   * Sets the <code>aria-dropeffect</code> attribute.
   *
   * <p>&#92;[Deprecated in ARIA 1.1&#92;] Indicates what functions can be performed when a dragged
   * object is released on the drop target.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-dropeffect">MDN: aria-dropeffect</a>
   */
  default T withAriaDropeffect(String value) {
    return attr("aria-dropeffect", value);
  }

  /**
   * Applies {@link #withAriaDropeffect(String)} only when {@code condition} is true.
   */
  default T withCondAriaDropeffect(boolean condition, String value) {
    return condition ? attr("aria-dropeffect", value) : self();
  }

  /**
   * Sets the <code>aria-errormessage</code> attribute.
   *
   * <p>Identifies the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> that
   * provides an error message for the <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-object">object</a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-invalid"><code>aria-invalid</code></a> and <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-describedby"><code>aria-describedby</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-errormessage">MDN: aria-errormessage</a>
   */
  default T withAriaErrormessage(String value) {
    return attr("aria-errormessage", value);
  }

  /**
   * Applies {@link #withAriaErrormessage(String)} only when {@code condition} is true.
   */
  default T withCondAriaErrormessage(boolean condition, String value) {
    return condition ? attr("aria-errormessage", value) : self();
  }

  /**
   * Sets the <code>aria-expanded</code> attribute.
   *
   * <p>Indicates whether the element, or another grouping element it controls, is currently expanded
   * or collapsed.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-expanded">MDN: aria-expanded</a>
   */
  default T withAriaExpanded(String value) {
    return attr("aria-expanded", value);
  }

  /**
   * Applies {@link #withAriaExpanded(String)} only when {@code condition} is true.
   */
  default T withCondAriaExpanded(boolean condition, String value) {
    return condition ? attr("aria-expanded", value) : self();
  }

  /**
   * Sets the <code>aria-flowto</code> attribute.
   *
   * <p>Identifies the next <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> (or
   * elements) in an alternate reading order of content which, at the user's discretion, allows
   * assistive technology to override the general default of reading in document source order.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-flowto">MDN: aria-flowto</a>
   */
  default T withAriaFlowto(String value) {
    return attr("aria-flowto", value);
  }

  /**
   * Applies {@link #withAriaFlowto(String)} only when {@code condition} is true.
   */
  default T withCondAriaFlowto(boolean condition, String value) {
    return condition ? attr("aria-flowto", value) : self();
  }

  /**
   * Sets the <code>aria-grabbed</code> attribute.
   *
   * <p>&#92;[Deprecated in ARIA 1.1&#92;] Indicates an element's "grabbed" <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-state">state</a> in a drag-and-drop operation.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-grabbed">MDN: aria-grabbed</a>
   */
  default T withAriaGrabbed(String value) {
    return attr("aria-grabbed", value);
  }

  /**
   * Applies {@link #withAriaGrabbed(String)} only when {@code condition} is true.
   */
  default T withCondAriaGrabbed(boolean condition, String value) {
    return condition ? attr("aria-grabbed", value) : self();
  }

  /**
   * Sets the <code>aria-haspopup</code> attribute.
   *
   * <p>Indicates the availability and type of interactive popup element, such as menu or dialog,
   * that can be triggered by an <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup">MDN: aria-haspopup</a>
   */
  default T withAriaHaspopup(String value) {
    return attr("aria-haspopup", value);
  }

  /**
   * Applies {@link #withAriaHaspopup(String)} only when {@code condition} is true.
   */
  default T withCondAriaHaspopup(boolean condition, String value) {
    return condition ? attr("aria-haspopup", value) : self();
  }

  /**
   * Sets the <code>aria-hidden</code> attribute.
   *
   * <p>Indicates whether the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a>
   * is exposed to an accessibility API. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-disabled"><code>aria-disabled</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-hidden">MDN: aria-hidden</a>
   */
  default T withAriaHidden(String value) {
    return attr("aria-hidden", value);
  }

  /**
   * Applies {@link #withAriaHidden(String)} only when {@code condition} is true.
   */
  default T withCondAriaHidden(boolean condition, String value) {
    return condition ? attr("aria-hidden", value) : self();
  }

  /**
   * Sets <code>aria-hidden="true"</code>. See {@link #withAriaHidden(String)}.
   */
  default T isAriaHidden() {
    return attr("aria-hidden", "true");
  }

  /**
   * Sets the <code>aria-invalid</code> attribute.
   *
   * <p>Indicates the entered value does not conform to the format expected by the application. See
   * related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-errormessage"><code>aria-errormessage</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-invalid">MDN: aria-invalid</a>
   */
  default T withAriaInvalid(String value) {
    return attr("aria-invalid", value);
  }

  /**
   * Applies {@link #withAriaInvalid(String)} only when {@code condition} is true.
   */
  default T withCondAriaInvalid(boolean condition, String value) {
    return condition ? attr("aria-invalid", value) : self();
  }

  /**
   * Sets the <code>aria-label</code> attribute.
   *
   * <p>Defines a string value that labels the current element. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-labelledby"><code>aria-labelledby</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-label">MDN: aria-label</a>
   */
  default T withAriaLabel(String value) {
    return attr("aria-label", value);
  }

  /**
   * Applies {@link #withAriaLabel(String)} only when {@code condition} is true.
   */
  default T withCondAriaLabel(boolean condition, String value) {
    return condition ? attr("aria-label", value) : self();
  }

  /**
   * Sets the <code>aria-labelledby</code> attribute.
   *
   * <p>Identifies the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> (or
   * elements) that labels the current element. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-describedby"><code>aria-describedby</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-labelledby">MDN: aria-labelledby</a>
   */
  default T withAriaLabelledby(String value) {
    return attr("aria-labelledby", value);
  }

  /**
   * Applies {@link #withAriaLabelledby(String)} only when {@code condition} is true.
   */
  default T withCondAriaLabelledby(boolean condition, String value) {
    return condition ? attr("aria-labelledby", value) : self();
  }

  /**
   * Sets the <code>aria-level</code> attribute.
   *
   * <p>Defines the hierarchical level of an <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> within a structure.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-level">MDN: aria-level</a>
   */
  default T withAriaLevel(String value) {
    return attr("aria-level", value);
  }

  /**
   * Applies {@link #withAriaLevel(String)} only when {@code condition} is true.
   */
  default T withCondAriaLevel(boolean condition, String value) {
    return condition ? attr("aria-level", value) : self();
  }

  /**
   * Sets the <code>aria-live</code> attribute.
   *
   * <p>Indicates that an <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> will
   * be updated, and describes the types of updates the <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-user-agent">user agents</a>, <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-assistive-technology">assistive technologies</a>,
   * and user can expect from the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-live-region">live
   * region</a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-live">MDN: aria-live</a>
   */
  default T withAriaLive(String value) {
    return attr("aria-live", value);
  }

  /**
   * Applies {@link #withAriaLive(String)} only when {@code condition} is true.
   */
  default T withCondAriaLive(boolean condition, String value) {
    return condition ? attr("aria-live", value) : self();
  }

  /**
   * Sets the <code>aria-modal</code> attribute.
   *
   * <p>Indicates whether an <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> is
   * modal when displayed.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-modal">MDN: aria-modal</a>
   */
  default T withAriaModal(String value) {
    return attr("aria-modal", value);
  }

  /**
   * Applies {@link #withAriaModal(String)} only when {@code condition} is true.
   */
  default T withCondAriaModal(boolean condition, String value) {
    return condition ? attr("aria-modal", value) : self();
  }

  /**
   * Sets <code>aria-modal="true"</code>. See {@link #withAriaModal(String)}.
   */
  default T isAriaModal() {
    return attr("aria-modal", "true");
  }

  /**
   * Sets the <code>aria-multiline</code> attribute.
   *
   * <p>Indicates whether a text box accepts multiple lines of input or only a single line.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-multiline">MDN: aria-multiline</a>
   */
  default T withAriaMultiline(String value) {
    return attr("aria-multiline", value);
  }

  /**
   * Applies {@link #withAriaMultiline(String)} only when {@code condition} is true.
   */
  default T withCondAriaMultiline(boolean condition, String value) {
    return condition ? attr("aria-multiline", value) : self();
  }

  /**
   * Sets <code>aria-multiline="true"</code>. See {@link #withAriaMultiline(String)}.
   */
  default T isAriaMultiline() {
    return attr("aria-multiline", "true");
  }

  /**
   * Sets the <code>aria-multiselectable</code> attribute.
   *
   * <p>Indicates that the user may select more than one item from the current selectable
   * descendants.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-multiselectable">MDN:
   * aria-multiselectable</a>
   */
  default T withAriaMultiselectable(String value) {
    return attr("aria-multiselectable", value);
  }

  /**
   * Applies {@link #withAriaMultiselectable(String)} only when {@code condition} is true.
   */
  default T withCondAriaMultiselectable(boolean condition, String value) {
    return condition ? attr("aria-multiselectable", value) : self();
  }

  /**
   * Sets <code>aria-multiselectable="true"</code>. See {@link #withAriaMultiselectable(String)}.
   */
  default T isAriaMultiselectable() {
    return attr("aria-multiselectable", "true");
  }

  /**
   * Sets the <code>aria-orientation</code> attribute.
   *
   * <p>Indicates whether the element's orientation is horizontal, vertical, or unknown/ambiguous.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-orientation">MDN: aria-orientation</a>
   */
  default T withAriaOrientation(String value) {
    return attr("aria-orientation", value);
  }

  /**
   * Applies {@link #withAriaOrientation(String)} only when {@code condition} is true.
   */
  default T withCondAriaOrientation(boolean condition, String value) {
    return condition ? attr("aria-orientation", value) : self();
  }

  /**
   * Sets the <code>aria-owns</code> attribute.
   *
   * <p>Identifies an <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> (or
   * elements) in order to define a visual, functional, or contextual parent/child <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-relationship">relationship</a> between DOM
   * elements where the DOM hierarchy cannot be used to represent the relationship. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-controls"><code>aria-controls</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-owns">MDN: aria-owns</a>
   */
  default T withAriaOwns(String value) {
    return attr("aria-owns", value);
  }

  /**
   * Applies {@link #withAriaOwns(String)} only when {@code condition} is true.
   */
  default T withCondAriaOwns(boolean condition, String value) {
    return condition ? attr("aria-owns", value) : self();
  }

  /**
   * Sets the <code>aria-placeholder</code> attribute.
   *
   * <p>Defines a short hint (a word or short phrase) intended to aid the user with data entry when
   * the control has no value. A hint could be a sample value or a brief description of the expected
   * format.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-placeholder">MDN: aria-placeholder</a>
   */
  default T withAriaPlaceholder(String value) {
    return attr("aria-placeholder", value);
  }

  /**
   * Applies {@link #withAriaPlaceholder(String)} only when {@code condition} is true.
   */
  default T withCondAriaPlaceholder(boolean condition, String value) {
    return condition ? attr("aria-placeholder", value) : self();
  }

  /**
   * Sets the <code>aria-posinset</code> attribute.
   *
   * <p>Defines an <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a>'s number or
   * position in the current set of listitems or treeitems. Not required if all elements in the set
   * are present in the DOM. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-setsize"><code>aria-setsize</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-posinset">MDN: aria-posinset</a>
   */
  default T withAriaPosinset(String value) {
    return attr("aria-posinset", value);
  }

  /**
   * Applies {@link #withAriaPosinset(String)} only when {@code condition} is true.
   */
  default T withCondAriaPosinset(boolean condition, String value) {
    return condition ? attr("aria-posinset", value) : self();
  }

  /**
   * Sets the <code>aria-pressed</code> attribute.
   *
   * <p>Indicates the current "pressed" <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-state">state</a> of toggle buttons. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-checked"><code>aria-checked</code></a> and <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-selected"><code>aria-selected</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-pressed">MDN: aria-pressed</a>
   */
  default T withAriaPressed(String value) {
    return attr("aria-pressed", value);
  }

  /**
   * Applies {@link #withAriaPressed(String)} only when {@code condition} is true.
   */
  default T withCondAriaPressed(boolean condition, String value) {
    return condition ? attr("aria-pressed", value) : self();
  }

  /**
   * Sets the <code>aria-readonly</code> attribute.
   *
   * <p>Indicates that the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> is
   * not editable, but is otherwise <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-operable">operable</a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-disabled"><code>aria-disabled</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-readonly">MDN: aria-readonly</a>
   */
  default T withAriaReadonly(String value) {
    return attr("aria-readonly", value);
  }

  /**
   * Applies {@link #withAriaReadonly(String)} only when {@code condition} is true.
   */
  default T withCondAriaReadonly(boolean condition, String value) {
    return condition ? attr("aria-readonly", value) : self();
  }

  /**
   * Sets <code>aria-readonly="true"</code>. See {@link #withAriaReadonly(String)}.
   */
  default T isAriaReadonly() {
    return attr("aria-readonly", "true");
  }

  /**
   * Sets the <code>aria-relevant</code> attribute.
   *
   * <p>Indicates what notifications the user agent will trigger when the accessibility tree within a
   * live region is modified. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-atomic"><code>aria-atomic</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-relevant">MDN: aria-relevant</a>
   */
  default T withAriaRelevant(String value) {
    return attr("aria-relevant", value);
  }

  /**
   * Applies {@link #withAriaRelevant(String)} only when {@code condition} is true.
   */
  default T withCondAriaRelevant(boolean condition, String value) {
    return condition ? attr("aria-relevant", value) : self();
  }

  /**
   * Sets the <code>aria-required</code> attribute.
   *
   * <p>Indicates that user input is required on the <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> before a form may be
   * submitted.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-required">MDN: aria-required</a>
   */
  default T withAriaRequired(String value) {
    return attr("aria-required", value);
  }

  /**
   * Applies {@link #withAriaRequired(String)} only when {@code condition} is true.
   */
  default T withCondAriaRequired(boolean condition, String value) {
    return condition ? attr("aria-required", value) : self();
  }

  /**
   * Sets <code>aria-required="true"</code>. See {@link #withAriaRequired(String)}.
   */
  default T isAriaRequired() {
    return attr("aria-required", "true");
  }

  /**
   * Sets the <code>aria-roledescription</code> attribute.
   *
   * <p>Defines a human-readable, author-localized description for the <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-role">role</a> of an <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-roledescription">MDN:
   * aria-roledescription</a>
   */
  default T withAriaRoledescription(String value) {
    return attr("aria-roledescription", value);
  }

  /**
   * Applies {@link #withAriaRoledescription(String)} only when {@code condition} is true.
   */
  default T withCondAriaRoledescription(boolean condition, String value) {
    return condition ? attr("aria-roledescription", value) : self();
  }

  /**
   * Sets the <code>aria-rowcount</code> attribute.
   *
   * <p>Defines the total number of rows in a <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#table"><code>table</code></a>, <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#grid"><code>grid</code></a>, or <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#treegrid"><code>treegrid</code></a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-rowindex"><code>aria-rowindex</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-rowcount">MDN: aria-rowcount</a>
   */
  default T withAriaRowcount(String value) {
    return attr("aria-rowcount", value);
  }

  /**
   * Applies {@link #withAriaRowcount(String)} only when {@code condition} is true.
   */
  default T withCondAriaRowcount(boolean condition, String value) {
    return condition ? attr("aria-rowcount", value) : self();
  }

  /**
   * Sets the <code>aria-rowindex</code> attribute.
   *
   * <p>Defines an <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element's</a> row index
   * or position with respect to the total number of rows within a <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#table"><code>table</code></a>, <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#grid"><code>grid</code></a>, or <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#treegrid"><code>treegrid</code></a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-rowcount"><code>aria-rowcount</code></a> and <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-rowspan"><code>aria-rowspan</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-rowindex">MDN: aria-rowindex</a>
   */
  default T withAriaRowindex(String value) {
    return attr("aria-rowindex", value);
  }

  /**
   * Applies {@link #withAriaRowindex(String)} only when {@code condition} is true.
   */
  default T withCondAriaRowindex(boolean condition, String value) {
    return condition ? attr("aria-rowindex", value) : self();
  }

  /**
   * Sets the <code>aria-rowspan</code> attribute.
   *
   * <p>Defines the number of rows spanned by a cell or gridcell within a <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#table"><code>table</code></a>, <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#grid"><code>grid</code></a>, or <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#treegrid"><code>treegrid</code></a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-rowindex"><code>aria-rowindex</code></a> and <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-colspan"><code>aria-colspan</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-rowspan">MDN: aria-rowspan</a>
   */
  default T withAriaRowspan(String value) {
    return attr("aria-rowspan", value);
  }

  /**
   * Applies {@link #withAriaRowspan(String)} only when {@code condition} is true.
   */
  default T withCondAriaRowspan(boolean condition, String value) {
    return condition ? attr("aria-rowspan", value) : self();
  }

  /**
   * Sets the <code>aria-selected</code> attribute.
   *
   * <p>Indicates the current "selected" <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-state">state</a> of various <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-widget">widgets</a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-checked"><code>aria-checked</code></a> and <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-pressed"><code>aria-pressed</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-selected">MDN: aria-selected</a>
   */
  default T withAriaSelected(String value) {
    return attr("aria-selected", value);
  }

  /**
   * Applies {@link #withAriaSelected(String)} only when {@code condition} is true.
   */
  default T withCondAriaSelected(boolean condition, String value) {
    return condition ? attr("aria-selected", value) : self();
  }

  /**
   * Sets the <code>aria-setsize</code> attribute.
   *
   * <p>Defines the number of items in the current set of listitems or treeitems. Not required if all
   * elements in the set are present in the DOM. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-posinset"><code>aria-posinset</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-setsize">MDN: aria-setsize</a>
   */
  default T withAriaSetsize(String value) {
    return attr("aria-setsize", value);
  }

  /**
   * Applies {@link #withAriaSetsize(String)} only when {@code condition} is true.
   */
  default T withCondAriaSetsize(boolean condition, String value) {
    return condition ? attr("aria-setsize", value) : self();
  }

  /**
   * Sets the <code>aria-sort</code> attribute.
   *
   * <p>Indicates if items in a table or grid are sorted in ascending or descending order.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-sort">MDN: aria-sort</a>
   */
  default T withAriaSort(String value) {
    return attr("aria-sort", value);
  }

  /**
   * Applies {@link #withAriaSort(String)} only when {@code condition} is true.
   */
  default T withCondAriaSort(boolean condition, String value) {
    return condition ? attr("aria-sort", value) : self();
  }

  /**
   * Sets the <code>aria-valuemax</code> attribute.
   *
   * <p>Defines the maximum allowed value for a range <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-widget">widget</a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-valuemax">MDN: aria-valuemax</a>
   */
  default T withAriaValuemax(String value) {
    return attr("aria-valuemax", value);
  }

  /**
   * Applies {@link #withAriaValuemax(String)} only when {@code condition} is true.
   */
  default T withCondAriaValuemax(boolean condition, String value) {
    return condition ? attr("aria-valuemax", value) : self();
  }

  /**
   * Sets the <code>aria-valuemin</code> attribute.
   *
   * <p>Defines the minimum allowed value for a range <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-widget">widget</a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-valuemin">MDN: aria-valuemin</a>
   */
  default T withAriaValuemin(String value) {
    return attr("aria-valuemin", value);
  }

  /**
   * Applies {@link #withAriaValuemin(String)} only when {@code condition} is true.
   */
  default T withCondAriaValuemin(boolean condition, String value) {
    return condition ? attr("aria-valuemin", value) : self();
  }

  /**
   * Sets the <code>aria-valuenow</code> attribute.
   *
   * <p>Defines the current value for a range <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-widget">widget</a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-valuetext"><code>aria-valuetext</code></a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-valuenow">MDN: aria-valuenow</a>
   */
  default T withAriaValuenow(String value) {
    return attr("aria-valuenow", value);
  }

  /**
   * Applies {@link #withAriaValuenow(String)} only when {@code condition} is true.
   */
  default T withCondAriaValuenow(boolean condition, String value) {
    return condition ? attr("aria-valuenow", value) : self();
  }

  /**
   * Sets the <code>aria-valuetext</code> attribute.
   *
   * <p>Defines the human readable text alternative of <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-valuenow"><code>aria-valuenow</code></a> for a
   * range <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-widget">widget</a>.
   *
   * @see <a href="https://www.w3.org/TR/wai-aria-1.1/#aria-valuetext">MDN: aria-valuetext</a>
   */
  default T withAriaValuetext(String value) {
    return attr("aria-valuetext", value);
  }

  /**
   * Applies {@link #withAriaValuetext(String)} only when {@code condition} is true.
   */
  default T withCondAriaValuetext(boolean condition, String value) {
    return condition ? attr("aria-valuetext", value) : self();
  }

  /**
   * Sets the <code>aria-details</code> attribute.
   *
   * <p>Identifies the <a href="https://www.w3.org/TR/wai-aria-1.1/#dfn-element">element</a> that
   * provides a detailed, extended description for the <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#dfn-object">object</a>. See related <a
   * href="https://www.w3.org/TR/wai-aria-1.1/#aria-describedby"><code>aria-describedby</code></a>.
   */
  default T withAriaDetails(String value) {
    return attr("aria-details", value);
  }

  /**
   * Applies {@link #withAriaDetails(String)} only when {@code condition} is true.
   */
  default T withCondAriaDetails(boolean condition, String value) {
    return condition ? attr("aria-details", value) : self();
  }

  /**
   * Sets the <code>aria-keyshortcuts</code> attribute.
   *
   * <p>Indicates keyboard shortcuts that an author has implemented to activate or give focus to an
   * element.
   */
  default T withAriaKeyshortcuts(String value) {
    return attr("aria-keyshortcuts", value);
  }

  /**
   * Applies {@link #withAriaKeyshortcuts(String)} only when {@code condition} is true.
   */
  default T withCondAriaKeyshortcuts(boolean condition, String value) {
    return condition ? attr("aria-keyshortcuts", value) : self();
  }
}
