package j2act.codegen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.stream.Stream;

/**
 * Generates the tag API: GlobalAttributes in j2act-core, one final class per element
 * and TagCreator in j2act-html. Output is checked in and verified by
 * GeneratedSourcesUpToDateTest. The shape follows j2html (see NOTICE).
 */
public final class Generate {

  static final String CORE = "j2act-core/src/main/java/j2act/";
  static final String HTML = "j2act-html/src/main/java/j2act/html/";
  static final String TAGS = HTML + "tags/";

  private static final String HEADER = ""
    + "// Generated by j2act-codegen. Do not edit; regenerate with:\n"
    + "//   ./mvnw -pl j2act-codegen compile exec:java\n"
    + "// Data: @vscode/web-custom-data (MIT), @mdn/browser-compat-data (CC0).\n"
    + "// API shape follows j2html (Apache-2.0). See NOTICE.\n";

  private static final String DEPRECATED_WHY = "marked deprecated in MDN browser-compat-data; avoid in new markup.";

  private Generate() {
  }

  public static void main(String[] args) throws IOException {
    Path root = Paths.get(args.length > 0 ? args[0] : "..").toAbsolutePath().normalize();
    Map<String, String> files = generate(Model.load());
    try (Stream<Path> old = Files.exists(root.resolve(TAGS)) ? Files.list(root.resolve(TAGS)) : Stream.empty()) {
      for (Path stale : (Iterable<Path>) old::iterator) {
        if (!files.containsKey(TAGS + stale.getFileName())) {
          Files.delete(stale);
        }
      }
    }
    for (Map.Entry<String, String> file : files.entrySet()) {
      Path path = root.resolve(file.getKey());
      Files.createDirectories(path.getParent());
      Files.write(path, file.getValue().getBytes(StandardCharsets.UTF_8));
    }
    System.out.println("Generated " + files.size() + " files under " + root);
  }

  /** Relative path to file content, for writing or for comparison in tests. */
  static Map<String, String> generate(Model model) {
    Map<String, String> files = new LinkedHashMap<>();
    files.put(CORE + "GlobalAttributes.java", globalAttributes(model));
    for (Model.Element element : model.elements) {
      files.put(TAGS + className(element) + ".java", tagClass(element));
    }
    files.put(HTML + "TagCreator.java", tagCreator(model));
    return files;
  }

  // ---- GlobalAttributes

  private static String globalAttributes(Model model) {
    StringBuilder b = new StringBuilder(HEADER).append("package j2act;\n\n");
    b.append(new Javadoc()
      .paragraph("Global attributes, valid on every element. Inline `on*` handler attributes are left out on purpose:"
        + " events are server handlers (`onClick`, `onInput`, `onChange`) declared on Tag.")
      .render(""));
    b.append("public interface GlobalAttributes<T extends Tag<T>> {\n\n");
    b.append("  T self();\n\n  T attr(String name, Object value);\n\n  T attr(String name);\n");
    Set<String> seen = new HashSet<>();
    for (Model.Attribute attr : model.globals) {
      attributeMethods(b, attr, "T", "default ", null, seen);
    }
    return b.append("}\n").toString();
  }

  // ---- tag classes

  private static String tagClass(Model.Element element) {
    String cls = className(element);
    String base = element.isVoid ? "EmptyTag" : "ContainerTag";
    StringBuilder b = new StringBuilder(HEADER).append("package j2act.html.tags;\n\n");
    b.append("import j2act.").append(base).append(";\n\n");
    b.append(elementDoc(element).render(""));
    if (element.deprecated) {
      b.append("@Deprecated\n");
    }
    b.append("public final class ").append(cls).append(" extends ").append(base).append('<').append(cls).append("> {\n\n");
    b.append("  public ").append(cls).append("() {\n    super(\"").append(element.name).append("\");\n  }\n");
    Set<String> seen = new HashSet<>();
    for (Model.Attribute attr : element.attributes) {
      attributeMethods(b, attr, cls, "public ", element, seen);
    }
    return b.append("}\n").toString();
  }

  private static Javadoc elementDoc(Model.Element element) {
    Javadoc doc = new Javadoc()
      .html("The <code>&lt;" + element.name + "&gt;</code> element.")
      .paragraph(element.description);
    String support = support(element.baseline, element.experimental);
    if (support != null) {
      doc.html(support);
    }
    return doc
      .see(element.mdn, "MDN: <" + element.name + ">")
      .deprecated(element.deprecated, "The <code>&lt;" + element.name + "&gt;</code> element is " + DEPRECATED_WHY);
  }

  /**
   * with/withCond for value attributes; is/withCond for boolean ones. Enumerated
   * true/false or yes/no attributes also get an is() that sets the affirmative value.
   */
  private static void attributeMethods(StringBuilder b, Model.Attribute attr, String self, String modifier,
                                       Model.Element element, Set<String> seen) {
    String suffix = methodSuffix(attr.name);
    String name = attr.name;
    Javadoc doc = new Javadoc().html("Sets the <code>" + name + "</code> attribute.").paragraph(attr.description);
    String support = support(attr.baseline, attr.experimental);
    if (support != null) {
      doc.html(support);
    }
    doc.see(attr.mdn, "MDN: " + name).deprecated(attr.deprecated, "The <code>" + name + "</code> attribute is " + DEPRECATED_WHY);
    String indent = "  ";
    String deprecated = attr.deprecated ? indent + "@Deprecated\n" : "";

    if (attr.bool) {
      method(b, seen, "is" + suffix + "()", doc.render(indent) + deprecated
        + indent + modifier + self + " is" + suffix + "() {\n"
        + indent + "  return attr(\"" + name + "\");\n" + indent + "}\n");
      method(b, seen, "withCond" + suffix + "(boolean)", condDoc(indent, "is" + suffix + "()") + deprecated
        + indent + modifier + self + " withCond" + suffix + "(boolean condition) {\n"
        + indent + "  return condition ? attr(\"" + name + "\") : self();\n" + indent + "}\n");
      return;
    }
    method(b, seen, "with" + suffix + "(String)", doc.render(indent) + deprecated
      + indent + modifier + self + " with" + suffix + "(String value) {\n"
      + indent + "  return attr(\"" + name + "\", value);\n" + indent + "}\n");
    method(b, seen, "withCond" + suffix + "(boolean,String)", condDoc(indent, "with" + suffix + "(String)") + deprecated
      + indent + modifier + self + " withCond" + suffix + "(boolean condition, String value) {\n"
      + indent + "  return condition ? attr(\"" + name + "\", value) : self();\n" + indent + "}\n");
    if (attr.valueless) {
      method(b, seen, "is" + suffix + "()", new Javadoc()
          .html("Sets <code>" + name + "</code> with no value. See {@link #with" + suffix + "(String)}.")
          .render(indent) + deprecated
        + indent + modifier + self + " is" + suffix + "() {\n"
        + indent + "  return attr(\"" + name + "\");\n" + indent + "}\n");
    }
    String affirmative = "b".equals(attr.valueSet) ? "true" : "y".equals(attr.valueSet) ? "yes" : null;
    if (affirmative != null) {
      method(b, seen, "is" + suffix + "()", new Javadoc()
          .html("Sets <code>" + name + "=\"" + affirmative + "\"</code>. See {@link #with" + suffix + "(String)}.")
          .render(indent) + deprecated
        + indent + modifier + self + " is" + suffix + "() {\n"
        + indent + "  return attr(\"" + name + "\", \"" + affirmative + "\");\n" + indent + "}\n");
    }
  }

  private static String condDoc(String indent, String target) {
    return new Javadoc().html("Applies {@link #" + target + "} only when {@code condition} is true.").render(indent);
  }

  /** Handwritten Tag/ContainerTag methods a generated attribute must never shadow. */
  private static final Set<String> RESERVED = Set.of(
    "withText(String)", "withKey(Object)", "withClasses(String...)", "withPending(DomContent)",
    "withDebounce(Duration)", "withData(String,String)", "withCondData(boolean,String,String)");

  private static void method(StringBuilder b, Set<String> seen, String signature, String source) {
    if (RESERVED.contains(signature)) {
      throw new IllegalStateException(signature + " would shadow a handwritten tag method;"
        + " exclude the attribute in data/overrides.json");
    }
    if (!seen.add(signature)) {
      throw new IllegalStateException("duplicate generated method " + signature);
    }
    b.append('\n').append(source);
  }

  private static String support(Model.Baseline baseline, boolean experimental) {
    String text = null;
    if (baseline != null) {
      switch (baseline.level) {
        case "high":
          text = "Baseline: widely available" + (baseline.highDate != null ? " since " + baseline.highDate : "") + ".";
          break;
        case "low":
          text = "Baseline: newly available" + (baseline.lowDate != null ? " since " + baseline.lowDate : "") + ".";
          break;
        default:
          text = "Limited availability: not yet supported in all major browsers.";
      }
    }
    if (experimental) {
      text = (text == null ? "" : text + " ") + "Experimental.";
    }
    return text;
  }

  // ---- TagCreator

  private static String tagCreator(Model model) {
    StringBuilder b = new StringBuilder(HEADER).append("package j2act.html;\n\n");
    b.append("import j2act.DomContent;\n");
    for (Model.Element element : model.elements) {
      b.append("import j2act.html.tags.").append(className(element)).append(";\n");
    }
    b.append('\n');
    b.append(new Javadoc()
      .paragraph("Static tag factories: `import static j2act.html.TagCreator.*`. Params are children only;"
        + " attributes are with* builders on the returned tag (ADR 0005). Helpers such as `each`, `iff`"
        + " and `join` come from TagHelpers.")
      .render(""));
    b.append("public final class TagCreator extends TagHelpers {\n\n  private TagCreator() {\n  }\n");
    for (Model.Element element : model.elements) {
      String cls = className(element);
      String f = element.name;
      Javadoc doc = new Javadoc()
        .html("Creates a <code>&lt;" + f + "&gt;</code> element.")
        .paragraph(Javadoc.firstSentence(element.description))
        .see(element.mdn, "MDN: <" + f + ">")
        .deprecated(element.deprecated, "The <code>&lt;" + f + "&gt;</code> element is " + DEPRECATED_WHY);
      String deprecated = element.deprecated ? "  @Deprecated\n" : "";
      String docText = doc.render("  ");
      b.append('\n').append(docText).append(deprecated)
        .append("  public static ").append(cls).append(' ').append(f).append("() {\n")
        .append("    return new ").append(cls).append("();\n  }\n");
      if (!element.isVoid) {
        b.append('\n').append(docText).append(deprecated)
          .append("  public static ").append(cls).append(' ').append(f).append("(String text) {\n")
          .append("    return new ").append(cls).append("().withText(text);\n  }\n");
        b.append('\n').append(docText).append(deprecated)
          .append("  public static ").append(cls).append(' ').append(f).append("(DomContent... children) {\n")
          .append("    return new ").append(cls).append("().with(children);\n  }\n");
      }
    }
    return b.append("}\n").toString();
  }

  // ---- naming

  static String className(Model.Element element) {
    return capitalize(element.name) + "Tag";
  }

  /** accept-charset to AcceptCharset, tabindex to Tabindex (j2html's casing). */
  static String methodSuffix(String attribute) {
    StringBuilder b = new StringBuilder();
    for (String part : attribute.split("-")) {
      b.append(capitalize(part));
    }
    return b.toString();
  }

  private static String capitalize(String s) {
    return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
  }
}
